### ISSUE TITLE
`AlwaysKeepUnsealedCopy = false` is not being honored.

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/boost#1003]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [X] Other

### Boost Version

```text
boost version 1.5.0+git.dbedffb
```

### Describe the Bug

**Hi Boost team 👋** 

After looking at logs, testing, talking with clients etc. in regards to issue https://github.com/filecoin-project/lotus/issues/9396
(Snap Deals always creates an unsealed copy even though "AlwaysKeepUnsealedCopy = false")

We think we have found the reason for why `AlwaysKeepUnsealedCopy = false` is not being honored:
https://github.com/filecoin-project/boost/blob/3c68f89975498c23fed70aad5dc928027a2ed475/storagemarket/provider.go#L591

Not all SP's or clients wants fast retrieval and should be able to opt out.

### Logging Information

```text
lotus-miner storage find 16273
In FILECOIN_SERVER (Unsealed, Cache, Update, UpdateCache)
	Sealing: false; Storage: true
	Local (/nfs/TechHedgeUnit3)
	URL: http://192.168.10.80:8001/remote/unsealed/s-t022352-16273 <---
```

### Repo Steps

1. Check that your configuration on the lotus miner is correct.
2. Run `lotus-miner sectors snap-up <sectornumb>`
3. Send a deal, import and seal deal into the snapped up sector
4. See that an unsealed copy was created in the long term storage.

**Comment by jacobheun** [comment]
Nice find! Yes, we should definitely fix this. 

_Context_: Archival/disaster recovery is a very real use case. I as a client might say, "I probably won't ever need this data, if I do, I'll contact you". We could make this easier in the future with a nice unseal cost story, but we should ensure support for the manual version works in the interim.
