### ISSUE TITLE
Add filter by Checkpoint

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#1014]
Currently it's possible to filter the list of deals by a search query, that matches against peer id, payload cid etc.
However it's not possible to filter by Checkpoint.

We should add an optional parameter to the deals endpoint to allow users to filter by checkpoint:
```
deals(query: String, checkpoint: String, cursor: ID, offset: Int, limit: Int): DealList!
```

**Comment by jacobheun** [comment]
The UI currently shows the 'State' rather than the Checkpoint, so based on a sync discussion we'll aim to expose the ability to filter on `State` rather than checkpoint. This will also give more granularity for later stages of deals.

**Comment by jacobheun** [comment]
After reviewing the internals of the code here, State is a computed property so for simplicity of this filtering by Checkpoint is the most direct path. Pulling some feedback from slack some requests to be able to filter by are:

* Filter all deals that are currently transferring, or waiting for offline import
* Filter for all deals that have been Accepted (and that are offline deals)

I'm reviewing the UX for the api and UI and will update when I have more thoughts on best path forward for these.
