### ISSUE TITLE
Add piece directory documentation for SPs

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#1018]
Add documentation about
- how to set up piece directory
  - leveldb vs couchbase (advantages of one over the other)
  - required resources (eg for N TB of deals, N GB of disk required by leveldb / couchbase - ask SPs to share their stats)
- architecture
  - schema
  - interface for other implementations (eg foundation db)

**Comment by brendalee** [comment]
tracking docs additions for LID here: https://github.com/filecoin-project/boost/issues/1453
