### ISSUE TITLE
Develop Concrete Load Testing Plan

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/boost#1026]
This work tracks discussions about developing a formal plan for load testing retrievals in Boost.

There is already #1019 and #877 but neither have developed into a concrete plan for what exactly we want to do. This work tracks that we need a plan before an implementation.

Acceptance criteria:
- plan outline document (notion/google/etc)
- individual github tickets as needed

**Comment by LaurenSpiegel** [comment]
Draft plan is here -- https://www.notion.so/pl-strflt/Retrieval-Test-Plan-b1662b4b4fad46bd9c0db15964cfff83
