### ISSUE TITLE
Decouple Index-provider for Boost from Lotus

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1033]
Currently, all the major code for index provider lives in the lotus and we only have a wrapper within Boost. This makes any changes required in index-provider very difficult as we need to wait for lotus release to upgrade the dependency.

I would recommend moving all the index-provider code to Boost repo and decouple this module. Lotus will be deprecating market soon and thus would have no use for this module.

**Comment by LexLuthr** [comment]
@dirkmc @nonsense Please let me know your thoughts.

https://github.com/filecoin-project/lotus/pull/9627 is waiting to be a part of the Lotus release is one example. Since we are planning more changes to indexing down the line, it would be good idea to move the module within Boost to allow faster updates.

**Comment by hannahhoward** [comment]
@LexLuthr FYI https://github.com/filecoin-project/boost/pull/967 also contains this change and is expected to merge with booster-bitswap final release.
