### ISSUE TITLE
Q1 2023: Help create SQL query to generate reports from Validation bot

### ISSUE THREAD

**Issue by marinakosti** [filecoin-project/boost#1039]
Please help create a query that I can run on a weekly basis in Validation bot database

I want to get a list of all SPs that were recorded in the system for the period of Mon - Sunday each week
(query should include specific dates (not last 7 days)

List of fields

- Multiaddress
- Peer ID
- Number of query requests
- Number of successful retrieval requests served
- Total volume of retrievals served
- Total number of blocks served
- Average retrieval success rate
- Average TTFB
- Average transfer speed

**Comment by willscott** [comment]
is this something @brossetti1 can help with?

* who has access to the validation bot database? - do you have access, @marinakosti  - if you don't, a first step for you is getting access so you can run any query that gets created.

**Comment by brossetti1** [comment]
I have access to the database, I can add your user @marinakosti and help with the query once I get some of these prs merged - can you pass me your aws user on slack?

**Comment by jacobheun** [comment]
Closing this as it doesn't belong in the boost repo. Internal requests like this may be best handled at https://github.com/protocol/bedrock
