### ISSUE TITLE
docker devnet -- M1 compatibility and lotus update

### ISSUE THREAD

**Issue by LaurenSpiegel** [filecoin-project/boost#1084]
@airenas and @nonsense , would appreciate your input on these:

1) Lotus's dockerfile has been updated. Is there anything we should do in our setup? See  https://github.com/filecoin-project/lotus/pull/9625

2) @hannahhoward was unable to get the docker to build on an M1 mac with either the make docker/all command or the make docker/all ffi_from_source=1

Error:
unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-6421404651457840.rlib" "-Wl,-Bdynamic" "-lhwloc" "-lOpenCL" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/usr/local/rustup/toolchains/nightly-2022-05-09-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/opt/filecoin/extern/filecoin-ffi/rust/target/debug/deps/filcrypto-bdd4d906adefd5ff" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
#12 445.0   = note: collect2: fatal error: ld terminated with signal 9 [Killed]
#12 445.0           compilation terminated.
#12 445.0           
#12 445.0 
#12 445.3 error: could not compile `filcrypto` due to previous error
#12 445.7 + rm -f /tmp/tmp.wqNf8h8H48
#12 445.7 make[1]: *** [Makefile:14: .install-filcrypto] Error 101
#12 445.8 make[1]: Leaving directory '/opt/filecoin/extern/filecoin-ffi'
#12 445.8 make: *** [Makefile:41: build/.filecoin-install] Error 2

**Comment by jacobheun** [comment]
Yeah we need to update our setup, Lotus has consolidated some images so we need to update for that.

**Comment by jacobheun** [comment]
Looks like there's an issue with M1s in the latest lotus setup https://github.com/filecoin-project/lotus/issues/9821

**Comment by airenas** [comment]
> 2\. @hannahhoward was unable to get the docker to build on an M1 mac with either the make docker/all command or the make docker/all ffi_from_source=1

It does not relate to lotus docker updates, as the Lotus Team has kept the old file we are using. From the info you pasted I see that the part of building filecoin-fii is failing with a termination error. I would guess that docker process on the @hannahhoward's machine runs out of memory, could it be?

**Comment by jacobheun** [comment]
@airenas if you have bandwidth to try updating to the new lotus image that would be great. I think we can do a followup as needed once lotus as support for arm in the new builds.

**Comment by airenas** [comment]
@LaurenSpiegel has asked me to confirm if devnet works on M1. I am confirming - it does. 
Chip: Apple M1, macOS: 12.5.1
Boost version: [5c2f301](https://github.com/filecoin-project/boost/tree/5c2f30104dca6a8fed0097790ed76ae88b94e463)
Build command: `make docker/all ffi_from_source=1`, by default it uses lotus *1.19.0-rc1* (tested also with *1.19.0*).
Started devnet, made a deal, and retrieved a file.

Regarding the error: I did the test. I limited RAM to 3GB, Swap to 512 Mb on Mac's *Docker Desktop/Settings/Resources/Advanced* tab and got exactly the same error as noted in https://github.com/filecoin-project/boost/issues/1084#issue-1535539001. So the reported error is related to the machine state/settings and not our docker configuration issue.

**Comment by LaurenSpiegel** [comment]
@airenas , thank you. Will you please make a PR to the readme with recommended resource settings a user should have in Docker Desktop/Settings/Resources/Advanced?

**Comment by airenas** [comment]
> Will you please make a PR to the readme with recommended resource settings a user should have in Docker Desktop/Settings/Resources/Advanced?
The default setup just worked fine for me. So I would say, we don't need a place for it in the readme. Don't you think that this issue is enough?

**Comment by LaurenSpiegel** [comment]
I think it would be helpful to add a one-liner. Will leave this ticket open for the lotus miner update.

**Comment by LaurenSpiegel** [comment]
@airenas, reminder on this. any issue with the lotus miner update?

**Comment by airenas** [comment]
Thanks for the hit. I tested the official lotus image from Dockerhub. The image with debug option works out of the box. I updated Makefile to use it by default: https://github.com/filecoin-project/boost/pull/1157.
