### ISSUE TITLE
Rename piece directory 

### ISSUE THREAD

**Issue by brendalee** [filecoin-project/boost#1086]
We were given feedback to rename the piece directory - this issue tracks the work to rename in the following places:
- code 
- documentation
- any discussion issues for SP engagement

New name: Local Index Directory

**Comment by jacobheun** [comment]
The rename landed on `Local Index Directory`. We talked about this sync last week and decided to focus on updated the user facing references first as the internal updates will be tedious and may take some time. We can make those updates in a followup as they won't affect users, but may be confusing for devs over time so we'd like to update naming everywhere.

**Comment by jacobheun** [comment]
All external references have been updated.
