### ISSUE TITLE
Support externally triggered PublishStorageDeals step

### ISSUE THREAD

**Issue by raulk** [filecoin-project/boost#1087]
## Context

The FVM enables the creation of alternative deals flows where certain key steps are triggered as on-chain logic. Take this flow as an example:

1. A DataDAO allows miners to register to participate as storage providers in the DAO.
2. When an SP registers, the DataDAO creates a “Participating Storage Provider” (PSP) contract via CREATE2 and returns its address. This is the gateway for the miner to participate in the DAO.
3. The SP adds the PSP as a control address to its Miner actor, thus allowing it to call PublishStorageDeals on its behalf.
4. When the DataDAO decides it wants to make a deal with the miner, it internally creates a DealProposal and notifies the PSP contract, which emits an event that the miner is watching (through some application).
5. When N number of deals have been made, the miner decides to commit to storing them, and sends a message to the PSP, which calls PSD on its behalf with the accumulated DealProposals (given that it’s a controlling address).
6. The miner now downloads the data through whatever mechanism the DataDAO designates (IPFS, Boost, HTTP, etc.)
7. The sealing process starts and progresses (Precommit with DealIDs, ProveCommit) until culmination (deal activation).

In that flow, the PSD message is not triggered by Boost, but rather sent by a smart contract on chain.

## Request

Have Boost detect and support externally-initiated PSD. For example, Boost could monitor/poll the market actor to identify new deals that the SP it is servicing has confirmed, and trigger the next step of the workflow.

**Comment by jacobheun** [comment]
@raulk do you have a link to a release milestone or similar we can add to this for understanding when this functionality is planned to launch? We don\t have bandwidth atm, but can evaluate this in our coming roadmap. Knowing the intended release timelines would be helpful.

**Comment by aashidham** [comment]
We would ideally like this included and shipped in time for FVM M2.1 launch in early March. 

This does not include buffer time of several weeks where we can have teams building on the platform to leverage this PSP capability, so the week of Feb 20 would be ideal (subject to change though). 

This integration is key to being able to make storage deals on chain, which is going to enable core use cases like dataDAOs and perpetual storage. Without this integration, key pieces of FVM functionality cannot be unlocked fully onchain.

**Comment by brendalee** [comment]
Thanks for letting us know about the work that's needed here. Unfortunately with the planning done for this quarter, with our team of 3 eng we have a full workload in Q1 - including some large items around tech debt to improve broader storage + retrieval stability and capabilities for storage providers. With the increase in retrievals to SPs, this stability work is quite important. Completing this work by the week by late Feb/early March will be difficult.

**Comment by aashidham** [comment]
We have published an FRC draft here that will require some key boost integration with SPs, do you mind having a look and leaving your comments? https://github.com/filecoin-project/FIPs/discussions/604

**Comment by jennijuju** [comment]
@aashidham AFAIK - the PSP solution, allowing a smart contract to be miners control address and publish storage deals,  is not the one we are prioritizing. If it is, could you please point me to the related doc/thread?

**Comment by aashidham** [comment]
You're right that PSP will not be prioritized.

For mainnet we need to work with Boost to build the end to end experience for Boost SPs. 

@raulk is there value in keeping this thread open? There should be no Boost dependence for Hyperspace. 

This is clarified in the work plan here: https://docs.google.com/document/d/11mr9Km3XWF-Pi86i3pPi4ul5Hew_yeuWcVt25ihpFK0/edit#bookmark=id.44hoxeirn232

**Comment by aashidham** [comment]
Feel free to close this thread for now, we will reopen if necessary.

**Comment by nonsense** [comment]
I know this is closed but just for reference on the flow of how deals work today --

5 and 6 are exchanged -- SPs first download data and then call PSD, and not the other way around. An SP can't be committing to a deal without having first received data and verified it against the deal parameters.

**Comment by aashidham** [comment]
@brendalee @nonsense My understanding is that SPs can call PSD but simply not submit a ProRep in the case where the PSD is published but the data is not transferred. If they do not submit a proof, then SPs face no penalty for backing out after the PSD is sent. Am I mistaken in my understanding?
