### ISSUE TITLE
Support Hyperspace net

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/boost#1104]
We kicked off a new dev focused hyperspace net last week, this network is aimed to be perpetual. Many developers have started to build data use cases on hyperspace as we kicked off space warp hackathon on Jan 20th, and we expect more developers coming buidl onwards. While currently SPs are fine running lotus market for deal makings, however, given boost is the go to market implementation  and have more advance features + better performance  than lotus market, I think it would be valuable for community to be able to run boost on hyperspace as well.

It would be amazing if we can add the support ASAP for space warp hackathon participants - you can find the hyperspace network files here https://github.com/filecoin-project/lotus/tree/ntwk/hyperspace/build.

**Comment by willscott** [comment]
Are there changes in the market APIs exported by lotus in this version that would cause boost not to be compatible with it?

Changes to parameters shouldn't directly impact boost since it doesn't interact with the chain directly - Are there specific issues that nodes attempting to run boost rather than lotus market have run into?

**Comment by jennijuju** [comment]
> Are there changes in the market APIs exported by lotus in this version that would cause boost not to be compatible with it?
> 
> Changes to parameters shouldn't directly impact boost since it doesn't interact with the chain directly - Are there specific issues that nodes attempting to run boost rather than lotus market have run into?

No market api changes.
i don’t suspect any. Tho we need boost to add `make hyperspacenet` for boost node to connect to hyperspace net i believe

**Comment by jennijuju** [comment]
(@raulk is taking a pass on this I think)

**Comment by brendalee** [comment]
thanks @jennijuju - if it's not done yet, @LexLuthr will be back in mid Feb. He could help with supporting this request.

**Comment by jennijuju** [comment]
> thanks @jennijuju - if it's not done yet, @LexLuthr will be back in mid Feb. He could help with supporting this request.

Thank you for the update !

**Comment by LexLuthr** [comment]
@jennijuju Can we merge master into the ntwk/hyperspace as dependency mismatch is failing the build. Boost is using the newer version with required code changes and so is lotus master it seems. As this branch fall far behind, it would be harder to keep boost releases in sync. We should do periodic merges from main to the branch to avoid these problems. 

```
# github.com/filecoin-project/lotus/node/modules
../../../../go/pkg/mod/github.com/filecoin-project/lotus@v1.20.0-hyperspace-nv20-event-migration-speedup/node/modules/storageminer.go:689:3: cannot use indexer (variable of type "github.com/filecoin-project/index-provider".Interface) as type "github.com/ipni/index-provider".Interface in argument to storageimpl.NewProvider:
	"github.com/filecoin-project/index-provider".Interface does not implement "github.com/ipni/index-provider".Interface (wrong type for GetAdv method)
		have GetAdv(context.Context, cid.Cid) (*"github.com/filecoin-project/storetheindex/api/v0/ingest/schema".Advertisement, error)
		want GetAdv(context.Context, cid.Cid) (*"github.com/ipni/storetheindex/api/v0/ingest/schema".Advertisement, error)
```

**Comment by jacobheun** [comment]
This is available in the https://github.com/filecoin-project/boost/tree/ntwk/hyperspace branch.
