### ISSUE TITLE
Boost support for FVM deals

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#1156]
## Summary
[FIP Discussion 604](https://github.com/filecoin-project/FIPs/discussions/604) proposes introducing the ability for storage deal proposal generation to occur on the FVM. In order for SP's to run these deals through existing flows there will be required updates to Lotus (currently in progress) as well as Boost.

## Proposal
* Boost SP's will have the ability to configure Boost to accept inbound FVM deals `AcceptContractDeals: true`.
  * Optionally: providing FVM support exists, SP's would be able to limit to specific topics.
* When `AcceptContractDeals` is true, Boost will subscribe to `DealProposalCreated` events via the Lotus RPC api
* When valid events are detected (TODO - define validity), Boost will perform an eth_call via the Lotus RPC api to `getDealProposal`
  * If the proposal includes an http hosted car file, Boost will automatically initiate the retrieve and progress the deal
  * If the proposal includes an unknown transport type, normal offline deal flows would be required by the SP
* Once data is downloaded, Boost will trigger a Propose Storage Deal (same flow as today) with `client` as per the params of the deal proposal
* The Storage Market Actor then calls the `client` address and authorizes the deal. ([Lotus Web3 Client Contract](https://github.com/lotus-web3/client-contract) contains source code on how deals proposed on the FVM would actually be authorized by client contracts, instead of authorized through client signature verification as it works today.)
* Once the deal has been authorized (i.e. PSD message is successful on-chain), Boost will pass the data to Lotus for sealing (existing flows apply)

### DataDAO with HTTP hosted CARs for allowlisted SP's
1. DataDAO deploys a limited contract per https://github.com/filecoin-project/FIPs/discussions/604
1. DataDAO owner/author/actor calls `makeDealProposal` for their `datadao01.car` file hosted at `https://my.data.dao/datadao01.car` triggering a new deal event
1. Lotus sees the event which is passed off to the subscribed Boost instance
1. Boost sees the event and fetches the deal proposal from Lotus via eth_call
1. Boost performs an http fetch of `https://my.data.dao/datadao01.car`
1. Once downloaded, Boost starts the deal flow, causing authorization with the client to trigger per the above proposal via a PSD message on-chain.
1. On acceptance, the deal is passed to sealing.

### DataDAO with custom data transfer (IPFS/Portable Drives/etc) for allowlisted SP's
1. DataDAO deploys a limited contract per https://github.com/filecoin-project/FIPs/discussions/604
1. DataDAO owner/author/actor calls `makeDealProposal` with metadata clarifying how the SP can manually retrieve the data (if not already negotiated as part of a partnership)
1. Lotus sees the event which is passed off to the subscribed Boost instance
1. Boost sees the event and fetches the deal proposal from Lotus via eth_call
1. Boost, not recognizing the transport, marks the deal for `Awaiting Offline Transfer`
1. The SP fetches (manually or scripted) the offline data and triggers the next phase of the deal with Boost
1. Boost continues the deal flow, causing authorization with the client to trigger per the above proposal via a PSD message on-chain.
1. On acceptance, the deal is passed to sealing.

## Outstanding questions
* How is "racing" / front-running of SP's handled? If 2 SP's submit proposals and only 1 is accepted, we need to clarify this flow.
* How are SP's filtering events for just the contract owners they accept? How are they managing that list?
* The flow above assumes that a `location reference` is part of the Deal Proposal struct and we get it via the eth_call read-only. Is this where the location reference will be stored?

## Dependencies
* https://github.com/filecoin-project/FIPs/discussions/604 will need to include a location/transport reference for http retrieval to work. Ideally there should be some metadata to clarify how offline deals can be performed, but this may be negotiated offline by SP's and contract author partnerships.
* Functional `eth_` namespace on Lotus (namely `eth_call` and `eth_subscribe`) so that Boost can receive events and do read-only JSON RPC calls to fetch VM state as described above.
* We will need to setup a devnet environment to properly test the end to end flow here, and will need support for the FVM and lotus functionality to be in place (even if in branches).

## References
* [FIP Discussion 604](https://github.com/filecoin-project/FIPs/discussions/604)

**Comment by jennijuju** [comment]
> AcceptFVMDeals

quick bike shedding, I feel like `AcceptContractDeals` is a better name - in the end of the day fvm is just a VM that executes the messages, it doesn't distribute deals or per se.

**Comment by jennijuju** [comment]
> Boost will subscribe to DealProposalCreated events via the Lotus RPC API

As in ALL contracts that emit this event? Will SP get to chose which ones they'd like to subscribe (deal with?)


> Boost sees the event and fetches the deal proposal from Lotus via eth_call

So this assumes we stores whole deal proposal in the contract and SP will poll. Curious why we didn't consider to have the event has enough deal proposal info and boost can just get them from event, without pulling from the contract again? (curious about the constraints, gas usage and contract statescalability)

**Comment by jennijuju** [comment]
> Boost will trigger a Propose Storage Deal with client as per the params of the deal proposal

this is just sending PSD correct?

**Comment by jennijuju** [comment]
(Also note, this flow should work for data contracts that do but are not limited to DataDAO, simple deal client, data bounty, DataDao, perpetual storage, storage automation and so on.

**Comment by jennijuju** [comment]
> How is "racing" / front-running of SP's handled? If 2 SP's submit proposals and only 1 is accepted, we need to clarify this flow.

Good q and i would argue different data platform will have different mechanism - we did some research on this problem here https://www.notion.so/pl-strflt/FilFil-PeSto-and-Filecoin-Archive-47ba9313222c4d86ac0539147b781a6c?p=9b63d39ac97240ce843b24d6b0ec994c&pm=s

**Comment by jennijuju** [comment]
> The flow above assumes that a location reference is part of the Deal Proposal struct and we get it via the eth_call read-only. Is this where the location reference will be stored?

AFAIK the location ref can also be a part of the event - which likely means you don't need eth_call to get it either? Event are  then stored as  a part of the message receipts.

It seems to me that we should prioritize on deciding if we should take the event only approach OR a event+getter approach.

**Comment by LaurenSpiegel** [comment]
> 

At the risk of further bike shedding, should we default to listening for these events?  So, the configuration would actually be something like `IgnoreContractEvents` and if the SP wants to ignore they set this to true.

**Comment by jacobheun** [comment]
> quick bike shedding, I feel like AcceptContractDeals is a better name

Fine by me, not strongly held to the names. `AcceptFVMDeals` changed to `AcceptContractDeals`.

> As in ALL contracts that emit this event? Will SP get to chose which ones they'd like to subscribe (deal with?)

This is listed as an outstanding question. It's still not clear what that stream will look like, how SP's can subscribe to certain topics, etc. Ideally, I imagine SP's are going to want to heavily filter this to relevant topics, but there needs to be some product work done to figure out what those end to end flows look like.

> So this assumes we stores whole deal proposal in the contract and SP will poll. Curious why we didn't consider to have the event has enough deal proposal info and boost can just get them from event, without pulling from the contract again?

@nonsense may have thoughts on this? I'm not currently clear on the benefits/drawbacks of having the events hold all information, versus them being lighter and requiring a fetch aside from a lighter resource load to hold an event cache, but this is likely pretty small.

> this is just sending PSD correct?

Yeah standard PSD flows that exist today. Clarified in the description.

> (Also note, this flow should work for data contracts that do but are not limited to DataDAO, simple deal client, data bounty, DataDao, perpetual storage, storage automation and so on.

100%. Current scenarios listed are just ones that I've heard numerous times, so using them as base use cases.

> Good q and i would argue different data platform will have different mechanism 

The main question we have here is that response is consistent. The error messaging can vary based on the mechanism, but being clear about what a denial (racing or otherwise) would be helpful, especially considering SP's will have had to download the data before getting to this step. If there's a high fail rate here, there is little incentive for them to burn resources fetching the data.

> It seems to me that we should prioritize on deciding if we should take the event only approach OR a event+getter approach.

Agreed, we need to clarify the flow here. I'd love to get the interface calls between Lotus and Boost clarified, as this should be helpful in sussing out any potential missing bits.

> At the risk of further bike shedding, should we default to listening for these events? So, the configuration would actually be something like IgnoreContractEvents and if the SP wants to ignore they set this to true.

@LaurenSpiegel for that to happen I think we really need to answer the event filtering problem here. If it's default, that means SP's would get ALL events. If contract deals are restricted to certain SP's, negotiated out of band, they could be getting events they can't make deals for. I'd really like to see clarity on what the end event stream looks like for SP's before defaulting to true out of the gate. We're also going to need to sort out what event retention looks like for SP's as well, which could quickly balloon and become unmanageable if there is a flood of these potential deals they need to sift through.

**Comment by nonsense** [comment]
> @nonsense may have thoughts on this? I'm not currently clear on the benefits/drawbacks of having the events hold all information, versus them being lighter and requiring a fetch aside from a lighter resource load to hold an event cache, but this is likely pretty small.

This is a rather small change on Boost side, depending how it is decided to be implemented. It is a standards question, and something to be discussed at https://github.com/filecoin-project/FIPs/discussions/604

At first thought, I'd probably opt for an event that contains all information rather than keep the deal proposal data in state, but this is not what the discussion is currently proposing. Not sure if events have any limitation with respect to the size of the data that they could contain.

**Comment by jennijuju** [comment]
> Good q and i would argue different data platform will have different mechanism
>> The main question we have here is that response is consistent.

Seems like we are getting at something like:
- in[ `policyOk`](https://github.com/lotus-web3/client-contract/blob/31866ab058c08572fc6b87ae57976411fc3229de/src/DealClient.sol#L37) (method name to be bikesheded later lolol) - we shall emit an event like `PSDFailed` with some predefined error codes for main scenarios like: enough copy made

@zenground0 do you have any thoughts here?

**Comment by aashidham** [comment]
The hope with the current interface is to enable a wide variety of data dao use cases, which is why we have an event emitted with an id that has to be called by Boost. 

When an SP then calls `getDealProposal` , the client contract can then determine whether or not it makes sense to actually send over the deal proposal. This denial can be based on the number of SPs that might have already replied, the funds left in the contract, whether or not a vote passed and if another deal is expiring. All kinds of parameters can be coded to make `getDealProposal` return nothing depending on the current state of the contract. 

This is why we want multiple SPs to respond if they are a fit for the emitted event. Only a subset may be picked with a non-null return.

---

On another note, the question about what we should contain in the event is a key one. [See the key / open question in the proposal:](https://github.com/filecoin-project/FIPs/discussions/604)

> Right now, the DealProposalCreate event only contains an id. Is there more worth adding to the event signature? Keep in mind each additional topic needs to be 32 bytes at most. Having more descriptive events may allows SPs to filter events so that they can more selectively respond. Some ideas:
> (a) MinerID: to let a participating SP filter by its own ID. This is valuable for clients to emit events that are specifically for a constrained set of SPs.
> (b) string: a human readable string (of at most 32 characters) that describes the storage deal. Can be optionally filled by clients. Relevant strings can then be filtered by SPs. May lead to confusion / splintered topics since this is a freeform field. May need further standardization if included.
> (c) pieceSize: the size of the deal. SPs can then filter by the size of deals they want to store.
> (d) verifiedDeal: whether or not the deal is verified. SPs may not want to entertain unverified deals.

Would love the input of the Boost team on this question based on known Boost behavior. How do Boost SPs evaluate deals currently? 

I am not currently a fan of including everything in the event, since that means a lot more PSDs will be submitted than the client can afford or meant to submit. The hope is that the emit (push) and the getter (pull) system allows for the PSD payload to be given only to the SPs that the client has approved to receive the payload. 

Ideally SPs can filter the deal proposal based on the event parameters (see open question) and the client can filter out SPs based on their selective response to `getDealProposal`.

**Comment by aashidham** [comment]
The event log is inherently gossipy. Look at the Transfer event for an ERC20. This is an event that gets emitted across the chain for all clients to see even though it only affects the sender's and receiver's balances. This is the case for most events.

Also note -- you can specify a set of SPs but the client might be more lenient. If an enterprising SP responded to a deal proposal that it was included in, the client might approve that request depending on its implementation of the interface. 

However you are right that there might be better fields to include in the event parameters than a miner ID. Others are also listed as options.
