### ISSUE TITLE
Support golang v1.20.x

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#1168]
Go recently release version 1.20. We have reports from users that Boost does not compile on the latest version.

With this we should update our minimum version to match golangs version support policy (which would be 1.19 and 1.20)

relates to https://github.com/filecoin-project/lotus/issues/10199

**Comment by jacobheun** [comment]
There is likely to be a dependency update trickle required to get this to land (such as propagating QUIC updates from libp2p up the stack), so this will likely take multiple days and coordination to get fully integrated.

**Comment by marten-seemann** [comment]
As this repo depends on lotus, https://github.com/filecoin-project/lotus/issues/10199 needs to be resolved first.

**Comment by LexLuthr** [comment]
https://boost.filecoin.io/getting-started#boost-and-lotus-compatibility-matrix closing as complete.
