### ISSUE TITLE
Expired deals are not retrievable

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#1200]
## Problem
When a sector expires, even if an unsealed copy exists and the sector has not been removed the deal cannot be retrieved. The following log is for a legacy deal that recently expired, where the data is still available locally:
```
2023-02-08T22:41:28.078+1100    ERROR   retrieval       impl/provider.go:434    Retrieval query: GetAsk: GetRetrievalPricingInput: failed to fetch storage deal state: 1 error occurred:
        * deal 2421142 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed
```

The issue is that a chain lookup is currently happening to get the deal info. As the deal has expired, this chain lookup fails, so despite having the data locally the retrieval fails. Ideally, this data should still be available and retrieval should not care about chain state (see https://github.com/filecoin-project/boost/issues/1002#issuecomment-1427905432 on related indexing discussions).

For Storage Deals made via the 1.2+ protocol, this should be fairly straightforward to ensure works, as we have all the data we need in our local store. For legacy deals (<= 1.1.x), the fix is likely to be more difficult and may require some migrations, as we need to avoid a lookup on chain.

## References
- relates to https://github.com/filecoin-project/boost/issues/1199
- Reported issue via Slack - https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1675856817927119

**Comment by jacobheun** [comment]
In order to properly resolve this without iterating through every legacy deal for every retrieval query, we're going to need to do some mapping or readonly table that gets us from a PieceCid to the local deal data.

* All legacy deals currently have their underlying data cbor encoded while stored, with no way to lookup the data by PieceCID without crawling all deals and unmarshaling the cbor.

**Option 1**: Duplicate all legacy deals data into a read only database. This would make it easier to deprecate/remove the legacy deal FSM logic in the future, but is more effort to get this working well.

**Option 2**: Store just a mapping of the PieceCID to FSM key in a new table. This would involve minimal changes while allowing us to use a DB to find the right FSM we need to fetch for the deal.

**Comment by LexLuthr** [comment]
Closing this as we are sending a remove to Indexer for expired deals. This should further improve as legacy deals are being deprecated soon.
