### ISSUE TITLE
Proposal format received by the deal filter is missing some key values

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1212]
The Proposal format received by the deal filter for offline incorrectly says IsOffline is false

"DealType": "storage",
    "DealUUID": "2d433aa5-d55c-46ba-bc90-c17357867b1a",
    "FormatVersion": "2.0.0",
    "IsOffline": false,
    
    
This is because we are not exposing the below 3 values when supplying the Deal details to the filter. These values can be further helpful to filter out deals with specific conditions.

 "IsOffline"
 "RemoveUnsealedCopy"
 "SkipIPNIAnnounce"

**Comment by LexLuthr** [comment]
CC: @s0nik42

**Comment by s0nik42** [comment]
Will you also set "Transfer->Type" to manual  like before instead of empty ? 
    "Transfer": {
        "ClientID": "",
        "Params": null,
        "Size": 18999266430,
        "Type": ""
    }

**Comment by LexLuthr** [comment]
@s0nik42 We were not setting it to manual in the first place. That is what caused the problem in https://github.com/filecoin-project/boost/issues/1208
If you check the client, we don't set any Transfer.Type for offline deals. Are you aware of any clients who are setting this value to manual explicitly for Boost deals?
In offline deals, Transfer.Type should not have any impact. We should avoid checking that for offline deals. I don't find it to be a reliable source as anyone can use any string when proposing a deal.

**Comment by s0nik42** [comment]
This value was set initially, I don't know if its lotus but this is how our implementation is working for now. I can find some examples if you need it let me know

**Comment by s0nik42** [comment]
so you mean boost is doing a passthrough on that field ?

**Comment by LexLuthr** [comment]
Yes. Boost never set that field from it's inception.

https://github.com/filecoin-project/boost/pull/383/files#diff-adad458ea2e7b55ef03d056002f8f398b27bf4dec1f113a6ccea392025599dab

Thus my comment saying that "I don't find it to be a reliable source as anyone can use any string when proposing a deal"

We should not be checking transfer types when dealing with offline deals.

**Comment by s0nik42** [comment]
Is it the same for Online deals ? you don't use that field ?

**Comment by LexLuthr** [comment]
In online deals transfer type is used. Right now it is "http"

**Comment by s0nik42** [comment]
BAsed on what we see in today's logs (cidgravity). We usually receive : 

Transfer -> Type with value http or libp2p (boost)
TransferType with value "manual". (probably legacy) (90% of the deals we analyzed on 02/23/23) 

I really need to understand how we should read interpret all of this. SPs are accepting and rejecting deals based on the transfer type.

**Comment by LexLuthr** [comment]
You will still see "manual" for legacy deals. Boost is not making any changes to that code path.
Online deals will have libp2p and http. In fact, we haven't made any changes to transfer type till now since Boost's release.

I don't have full insight into CIDGravity filters. But are legacy filters and Boost filters same?

**Comment by s0nik42** [comment]
yes
We support multiple proposal format (legacy / boost 2.0.0 / boost 2.1.0) 
then we standerdized them to an internal format. The application is design to support multiple format as input. 
For each format we just need to understand the expect json format and the expected values.

**Comment by LexLuthr** [comment]
We have updated the JSON here. It will be a part of all new releases. Everything else is same as before, I just added 3 more params to allow greater control over deal acceptance. 

legacy/ Boost 2.0.0 / Boost 2.1.0 will stay the same as before. 
As to the your original comment, I want to reiterate, we were never setting Trasnfer.Type for Boost offline deals. It was always empty. 

I hope this make all the upcoming changes clear and you can update the filter scripts accordingly.

**Comment by jacobheun** [comment]
Fixed by https://github.com/filecoin-project/boost/pull/1213, feel free to reopen if needed.
