### ISSUE TITLE
Add a start-epoch-diff option 

### ISSUE THREAD

**Issue by anjor** [filecoin-project/boost#1224]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [X] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
v1.5.2
```

### Describe the Bug

Today if a client wants to specify a longer duration for the SPs, the client is required to figure out the current head and add the number of epochs they want. This requires an extra call from the client either to a lotus node or a boost node.

Instead, the client should be able to provide a `start-epoch-diff` which specifies the amount of time starting from the current head that the client is ok with waiting before the deal is published on chain. 

Other considerations:

- This needs to be a separate flag instead of reworking `start-epoch` for backwards compatibility
- `start-epoch` should supersede this setting, again for backwards compatibility.

### Logging Information

```text
n/a
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by anjor** [comment]
Relevant slack discussions: 
https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1677258094745299
https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1662569258162799

**Comment by nonsense** [comment]
Added `start-epoch-head-offset` flag. Thanks @anjor
