### ISSUE TITLE
Write tests for Boost SM

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#125]
- [x] Test deal resumption after process restart for each of the checkpoints
- [x] Test deal resumption after context cancellation for each of the checkpoints.
- [ ] Test deal data-transfer resumption after some data has already been downloaded after a process restart. 
- [x] Test deal data-transfer resumption after some data has already been downloaded after a process restart by context cancellation. 
- [x] Test deal data-transfer resumption because of multiple disconnects.
- [x] Test user cancellation of a deal for each of the checkpoints.
- [ ] Deal validation unit tests -> copy over from existing Markets.
- [x] Integration tests for happy path for multiple concurrent deals.
- [x] Integration tests to test fund manager and storage manager state for multiple concurrent deals.
- [x] Unit tests for the deal handler.
- [x] Test non-recoverable deal failure after each of the checkpoints and ensure failure is handled correctly and state is cleaned-up correctly.
- [x] Unit Tests for the Provider event loop and code flow upto deal execution.

**Comment by aarshkshah1992** [comment]
Tracking issue for the one remaining testcase at https://github.com/filecoin-project/boost/issues/216 as it needs some refactoring.
