### ISSUE TITLE
boost deal --wallet ingored

### ISSUE THREAD

**Issue by f8-fil-ops** [filecoin-project/boost#1334]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [X] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boost version 1.6.1+git.4931e18
```

### Describe the Bug

`boost deal` ignores the `--wallet` flag and defaults to the default address 

### Logging Information

```text
provided if needed
```

### Repo Steps

- make a deal and set `--wallet` different from the default address
- see what the client address is in the proposal

**Comment by LexLuthr** [comment]
Is you wallet added to the boost client?

**Comment by LexLuthr** [comment]
Are you sure there is no mistake in the command? I just ran a test and it seems to be working.

```
Address                                                                                 Balance                    Market(Avail)  Market(Locked)  Nonce  Default  DataCap  
t17oxqopbqq4qgtmc4zo7psaxhkf7kbysryvycuwa                                               39.999999903866199977 FIL  10 FIL         0 FIL           1               X        
t3vkewzxvqooc3gk3dxjq3nvpdaxajjbvnjjxvxuthoskft3mxd4giadss7e2ps3ptqoiv5g3hh4qtsbgntbfa  8.999996094589381726 FIL   1 FIL          0 FIL           1      X        X        
```

```
root@7074e3dab6dd:/app/sample# boost deal --verified=false --provider=t01000 --http-url=http://demo-http-server/sample.car --commp=baga6ea4seaqpfonfro6j3gcw4uxkxbivlqn2fghx5dpulc6sbi5noz7bcvzmuiq --car-size=1175 --piece-size=2048 --payload-cid=bafk2bzacec3jst4tkh424chatp273o6rxvipfg54kphd56gaxobpcdtr2sgco --storage-price 20000000000 --wallet t17oxqopbqq4qgtmc4zo7psaxhkf7kbysryvycuwa
sent deal proposal
  deal uuid: 928ed621-6831-4d51-a301-afdd48b28e1d
  storage provider: t01000
  client wallet: t17oxqopbqq4qgtmc4zo7psaxhkf7kbysryvycuwa
  payload cid: bafk2bzacec3jst4tkh424chatp273o6rxvipfg54kphd56gaxobpcdtr2sgco
  url: http://demo-http-server/sample.car
  commp: baga6ea4seaqpfonfro6j3gcw4uxkxbivlqn2fghx5dpulc6sbi5noz7bcvzmuiq
  start epoch: 5832
  end epoch: 524232
  provider collateral: 0
```
