### ISSUE TITLE
Remove support for legacy (< /fil/storage/mk/1.2.0) Propose Storage Deal Protocol deals

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#1408]
## Summary
This issue is for tracking removal of support for making new, legacy deals in Boost. Going forward `Propose Storage Deal Protocol` deals made on protocol `/fil/storage/mk/1.2.0` or later will only be supported. This change is being made to fully deprecate and remove, inefficient, legacy code paths.

### Protocol support being dropped
The following protocols will have their support removed with this change:
* `/fil/storage/mk/1.0.1`
* `/fil/storage/mk/1.1.0`
* `/fil/storage/mk/1.1.1`

## Requirements
* The above mentioned protocols will no longer be supported for new deals
* Existing legacy deals must still be accessible for Storage Providers via the UI/CLI for managing them
* Existing legacy deals must still be retrievable by clients

## Implementation Notes
In order to fully remove the legacy code paths, we may want to consider migrating old deals from their current, cbor encoded storage into the Boost database. This would make it easier and more efficient to reference old deals. This _may_ not be entirely necessary if we choose to drop their references after expiry, but this does run the risk of extending the life of the old code, as well as SP's eventually losing any visibility into these old deals.

**Comment by GuoChangJinYa** [comment]
Hi, I came across this while Posting storage transactions: Provider message: deal proposals made over the legacy /fil/storage/mk/1.1.1 protocol are deprecated - please use the / / fil/storage/mk 1.2.1 deal proposal protocol.

How can I update this agreement

**Comment by LexLuthr** [comment]
@GuoChangJinYa You need to use newer protocol if you are making deal with Boost SPs. I would suggest checking the protocols used by your client and update it.

**Comment by tmkhoa-dev** [comment]
Thank @LexLuthr , I'm facing with this issue also. I'm running local lite-node on MacOS. When I run `lotus client deal`, I'm stucking on that error

**Comment by vinkent420** [comment]
> @GuoChangJinYa You need to use newer protocol if you are making deal with Boost SPs. I would suggest checking the protocols used by your client and update it.

I don't know how to update it, can you help to provide a hint, please!

**Comment by LexLuthr** [comment]
@tmkhoa-dev @vinkent420 Boost does not support Lotus client anymore. You will need use boost client.
https://boost.filecoin.io/storing-data-on-filecoin

I am closing this issue as latest main does not have any legacy code base.
