### ISSUE TITLE
unable start boostd

### ISSUE THREAD

**Issue by lbj2004032** [filecoin-project/boost#1411]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.7.2+git.4214dd7
```

### Describe the Bug

unable start boostd

### Logging Information

```text
2023-05-03T08:38:01.765+0800    INFO    unsmgr  indexprovider/unsealedstatemanager.go:52        starting unsealed state manager running on interval 0s
panic: non-positive interval for NewTicker

goroutine 642438 [running]:
time.NewTicker(0x0?)
        /usr/local/go/src/time/tick.go:24 +0x10f
github.com/filecoin-project/boost/indexprovider.(*UnsealedStateManager).Run(0xc012ec4aa0, {0x673c320, 0xc010728740})
        /home/lotus/boost/indexprovider/unsealedstatemanager.go:53 +0xdd
created by github.com/filecoin-project/boost/indexprovider.(*Wrapper).Start
        /home/lotus/boost/indexprovider/wrapper.go:313 +0x1d9
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by LexLuthr** [comment]
Can you please update StorageListRefreshDuration = "1h" in boost config and restart. Check if that works.

**Comment by lbj2004032** [comment]
> StorageListRefreshDuration

Thanks, it works now.
