### ISSUE TITLE
storage deals stuck at Staged status

### ISSUE THREAD

**Issue by lbj2004032** [filecoin-project/boost#1412]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.6.1+git.4931e18.dirty
```

### Describe the Bug

storage deals stuck at Staged status
How resolve StorageDealError: deal rejected: invalid deal end epoch 4399960: cannot be more than 1555200 past current epoch 2824600

### Logging Information

```text
$ lotus-miner storage-deals list
ERROR: fatal error calling 'Filecoin.MarketListIncompleteDeals': panic in rpc method 'Filecoin.MarketListIncompleteDeals': runtime error: invalid memory address or nil pointer dereference
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...
<img width="942" alt="搜狗截图20230503102444" src="https://user-images.githubusercontent.com/101935091/235822234-ea70c65a-ec46-4aef-b66a-cccbdcb2405a.png">
<img width="760" alt="搜狗截图20230503102510" src="https://user-images.githubusercontent.com/101935091/235822240-ced0643c-d15b-404e-baf6-60c7d588b68f.png">

**Comment by LexLuthr** [comment]
A couple of things to note here. 
1. Boost version is dirty. Have you done a clean build?
2. Filecoin.MarketListIncompleteDeals is not an error. Please do not use lotus-miner commands for anything related to market.
3. You are running a an old version of Boost. I would recommend upgrading to latest stable version as per the [compatibility matrix](https://boost.filecoin.io/getting-started#boost-and-lotus-compatibility-matrix). 
4. The proposed deal ends on 2024-10-30 which is more than 1.5 years and thus is being rejected by the filter. Please adjust the deal's end and start epochs.

**Comment by LexLuthr** [comment]
Please provide the logs and deal details for one of the staged deals from the UI. You can copy all this information with clipboard button on the side of deal UUID on deal detail page.

**Comment by lbj2004032** [comment]
> Please provide the logs and deal details for one of the staged deals from the UI. You can copy all this information with clipboard button on the side of deal UUID on deal detail page.

![image](https://user-images.githubusercontent.com/101935091/235932294-f976f3c0-fa26-4213-a053-8564f7d78030.png)

**Comment by lbj2004032** [comment]
> A couple of things to note here.
> 
> 1. Boost version is dirty. Have you done a clean build?
> 2. Filecoin.MarketListIncompleteDeals is not an error. Please do not use lotus-miner commands for anything related to market.
> 3. You are running a an old version of Boost. I would recommend upgrading to latest stable version as per the [compatibility matrix](https://boost.filecoin.io/getting-started#boost-and-lotus-compatibility-matrix).
> 4. The proposed deal ends on 2024-10-30 which is more than 1.5 years and thus is being rejected by the filter. Please adjust the deal's end and start epochs.

What is the alternative command for lotus miner storage deals selection reject -- online

**Comment by lbj2004032** [comment]
> A couple of things to note here.
> 
> 1. Boost version is dirty. Have you done a clean build?
> 2. Filecoin.MarketListIncompleteDeals is not an error. Please do not use lotus-miner commands for anything related to market.
> 3. You are running a an old version of Boost. I would recommend upgrading to latest stable version as per the [compatibility matrix](https://boost.filecoin.io/getting-started#boost-and-lotus-compatibility-matrix).
> 4. The proposed deal ends on 2024-10-30 which is more than 1.5 years and thus is being rejected by the filter. Please adjust the deal's end and start epochs.


it's unable start boostd with version v1.7.2
023-05-03T21:54:19.579+0800    INFO    unsmgr  indexprovider/unsealedstatemanager.go:52        starting unsealed state manager running on interval 0s
panic: non-positive interval for NewTicker

goroutine 628738 [running]:
time.NewTicker(0x0?)
        /usr/local/go/src/time/tick.go:24 +0x10f
github.com/filecoin-project/boost/indexprovider.(*UnsealedStateManager).Run(0xc0176d76d0, {0x67637a0, 0xc0198cd9f0})
        /home/lotus/boost/indexprovider/unsealedstatemanager.go:53 +0xdd
created by github.com/filecoin-project/boost/indexprovider.(*Wrapper).Start
        /home/lotus/boost/indexprovider/wrapper.go:313 +0x1d9

**Comment by lbj2004032** [comment]
> Please provide the logs and deal details for one of the staged deals from the UI. You can copy all this information with clipboard button on the side of deal UUID on deal detail page.

![image](https://user-images.githubusercontent.com/101935091/235941406-2c3a2375-72f2-4211-8a0b-db7e7007721d.png)
![image](https://user-images.githubusercontent.com/101935091/235948782-65188884-645c-4daf-acde-6835e4ed3550.png)

Do these error deals mean a loss of 0.01 Fil

**Comment by lbj2004032** [comment]
> It doesn't look like anything is wrong with the deal. You need to check your miner logs to figure out why deal is not being added to a sector. If this is snap-deal, it could be that you don't have any Available sector with correct expiration. If this is normal sector sealing then your pipeline might be busy and cannot accommodate the new AP.
> 
> I am ignoring the 0.01 Fil question as it is already answered in #1414

How resolve it stuck at Staged status?
How resolve epoch issue,even I renew sectors , it stuck at Staged status also.

**Comment by LexLuthr** [comment]
There no alternative command. You can set the configuration in Boost config and restart boost for it to take effect.

Epoch Issue:
`How resolve StorageDealError: deal rejected: invalid deal end epoch 4399960: cannot be more than 1555200 past current epoch 2824600`
It is telling you what is wrong in the error. Your client is sending deal which are too long. Ask them to ensure (deal end epoch) - (deal start epoch) < 1555200

Staged Issue:
You need to provide miner logs for this. This is a lotus-miner issue not Boost.

**Comment by lbj2004032** [comment]
> r this. This is a lotus-miner issue not Boost.

ERROR   sectors pipeline/states_replica_update.go:275   handleReplicaUpdateWait: failed to wait for message: failed to load message: ipld: could not find bafy2bzacea6xdnodahbhvbtydhvqet4wkuehj6z6asydvihnsjgmvcm7p7wxm
