### ISSUE TITLE
Docs: fix typos in environment variables for `booster-http`

### ISSUE THREAD

**Issue by geoknee** [filecoin-project/boost#1467]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [X] Other

### Boost Version

```text
boost version 1.7.3-rc2+git.24a9bb3
boostd version 1.7.3-rc2+git.24a9bb3

(M2 Mac)
```

### Describe the Bug

Trying to serve retrievals using `booster-http`, with a `devnet` and `boostd` processes running (as described [here](Following the instructions here https://boost.filecoin.io/http-retrieval#local-setup.))

### Logging Information

```text
~/f/boost ❯❯❯ ./booster-http run --api-boost=$BOOST_API_INFO --api-fullnode=$FULLNODE_API_INFO --api-storage=$MINER_API_INFO
2023-05-25T16:38:46.811+0100	INFO	booster	booster-http/run.go:324	Using boost API at /rpc/v0
Error: getting boost API: creating full node service API: unknown url scheme ''
```

### Repo Steps

1. Follow the instructions here https://github.com/filecoin-project/boost#running-boost-for-development.
2. (Optional, I guess) including the "Make a deal with Boost" part. 
3. Follow the instructions here https://boost.filecoin.io/http-retrieval#local-setup
4. Observe error `Error: getting boost API: creating full node service API: unknown url scheme ''` when trying to launch `booster-http`.

There are some typos in the instructions for setting environment variables. There are missing backticks, and some copypaste errors mapping between `ENV_` prefixed and non-prefixed variables. 

Here's the fix:

```diff
export ENV_BOOST_API_INFO=`boostd auth api-info --perm=admin`
- export BOOST_API_INFO=echo $ENV_BOOST_API_INFO | awk '{split($0,a,"="); print a[2]}'
+ export BOOST_API_INFO=`echo $ENV_BOOST_API_INFO | awk '{split($0,a,"="); print a[2]}'`
```

```diff
export ENV_FULLNODE_API_INFO=`lotus auth api-info --perm=admin`
- export FULLNODE_API_INFO=echo $ENV_BOOST_API_INFO | awk '{split($0,a,"="); print a[2]}'
+ export FULLNODE_API_INFO=`echo $ENV_FULLNODE_API_INFO | awk '{split($0,a,"="); print a[2]}'`
```

```diff
export ENV_MINER_API_INFO=`lotus-miner auth api-info --perm=admin`
- export MINER_API_INFO=echo $ENV_BOOST_API_INFO | awk '{split($0,a,"="); print a[2]}'
+ export MINER_API_INFO=`echo $ENV_MINER_API_INFO | awk '{split($0,a,"="); print a[2]}'`
```

Doing this allowed me to complete following the instructions and successfully perform a retrieval.

**Comment by LexLuthr** [comment]
Fixed in https://github.com/filecoin-project/boost-docs/commit/ad5e98cfc30e817a737e716aff500bb012612527

**Comment by geoknee** [comment]
Thanks @LexLuthr -- not sure that fix quite nailed it though? Take a closer look at the variable names...

**Comment by LexLuthr** [comment]
@geoknee Good catch. I completely missed those Typos. Fixed now.

**Comment by oneforalone** [comment]
@LexLuthr Seems there still have typos in `FULLNODE_API_INFO` variables, missing an `O` in both v1 (https://boost.filecoin.io/v/v1/http-retrieval) and v2(https://boost.filecoin.io/retrieving-data-from-filecoin/http-retrieval) docs.
Should be:
```
export FULLNODE_API_INFO=`echo $ENV_FULLNODE_API_INFO | awk '{split($0,a,"="); print a[2]}'`
```
not
```
export FULLNODE_API_INFO=`echo $ENV_FULLNODE_API_INF | awk '{split($0,a,"="); print a[2]}'`
```
