### ISSUE TITLE
Investigate Graphsync retrievals lockup issues in Boost

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1474]
## Problem Description
As the number of retrievals started increasing with the Golden Retriever programs, we started observing a trend where Graphsync retrievals would stop serving requests after a few hours. There are no logs generated and no new events are emitted for incoming requests. Client does not see any progress on their side either.
A boostd restart fixes the problem temporarily but it comes back after few hours.
Please note that Bitswap and HTTP are not impacted and keep serving the data.

Grafana monitoring of graphsync requests
![image (6)](https://github.com/filecoin-project/boost/assets/88259624/23d032eb-4640-4084-8cbb-1266898e45cd)

At the same time Bitswap is unaffected
![image (7)](https://github.com/filecoin-project/boost/assets/88259624/f3416e90-56ca-4c06-9fa1-a484ca3ac47e)

Event monitoring in Boost UI
![image (4)](https://github.com/filecoin-project/boost/assets/88259624/c4845369-5590-46a0-ae4e-f1cd030febab)

### Goroutine leaks (incorrect termination handling in data-transfer/graphsync)
We found that Graphsync would start thousands of goroutines (and FSMs) and would not close them correctly after client terminates connection from their side. This was fixed by creating a small goroutine which terminates any Graphsync not updated in last 5 minutes on SP side. This helped very little and the problem persisted.

## New unpaid Graphsync retrieval server
A new unpaid server was written and all graphsync requests were redirected to it. This prevented the use of older code base for all unpaid retrievals. This reduced the calls to the older code base but did not had much impact on the original problem

## GO-Legs voucher moved to unpaid retrievals
The retrieval requests from IPNI were still going through older code base. We made changes so any go-legs voucher was intercepted by the new unpaid retrievals code base. No improvement.

## Move IPNI fetch to HTTP
In the latest RC, we implemented new functionality to allow publishing ads over HTTP. The network indexers could fetch the multihashes over HTTP instead of Graphsync. This was tested with 2 SPs but it did not help with the problem.

## Current Scenario
1. We are intercepting the Graphsync requests in such a way that 100% of them should be going to new unpaid implementation local to Boost. 
2. IPNI announcements are being published over HTTP
3. The Graphsync retrievals still lock up after few hours. We see some rejected or failed queries getting logged but no other information.

![image (5)](https://github.com/filecoin-project/boost/assets/88259624/61517f65-8298-4f1f-9d02-07679f7ab594)

4. Client does not see anything. Retrieval command just gets stuck in the beginning with no output.
5. The data transfer list is usually empty when retrievals are stuck.
6. The concurrent retrievals number is set to 100 for one of the SPs.

**Comment by dirkmc** [comment]
Fixed in release v1.7.3
