### ISSUE TITLE
Piece Doctor - all flagged pieces are marked as having no unsealed sector

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#1513]
When the piece doctor flags a piece, it always marks the piece as having no unsealed sector, even if the piece does in fact have an associated unsealed sector.
The reason is that the `hasUnsealedSector` flag is hard-coded to `false` in the [function that checks the piece state](https://github.com/filecoin-project/boost/blob/4ee35f16ff237a910e5ef1437bb7ee3cf28b4488/piecedirectory/doctor.go#L179).

**Comment by nonsense** [comment]
Fixed in https://github.com/filecoin-project/boost/pull/1515
