### ISSUE TITLE
Use DeserializedResponses parameter for gateway in booster-http

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#1531]
Depends on https://github.com/filecoin-project/boost/pull/1492

With the release of boxo v0.10.1, the config for the Boxo Gateway handler config now has variable called [`DeserializedResponses`](https://github.com/ipfs/boxo/blob/main/gateway/gateway.go#L36).
When set to `true`, flat files (i.e. deserialized responses) are served, as all CAR and RAW files.
When set to `false`, flat files are not served, and the only CAR + RAW files served are those that can verify trustlessly (all CAR requests and RAW requests that have no path).

booster-http contains a significant amount of code aimed at partially replicating this behavior. However the Boxo code is more correct. Boost filters by file type, which serves some requests that cannot be verified trustlessly (RAW blocks served at a path are not verifiable)

We should switch booster-http to take advantage of the new parameter:
- Remove `--serve-files`, `--serve-blocks` and `--serve-cars` parameters
- Add parameter `--serve-gateway=verifiable|all|none`
  - `verifiable`: set `DeserializedResponses` to `false`
  - `all`: set `DeserializedResponses` to `true`
  - `none`: do not enable gateway handler

**Comment by LexLuthr** [comment]
Resolved by Frisbii implementation.
