### ISSUE TITLE
Awaiting publish confirmation passes 10 epochs

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#1536]
An SP reports that the publish confirmation message passes 10 epochs, and sometimes goes up to 12 epochs:
![image](https://github.com/filecoin-project/boost/assets/169124/150c4531-5888-4b14-81c8-8de3ab481237)

**Comment by LexLuthr** [comment]
I think the reason for this might be because we start counting as soon as we send the message but the message might not land on chain for a epoch or two. Then we have 10 epoch confidence from there. So, total might exceed 10.

**Comment by LexLuthr** [comment]
@dirkmc Are we good to close this?

**Comment by LexLuthr** [comment]
This can be fixed by using the new mpool monitor to ensure we don't start counting till the message has left mpool.

**Comment by davidd8** [comment]
@LexLuthr has this been fixed and rolled out (i.e. mpool monitor)? If so, let's close this issue.

**Comment by LexLuthr** [comment]
Not yet. I will fix this today.
