### ISSUE TITLE
Boost MPOOL to show local boost/miner,  not network.

### ISSUE THREAD

**Issue by michieljmitchell** [filecoin-project/boost#1545]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [X] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Improvement Suggestion

Would be preffered to see the message pool summary for the local boost/miner instead of the entire networks mpool or both. Having the entire networks mpool size is usefull but it does not make sense to have to drill down for the local mpool.

![image](https://github.com/filecoin-project/boost/assets/97198835/b4f3fd83-789c-4721-a0eb-357682a5c3ff)

**Comment by LexLuthr** [comment]
This bug was already resolved in https://github.com/filecoin-project/boost/pull/1523 and further improvements to the page are planned in https://github.com/filecoin-project/boost/pull/1530

**Comment by dirkmc** [comment]
Thanks for the bug report
Closing as fixed by #1523
