### ISSUE TITLE
Dockerfile for boost client

### ISSUE THREAD

**Issue by mrtechit** [filecoin-project/boost#1550]
### Checklist

- [X] This is **not** a new feature or an enhancement to the Filecoin protocol. If it is,  please open an [FIP issue](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md).
- [X] This is **not** brainstorming ideas. If you have an idea you'd like to discuss, please open a new discussion on [the Boost forum](https://github.com/filecoin-project/boost/discussions/categories/ideas) and select the category as `Ideas`.
- [X] I **have** a specific, actionable, and well motivated feature request to propose.

### Boost component

- [ ] boost daemon - storage providers
- [X] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### What is the motivation behind this feature request? Is your feature request related to a problem? Please describe.

I want to use boost client on amazon linux, however some of the packages are not available (at least during my initial investigation). So its better to have a dockerfile

### Describe the solution you'd like

Dockerfile for all boost binaries

### Describe alternatives you've considered

Use a different AWS EC2 image instead of amazon linux

**Comment by LexLuthr** [comment]
@mrtechit We have a dockerfile for devnet at https://github.com/filecoin-project/boost/blob/main/docker/devnet/Dockerfile.source

Please feel free to hack through it to remove lotus related parts and build a mainnet binary of Boost instead of devnet.

**Comment by LexLuthr** [comment]
Task list:
1. Use  https://github.com/filecoin-project/boost/blob/main/docker/devnet/Dockerfile.source for reference
2. We can get rid of Node related stuff as client doesn't have UI
3. We can drop rust related stuff as we don't need to compile `boostx`
4. Create under docker/boost-client/
5. Use Golang 1.20 image
6. Drop lotus related binaries

**Comment by alvin-reyes** [comment]
Do we just want a containerized `boost` or do we need to run specific commands on the `entrypoint?`

**Comment by alvin-reyes** [comment]
@mrtechit do you just need a containerized `boost` (boost-client) without any of the dependencies or do you also need boostd,boostx,boost-data?

**Comment by alvin-reyes** [comment]
Draft: https://github.com/filecoin-project/boost/compare/main...alvin-reyes:boost:main
