### ISSUE TITLE
Funds Page Improvements

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#157]
* Source wallet tooltip is a bit self descriptive. Maybe we should change to something along the lines of "Move funds from the Source Wallet to Escrow to earmark them for deals". It's not immediately clear why I wouldn't just move all my funds from source to Escrow. Can I also move funds from Source to the publish wallet? I don't see UI for that, is that done via lotus directly?
* Escrow tooltip is pretty clear
* Publish tooltip is also clear

* Perhaps we can add some UX here as a call to action for SPs. Can we get a range of how many deals they have escrow for and maybe add a warning label to recommend they move collateral to escrow ("Escrow only has capacity for ~1 more deal, [add funds to escrow](#) before making further deals.")? Effectively I'm thinking about triggers for them too: 
  1. Move funs to source wallet. 
  2. Move funds to Escrow. 
  3. Move funds to Publish storage deals. 
I think leveraging more calls to action would be helpful. We're providing better visibility into the system, and I think adding those nudges to help them keep deals moving will be helpful in several of the views.

**Comment by jacobheun** [comment]
Closing this out in favor of more targeted improvements
