### ISSUE TITLE
Instructions for installing and launching `booster-bitswap` are incorrect

### ISSUE THREAD

**Issue by Shekelme** [filecoin-project/boost#1577]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [X] Other

### Improvement Suggestion

In "Bitswap Retrieval" section of Boost documentation each time after `make booster-bitswap` user should manually move the `booster-bitswap` binary to /usr/local/bin (in general), since we cannot `make install` the specific binary. Otherwise it is impossible to perform next command, `booster-bitswap init`. At least in the form in which the command is given in the documentation.
But in the documentation this point is simply ignored.

**Comment by LexLuthr** [comment]
This has already been fixed in https://github.com/filecoin-project/boost/pull/1519
