### ISSUE TITLE
Transfers page: make the bytes human readable

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#160]
* Use human readable metrics
* Include units on the left hand side of the graph (MB, GB, etc)

**Comment by jacobheun** [comment]
@dirkmc are the units already included? They weren't in the demo on Monday, so just wanted to confirm if those were added yet before closing this out.

**Comment by dirkmc** [comment]
I haven't added the units yet - I was waiting till we have a few UX changes so we can do them all at once

**Comment by jacobheun** [comment]
Sounds good and makes sense, will move this to closed alpha.

**Comment by dirkmc** [comment]
Fixed
