### ISSUE TITLE
Http retrieval retry

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/boost#1605]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [X] Other

### Improvement Suggestion

Hello,

When a HTTP transfer gives timeout one can reconnect, however then the download starts all over again. Is it possible to restart where it left off?

837900K .......... .......... .......... .......... ..........  1%  718K 32h3m
837950K .......... .......... .......... .......... ..........  1%  356K 32h3m
838000K .......... .......... .......... .......... ..........  1%  249K 32h3m
838050K .......... .......... .......... .......... ..........  1%  738K 32h3m
838100K .......... .......... .......... .......... ..........  1%  166K 32h3m
838150K .......... .......... .......... .......... ..........  1%  316K 32h4m
838200K .......... .......... .......... .......... ..........  1%  372K 32h4m
838250K .......... .......... .......... .......... ..........  1%  704K 32h4m
838300K .......... .......... .......... .......... ..........  1%  222K 32h4m
838350K .......... .......... .......... .......... ..........  1%  720K 32h4m
838400K .......... .......... .......... .......... ..........  1%  369K 32h4m
838450K .......... .                                            1%  964M=24m21s

2023-08-03 15:11:19 (574 KB/s) - Read error at byte 1354717575/68719476746 (Connection timed out). Retrying.

--2023-08-03 15:11:20--  (try:94)  http://5.44.251.103:12888/piece/baga6ea4seaqkbdulkm3b33kdqpukyhrkp62iofn6575yihph7vnpobkfewohyoi
Connecting to 5.44.251.103:12888... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68719476746 (64G) [application/piece]
Saving to: ‘/root/downloadedcarfiles/httpretrievals/1881-f02122421-f02244750-46970098-baga6ea4seaqkbdulkm3b33kdqpukyhrkp62iofn6575yihph7vnpobkfewohyoi’

     0K .......... .......... .......... .......... ..........  0% 2.05M 8h53m
    50K .......... .......... .......... .......... ..........  0% 4.03M 6h42m
   100K .......... .......... .......... .......... ..........  0% 6.34K 41d0h
   150K .......... .......... .......... .......... ..........  0% 18.8M 30d18h
   200K .......... .......... .......... .......... ..........  0% 13.5M 24d15h
   250K .......... .......... .......... .......... ..........  0% 9.68M 20d13h
   300K .......... .......... .......... .......... ..........  0% 15.2M 17d14h
   350K .......... .......... .......... .......... ..........  0% 6.88K 29d12h
   400K .......... .......... .......... .......... ..........  0% 39.8M 26d6h
   450K .......... .......... .......... .......... ..........  0% 50.2M 23d15h
   500K .......... .......... .......... .......... ..........  0% 6.09M 21d11h
   550K .......... .......... .......... .......... ..........  0%  720M 19d16h
   600K .......... .......... .......... .......... ..........  0%  963M 18d4h
   650K .......... .......... .......... .......... ..........  0% 1.07G 16d21h
   700K .......... .......... .......... .......... ..........  0% 35.5M 15d18h
   750K .......... .......... .......... .......... ..........  0% 76.5M 14d18h
   800K .......... .......... .......... .......... ..........  0% 19.8M 13d21h
   850K .......... .......... .......... .......... ..........  0% 1.10G 13d3h
   900K .......... .......... .......... .......... ..........  0% 25.8M 12d10h
   950K .......... .......... .......... .......... ..........  0% 1.74M 11d20h
  1000K .......... .......... .......... .......... ..........  0%  196M 11d6h
  1050K .......... .......... .......... .......... ..........  0% 72.5M 10d18h
  1100K .......... .......... .......... .......... ..........  0% 1017M 10d7h
  1150K .......... .......... .......... .......... ..........  0% 67.3M 9d21h
  1200K .......... .......... .......... .......... ..........  0% 71.8M 9d11h
  1250K .......... .......... .......... .......... ..........  0% 73.2M 9d2h
  1300K .......... .......... .......... .......... ..........  0% 91.0M 8d18h
  1350K .......... .......... .......... .......... ..........  0%  887M 8d11h
  1400K .......... .......... .......... .......... ..........  0% 64.8M 8d4h
  1450K .......... .......... .......... .......... ..........  0% 72.6M 7d21h
  1500K .......... .......... .......... .......... ..........  0% 67.5M 7d15h
  1550K .......... .......... .......... .......... ..........  0% 75.3M 7d9h
  1600K .......... .......... .......... .......... ..........  0% 1.32G 7d4h
  1650K .......... .......... .......... .......... ..........  0% 70.9M 6d23h
  1700K .......... .......... .......... .......... ..........  0% 81.8M 6d18h
  1750K .......... .......... .......... .......... ..........  0% 56.7M 6d14h
  1800K .......... .......... .......... .......... ..........  0% 1.05G 6d9h
  1850K .......... .......... .......... .......... ..........  0% 88.8M 6d5h
  1900K .......... .......... .......... .......... ..........  0% 22.1M 6d1h
  1950K .......... .......... .......... .......... ..........  0%  152M 5d22h
  2000K .......... .......... .......... .......... ..........  0% 63.0M 5d18h
  2050K .......... .......... .......... .......... ..........  0% 1.04G 5d15h
  2100K .......... .......... .......... .......... ..........  0% 76.9M 5d12h
  2150K .......... .......... .......... .......... ..........  0% 68.4M 5d9h
  2200K .......... .......... .......... .......... ..........  0% 66.5M 5d6h
  2250K .......... .......... .......... .......... ..........  0% 63.9M 5d3h
  2300K .......... .......... .......... .......... ..........  0%  985M 5d1h
  2350K .......... .......... .......... .......... ..........  0% 61.1M 4d22h
  2400K .......... .......... .......... .......... ..........  0% 71.3M 4d20h
  2450K .......... .......... .......... .......

**Comment by alvin-reyes** [comment]
It would be possible to resume the download if we have an identifier and the sizes. If we have those, the downloader can try requesting the portion of the file by adding the `Range` attribute to only requesting a portion of the missing file and padding it to the file.

**Comment by LexLuthr** [comment]
@cryptowhizzard Following our conversation in Slack, I can confirm that range requests work in booster-http as expected. This should allow clients to resume download and do multi-stream downloads. 
Caveat is that SP should not be disregarding these headers in their reverse proxy. Ultimately, SP has full control over how they respond to requests. 

If you agree with our discussion, then, shall we close this request?

**Comment by cryptowhizzard** [comment]
Sounds good @LexLuthr
