### ISSUE TITLE
Check `ExpectedSealDuration` and `MaxDealStartDelay` for boost deals

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1608]
We are currently not checking these 2 variables within the BasicDealFilters. We must check them or remove the config options from the [Dealmaking] section. 
Since, legacy deals are now deprecated, the importance of these filters is higher.

**Comment by oneforalone** [comment]
Is that these configures would be redundant? Cause there are same variables in `[LotusDealmaking]`, moreover, there's `[Dealmaking]` section in miner's config file. Should i set them both, or just care about `[Dealmaking]` section of boost?
