### ISSUE TITLE
mmlid: The miner address in deals is being stored with a t address

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#1623]
It seems that the miner address in the PieceDeal table in cassandra is sometimes being stored with a `t` address instead of and `f` address.

```
cqlsh> select count(*) from idx.piecedeal where mineraddr = 'f0127896';

 count
-------
  2400

(1 rows)
cqlsh> select count(*) from idx.piecedeal where mineraddr = 't0127896';

 count
-------
    75
```

**Comment by LexLuthr** [comment]
For sofiaminer, the sector does exists and will expire soon.

```
lotus-miner sectors list | grep 1088
1088  Proving           YES      YES     3188586 (in 2 weeks 15 hours)     41     24.73GiB    197.9GiB
```

As LID implementation is complete, maybe it is time to start looking into deal cleanup. We should clean up deals from LID once they expire. As of now LID is holding piece details for all deals since the init of the miner.

**Comment by dirkmc** [comment]
It turns out the problem is that we are no longer calling `SetAddressNetwork` from `build/params.go`.
We need to
- call `SetAddressNetwork` with the appropriate environment, depending on build flags
- add a migration to convert any `t` addresses to `f` addresses in the cassandra and postgres databases.

**Comment by dirkmc** [comment]
After more investigation it turns out the above comment is incorrect.

The problem is that when address.Address decodes a marshalled value, it ignores the network component of the address, and instead sets the environment to whatever the binary doing the unmarshalling was compiled to.

For example:
```
func TestMarshallUnmarshall(t *testing.T) {
	// Ignores f and instead interprets address according to environment
	// set in executable
	a, err := address.NewFromString("f0123456")
	require.NoError(t, err)
	t.Log("address", a.String())
}

=== RUN   TestMarshallUnmarshall
    piecedoctor_test.go:30: address t0123456
--- PASS: TestMarshallUnmarshall (3.32s)
PASS
```

So we need to change the boostd-data executable (not boostd) to
- call SetAddressNetwork with the appropriate environment, depending on build flags
- add a migration to convert any t addresses to f addresses in the cassandra and postgres databases.
