### ISSUE TITLE
Add direct data onboarding client allocation implementation

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1629]
Boost client should allow users to create allocation for verified deals. This functionality is independent of mode of the direct deal i.e. online or offline
The implementation will be based on https://github.com/filecoin-project/lotus/blob/00b8b1856cf8e72031b24952c9cfb89806038828/itests/verifreg_test.go#L426-L464

Expected functionality:
1. Allocate for one pieceCID (Data) to one minerID
2. Allocate for multiple pieceCIDs (Data) to one minerID
3. Allocate one pieceCID (Data) to multiple miners

Wait for message to land on chain and then print new allocations (allow a flag to print all allocations)

1. Add a command to query allocations

Expected commands
```
boost allocate [--wallet <walletID>] --miner <minerID1> <minerID2> --pieceCID <pieceCID1> <pieceCID2>
```

**Comment by LexLuthr** [comment]
Additional Task: Allow for JSON output

**Comment by jennijuju** [comment]
How is this blocked?

**Comment by LexLuthr** [comment]
> why/How is this blocked?

We are waiting for the new branch on Lotus side to sync the dependency. The new branch will also have https://github.com/filecoin-project/lotus/pull/11183 so I can uncomment the verification code and use the gateway APIs instead of full node.

**Comment by jennijuju** [comment]
https://filecoinproject.slack.com/archives/CP50PPW2X/p1692852646487879 - then you should be unblocked 

(also please proactively raise anything thats blocking you from lotus side to us, so we can help 🔪 !
