### ISSUE TITLE
Boost GUI does not display the right sector states.

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/boost#1755]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [X] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
Latest master 16 Oktober 2023
```

### Describe the Bug

The Boost GUI does not display the right sector states even after a day.

For example in the attached screenshot baga6ea4seaqamo2ilocfy5h3j7b5vx76olzox2uhfn5le6gtvrqn3t5dikjauki seems to be in sector 34787 and is already past the publishdeal state a long time.

>>
lotus-miner sectors status 34787
SectorID:	34787
Status:		PreCommit1
CIDcommD:	<nil>
CIDcommR:	<nil>
Ticket:		b79f3b2c90f63572a9798a921ed84a4249371d676fa532e3b085aff8e0911961
TicketH:	3303860
Seed:		
SeedH:		0
Precommit:	<nil>
Commit:		<nil>
Deals:		[58710325]
Retries:	0
>>

>>
lotus state get-deal 58710325
{
  "Proposal": {
    "PieceCID": {
      "/": "baga6ea4seaqamo2ilocfy5h3j7b5vx76olzox2uhfn5le6gtvrqn3t5dikjauki"
    },
    "PieceSize": 34359738368,
    "VerifiedDeal": true,
    "Client": "f01880198",
    "Provider": "f01786387",
    "Label": "bafkreie3zshz2kyryqlpolqgadhipnmz3l6ml2dujf73ylbi4kgw7nkfkm",
    "StartEpoch": 3313282,
    "EndEpoch": 4854082,
    "StoragePricePerEpoch": "0",
    "ProviderCollateral": "7568607423858545",
    "ClientCollateral": "0"
  },
  "State": {
    "SectorStartEpoch": -1,
    "LastUpdatedEpoch": -1,
    "SlashEpoch": -1,
    "VerifiedClaim": 0
  }
}
>>

![Scherm­afbeelding 2023-10-16 om 14 13 21](https://github.com/filecoin-project/boost/assets/36404435/fbe01fd0-88eb-44de-b6ec-361c59adeaf8)

![Scherm­afbeelding 2023-10-16 om 14 13 33](https://github.com/filecoin-project/boost/assets/36404435/5e444260-a20a-4c46-bc26-61a5f07a5e39)

### Logging Information

```text
Using configuration parameters:

  SealingPipelineCacheTimeout = "5m0s"
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by LexLuthr** [comment]
I think there is some confusion here. If you check the deal UUID in the first screenshot, it starts with 4eee....
If you check the only deal which has a sector in the second screenshot, it ha different UUID. It looks like you got multiple deals for the same piece CID. One deal is already sealed and the other one is still waiting to be published.

**Comment by cryptowhizzard** [comment]
Let me clarify here.

From Screenshot 1 to Screenshot 2 the steps i take are just clicking the baga link in screenshot 1.

I don't see the deals duplicate.

**Comment by LexLuthr** [comment]
Your second screenshot is full of duplicate deals. You can click on the deal UUID which has sector ID and onChain deal ID. That will take you to the duplicate deal which is already sealed.

**Comment by cryptowhizzard** [comment]
And here?

![Scherm­afbeelding 2023-10-17 om 14 47 49](https://github.com/filecoin-project/boost/assets/36404435/0629dbcf-3092-4908-9986-5b3bd9f0aa77)
![Scherm­afbeelding 2023-10-17 om 14 47 15](https://github.com/filecoin-project/boost/assets/36404435/ec9ca132-afae-4612-97dc-53e197b101e6)
![Scherm­afbeelding 2023-10-17 om 14 47 00](https://github.com/filecoin-project/boost/assets/36404435/f3998fea-3dfb-47ac-a006-0eccd1940141)
![Scherm­afbeelding 2023-10-17 om 14 46 50](https://github.com/filecoin-project/boost/assets/36404435/1aae177a-2795-4f8e-ac09-51ed5be9c319)

**Comment by LexLuthr** [comment]
@cryptowhizzard The stuck in announcing would be a problem with indexing. Can you check if you are seeing any errors there?

**Comment by LexLuthr** [comment]
@cryptowhizzard Are we good to close this?

**Comment by cryptowhizzard** [comment]
This issue can be closed. With the new version of Boost this is resolved.
