### ISSUE TITLE
no decoder registered for multicodec code 61697

### ISSUE THREAD

**Issue by strahe** [filecoin-project/boost#1822]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [X] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
Deamon: boostd version 2.1.0+calibnet+git.d6383d6
Client: boost version 2.1.0+calibnet+git.d6383d6
Miner: lotus-miner version 1.24.0+calibnet+git.e2f0a4f79
```

### Describe the Bug

![image](https://github.com/filecoin-project/boost/assets/7932644/de113ed4-167b-4230-a348-9e57f83fadeb)

### Logging Information

```text
Error: Failed to retrieve content with candidate miner t017387: data transfer failed: datatransfer error: data transfer channel 12D3KooWQsjnCUtdsuMArK3HqNv1U6FcrnqiAnDiu8hMcvWsRKS4-12D3KooWCbuzR66CUBnQa7vPa1SPEUPDBDU4StegsAnhZqxe4Z78-1701066955143376431 failed to transfer data: channel 12D3KooWQsjnCUtdsuMArK3HqNv1U6FcrnqiAnDiu8hMcvWsRKS4-12D3KooWCbuzR66CUBnQa7vPa1SPEUPDBDU4StegsAnhZqxe4Z78-1701066955143376431: graphsync request failed to complete: could not choose a decoder: no decoder registered for multicodec code 61697 (0xf101)
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by LexLuthr** [comment]
You are using a piece CID to retrieve a payload. Please note that Boost client does not support piece retrieval over Graphsync.
