### ISSUE TITLE
High CPU usage for boostd-data service

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#1826]
Very high CPU usage is observed on boostd-data service when indexing is being performed.

Attached is a PPROF CPU profile dump taken during the high load over 3 minutes.

<img width="748" alt="Screenshot 2023-11-29 at 11 58 04 AM" src="https://github.com/filecoin-project/boost/assets/88259624/991e170a-2a33-440d-a53f-ade21709025f">

[high_cpu.dump.txt](https://github.com/filecoin-project/boost/files/13497643/high_cpu.dump.txt)

**Comment by nonsense** [comment]
Fixed in https://github.com/filecoin-project/boost/pull/1828
