### ISSUE TITLE
Boost Deals table PieceCID is not indexed

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/boost#1852]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [X] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
2.1.1
```

### Describe the Bug

- Boost Deals table misses `PieceCID` index, yet there is a `ByPieceCID` method
- Boost Deals table misses `DealDataRoot` index, yet there is a `ByRootPayloadCID` method (this method is not used)
- Boost Deals table misses `ProviderAddress` and `SectorID` index, yet there is a `BySectorID` method (this method is used every time a deal is made, and more importantly, its being used when a list of sector updates comes through, which can be huge (140k in my case))
- Boost Deals table misses `Checkpoint` index, but the ListActive and ListCompleted make extensive use of these

### Logging Information

```text
-
```

**Comment by RobQuistNL** [comment]
I've just added an index for `SectorID` to the Deals table, and this sped up the `BySectorID` query from 400ms to 14ms (on an unloaded machine)

Checking how fast the sector state updates go in production now...

**Comment by RobQuistNL** [comment]
That turned it from 0.5 - 2 seconds per sector state update to < 1ms;

Before:
```json
{"level":"debug","ts":"2023-12-20T04:53:30.106Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 33652} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T04:53:30.727Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 36828} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T04:53:31.353Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 6938} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T04:53:32.026Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 35695} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T04:53:32.604Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 6455} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T04:53:33.212Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 6856} has 0 deals, seal status Removed"}
(...)
{"level":"debug","ts":"2023-12-20T04:08:01.423Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 30741} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T04:08:02.083Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 35096} has 0 deals, seal status Removed"}
```

After:
```json
{"level":"debug","ts":"2023-12-20T23:45:01.384Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 169976} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T23:45:01.384Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 162039} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T23:45:01.384Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 167594} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T23:45:01.384Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 25216} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T23:45:01.384Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 55146} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T23:45:01.384Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 49044} has 0 deals, seal status Removed"}
{"level":"debug","ts":"2023-12-20T23:45:01.384Z","logger":"index-provider-wrapper","caller":"indexprovider/wrapper.go:161","msg":"sector {<minerid> 77563} has 0 deals, seal status Removed"}
```

**Comment by RobQuistNL** [comment]
@LexLuthr Can you re-open this? This fixes the 3rd point but there's still some fields that could potentially benefit from a proper index

**Comment by LexLuthr** [comment]
Github closed this one I think as it was attached to the PR.

**Comment by RobQuistNL** [comment]
Yerp, figured as much :)
