### ISSUE TITLE
What is the Params limit of TransferExported method?

### ISSUE THREAD

**Issue by beck-8** [filecoin-project/boost#1897]
https://github.com/filecoin-project/boost/blob/203c05bc0ae8b0f6c46e61de18a6bf7ebfb1c6cf/cmd/boost/util/util.go#L141

Is there a recommendation for how many parameters can be stored in a message?

In addition, this writing method is not suitable for large-scale use by users. It is recommended to use parameters such as `--file pieces.txt`
https://github.com/filecoin-project/boost/blob/203c05bc0ae8b0f6c46e61de18a6bf7ebfb1c6cf/cmd/boost/direct_deal.go#L40

**Comment by LexLuthr** [comment]
Using a file restricts the users to a particular format. This way provides a more flexibility using BASH. 
Most of the gas should be required for unmashalling the parameters but I don't have an exact number. Let me check with the Actors team.

**Comment by beck-8** [comment]
> Using a file restricts the users to a particular format. This way provides a more flexibility using BASH.
Can you give me an example? I don't see how this is more convenient.
On the contrary, this is very painful for people who are not skilled in bash. They have no idea how to send 10,000 transactions in batches quickly.
