### ISSUE TITLE
Measure adoption rates for Boost

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#195]
## Problem
We eventually want to deprecate go-fil-markets in Lotus, tracking adoption for SP's running Lotus will allow us to gauge when deprecation will be feasible

## Possible solutions
Boost introduces a new deal protocol over libp2p, `/fil/storage/mk/1.2.0`. We should be able to intermittently connect to SP's to gather their advertised libp2p protocols to determine who has switched to Boost. 

**Questions**
* How can we determine which SP's are using Lotus?

**Comment by nonsense** [comment]
Magik has done this for us.

```
lotus client list-asks --protocols > protos
cat protos | grep mk\/1.2.0
```
