### ISSUE TITLE
TestDummyDeal is flaky

### ISSUE THREAD

**Issue by aarshkshah1992** [filecoin-project/boost#206]
```
StartEpoch:           abi.ChainEpoch(rand.Intn(100000)),
		EndEpoch:             800000 + abi.ChainEpoch(rand.Intn(10000)),
```

The randomness involved in the epoch generation can cause it too fail with start epoch being too close to current epoch. We need to align the current epoch, the start epoch and the end epoch in a way that it's never flaky.

**Comment by nonsense** [comment]
I believe we've fixed this.
