### ISSUE TITLE
Create benchmarks for Storage data transfer speeds

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#208]
Compare data transfer performance against the various storage transfer protocols so we can inform users of expectations around performance.

- Record transfer speed, memory, cpu
- Compare graphsync, libp2p and http transfers
- Compare file sizes for 2, 8, and 32 GB files
- Include 10ms latency to account for round trips

**Comment by dirkmc** [comment]
Closing as this has already been proven in production
