### ISSUE TITLE
Design UX around Snap Deals and Committed Capacity sectors

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#266]
Boost currently doesn't display any information around the status of deals going through the SnapDeals process. It would be helpful for SP's to be able to see the correct stage of deals/sectors that are in this process.

- coordinate with someone from SnapDeals/lotus team to understand how to best represent the flows & states of this process

**Comment by dirkmc** [comment]
Display Snap Deals states on sealing page: https://github.com/filecoin-project/boost/pull/412
