### ISSUE TITLE
[UX] Boost react app should not assume graphql server is running on localhost

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#388]
The Boost react app attempts to connect to the graphql server at localhost:8080.
However the graphql server may be running on a remote host. So the react app should attempt instead to connect to the hostname in the url.

**Comment by SBudo** [comment]
I have this specific issue on my Calibnet deployment, so let me know if you need me to test anything relating to this issue

**Comment by dirkmc** [comment]
Fixed in https://github.com/filecoin-project/boost/pull/420
