### ISSUE TITLE
Support rate limiting bitswap requests (per peer?)

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/boost#394]
Providers may want to manage the amount of traffic they send over bitswap for retrievals, or rate limit specific peers.

Once https://github.com/ipfs/go-bitswap/issues/558 is implemented, we could build a hook and tools for configuring how much data is sent out over bitswap.

**Comment by jacobheun** [comment]
Superseded by https://github.com/filecoin-project/boost/issues/716
