### ISSUE TITLE
Add CheckpointAt timestamp to Deals table

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#413]
Depends on https://github.com/filecoin-project/boost/issues/340

We need to show the user how long a deal has been in a particular state (eg AddPiece):
- Add a CheckpointAt timestamp to the Deals table
- Update the CheckpointAt timestamp each time the checkpoint is updated
- Display a column on the Deals List page and a field on the Deals Detail page indicating how long the deal has been in the current state

**Comment by nonsense** [comment]
Blocked by: https://github.com/filecoin-project/boost/issues/340
