### ISSUE TITLE
Add an option to specify wallet for making deal

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#414]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [X] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boost 0.0.1+git.989bfbc
```

### Describe the Bug

Please add an option to specify the wallet to be used for making the deal. A client can have multiple wallets for different use cases and verified data cap.

Example:

NAME:
   boost deal - Make an online deal with Boost

USAGE:
   boost deal [command options] [arguments...]

OPTIONS:
  --wallet                              wallet address to be used for the deal  <-------------------------- New feature
   --http-url value                 http url to CAR file
   --http-headers value             http headers to be passed with the request (e.g key=value)
   --repo value                     repo directory for Boost client (default: "~/.boost-client")
   --provider value                 storage provider on-chain address
   --commp value                    commp of the CAR file
   --piece-size value               size of the CAR file as a padded piece (default: 0)
   --car-size value                 size of the CAR file (default: 0)
   --payload-cid value              root CID of the CAR file
   --start-epoch value              start epoch by when the deal should be proved by provider on-chain (default: 0)
   --duration value                 duration of the deal in epochs (default: 518400)
   --provider-collateral value      deal collateral that storage miner must put in escrow; if empty, the min collateral for the given piece size will be used (default: 0)
   --storage-price-per-epoch value  (default: 1)
   --verified                       whether the deal funds should come from verified client data-cap (default: true)
   --help, -h                       show help (default: false)
   

We would also need to allow import and export of wallet to facilitate the above request.
   
Example: This can be integrated in `boostx` as well instead of `boost`

NAME:
   boost wallet - Manage wallet

USAGE:
   boost wallet command [command options] [arguments...]

COMMANDS:
   new          Generate a new key of the given type <-- To allow new wallets in case people need to use a different one/ We skip this with if we want to keep only import option and redirect to lotus for creating wallet but that would defeat the purpose of lightweight client.

   list         List wallet address
   balance      Get account balance
   export       export keys
   import       import keys
   default      Get default wallet address
   set-default  Set default wallet address
   help, h      Shows a list of commands or help for one command

OPTIONS:
   --help, -h     show help (default: false)
   --version, -v  print the version (default: false)

### Logging Information

```text
No logging. Feature request.
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by kernelogic** [comment]
Is this supported now?

**Comment by LexLuthr** [comment]
@kernelogic 

```
$ ./boost/boost wallet -h
NAME:
   boost wallet - Manage wallets with Boost

USAGE:
   boost wallet command [command options] [arguments...]

COMMANDS:
   new                   Generate a new key of the given type
   list                  List wallet address
   balance               Get account balance
   export                export keys
   import                import keys
   default, get-default  Get default wallet address
   set-default           Set default wallet address
   delete                Delete an account from the wallet
   help, h               Shows a list of commands or help for one command

OPTIONS:
   --repo value  repo directory for Boost client (default: "~/.boost-client")
   --help, -h    show help (default: false)
```
