### ISSUE TITLE
SPs and clients should be able to mark content as not available for indexing

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#455]
SPs are requesting the ability to publish the index of a particular deals. This would avoid publishing index of the deals where SPs clients have requested the data to kept private.

Suggestion:
We can do this on deal level rather than CID/Multihash level.
This might require a change in deal proposal to check if deal should be indexed or not.

**Comment by jacobheun** [comment]
Replaced by https://github.com/filecoin-project/boost/issues/689
