### ISSUE TITLE
Embed webui in boostd

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/boost#457]
Right now the docs are telling me to run the frontend with `npm run`.

It would be really nice if a frontend build could be embedded into the boostd binary

(go-embed makes embedding resources for http really easy, see https://blog.jetbrains.com/go/2021/06/09/how-to-use-go-embed-in-go-1-16/)

**Comment by magik6k** [comment]
(I also can't just point the dev npm thing at my node because CORS)

**Comment by dirkmc** [comment]
You shouldn't need `npm run` unless you're doing front-end development work on Boost.
When `boostd` starts up it runs a web server on port 8080, so you should just be able to open http://localhost:8080
This server should also accept CORS requests.
Does that work?

**Comment by magik6k** [comment]
I see, that works, but I still need to copy files over.

https://github.com/filecoin-project/boost/blob/e9db5d61c0768c53a249ad5972a82a4768209015/gql/server.go#L108 should be using go:embed

**Comment by magik6k** [comment]
(without copying files I'm just getting a 404)
