### ISSUE TITLE
Unable to cancel data transfers

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/boost#491]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [X] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 0.0.1+git.d561bbf
```

### Describe the Bug

Running `boostd data-transfers list` displays many transfers in progress but these are all stuck. GUI shows no transfers running.
Trying to cancel (see below) any of these returns an error. I have also tried rebooting the machine boost runs on with no efffect, these simply remain.

Sending Channels

ID          Status   Sending To  Root Cid   Initiated? Transferred Voucher                  
1650707137454670694 Ongoing   ...Fxh7nHz3 ...wavlcprm N      1.633MiB   ...aguqeeqq332gqmb3gdjujuqobmwavlcprm"}}  
1650707137454673255 Ongoing   ...Fxh7nHz3 ...deawmjza N      1.654MiB   ...aguqeeqqj7bhoaubtc2r4eyer2deawmjza"}}  
1650709311564020643 Ongoing   ...RvQMWNor ...wavlcprm N      1.631MiB   ...aguqeeqq332gqmb3gdjujuqobmwavlcprm"}}  
1650709311564022618 Cancelling ...RvQMWNor ...deawmjza N      1.587MiB   ...aguqeeqqj7bhoaubtc2r4eyer2deawmjza"}}  

Receiving Channels

_[Empty]_

### Logging Information

```text
boostd data-transfers cancel 1650707137454670694
Error: fatal error calling 'Filecoin.MarketListDataTransfers': panic in rpc method 'Filecoin.MarketListDataTransfers': runtime error: invalid memory address or nil pointer dereference
```

### Repo Steps

1. Run `boostd data-transfers list`
2. Do `boostd data-transfers cancel 1650707137454670694`
3. See error 

> Error: fatal error calling 'Filecoin.MarketListDataTransfers': panic in rpc method 'Filecoin.MarketListDataTransfers': runtime error: invalid memory address or nil pointer dereference

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/boost/pull/493
