### ISSUE TITLE
Indexer error after each new deal on Boost

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/boost#492]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 0.0.1+git.d561bbf
```

### Describe the Bug

After every boost deal is published, Boostd log throws this error "failed to announce deal to network indexer but not failing deal as it's already been handed for sealing"

### Logging Information

```text
2022-04-30T14:07:28.652 INFO filcrypto::proofs::api > generate_data_commitment: start
2022-04-30T14:07:28.653 INFO filcrypto::proofs::api > generate_data_commitment: finish
2022-04-30T14:36:17.988Z        ERROR   boost-storage-deal      logs/log.go:53  failed to announce deal to network indexer but not failing deal as it's already been handed for sealing {"id": "c2ed5e5d-b3a6-4b1d-89e4-9bbc0d5700ea", "err": "failed to announce deal to inde
x provider: failed getting deal bafyreieu5k2pazrtb73s4n4lorkcm7ygcywv73gjror6mkvv7kjqr7xas4: No state for /bafyreieu5k2pazrtb73s4n4lorkcm7ygcywv73gjror6mkvv7kjqr7xas4: datastore: key not found"}
```

### Repo Steps

1. Accept new boost deal
2. Publish deal
3. See error 'failed to announce deal to network indexer but not failing deal as it's already been handed for sealing'
...

**Comment by LexLuthr** [comment]
@stuberman Thanks for reporting this. Can you get more logs from the boost around this. We need to check why index announcement failed.

**Comment by stuberman** [comment]
I am traveling this week, but will do when I have the chance. Note that the deals gets published but I see these errors. Not sure if it affects anything such as the indexer function.

**Comment by dirkmc** [comment]
Thanks for the bug report @stuberman 
This is fixed by https://github.com/filecoin-project/boost/pull/508
