### ISSUE TITLE
UI - Sealing Pipeline - Duplicate list of running jobs

### ISSUE THREAD

**Issue by SBudo** [filecoin-project/boost#503]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [X] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 0.0.1+git.10c5ec8
```

### Describe the Bug

When sealing CC sectors, the "Sealing Pipeline" in the boost UI first displays the correct list of sealing jobs running under the "workers" list.
After a few seconds, the list start to fill-up with duplicates line items of the existing jobs. 
The UI will continue to fill-up the list with duplicate until you refresh the page.

![Screenshot Sealing pipeline](https://user-images.githubusercontent.com/16908232/166687955-f23724b4-28f3-4159-a667-79e077e098ec.png)
[boost20220504-1050.log](https://github.com/filecoin-project/boost/files/8620626/boost20220504-1050.log)
.

### Logging Information

```text
boosts logs attached
```

### Repo Steps

- start sealing some CC sectors (no deals sectors)
- watch the sealing jobs in the UI 
- wait for 5/10 seconds and duplicates jobs will start to appear in the list

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/boost/pull/504
