### ISSUE TITLE
Errors trying to reinstall Boost

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/boost#507]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [X] Other

### Boost Version

```text
boostd --version
boostd version 0.0.1+git.4fb17ba
```

### Describe the Bug

When trying to update boost, get these errors

`make build`
> npm install --prefix react
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: apollo-link-ws@1.0.20
> npm ERR! Found: subscriptions-transport-ws@0.11.0
> npm ERR! node_modules/subscriptions-transport-ws
> npm ERR!   subscriptions-transport-ws@"^0.11.0" from the root project
> npm ERR!   peerOptional subscriptions-transport-ws@"^0.9.0 || ^0.11.0" from @apollo/client@3.5.5
> npm ERR!   node_modules/@apollo/client
> npm ERR!     @apollo/client@"^3.4.16" from the root project
> npm ERR!     @apollo/client@"latest" from @apollo/react-hooks@4.0.0
> npm ERR!     node_modules/@apollo/react-hooks
> npm ERR!       @apollo/react-hooks@"^4.0.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer subscriptions-transport-ws@"^0.9.0" from apollo-link-ws@1.0.20
> npm ERR! node_modules/apollo-link-ws
> npm ERR!   apollo-link-ws@"^1.0.20" from the root project
> npm ERR! 
> npm ERR! Conflicting peer dependency: subscriptions-transport-ws@0.9.19
> npm ERR! node_modules/subscriptions-transport-ws
> npm ERR!   peer subscriptions-transport-ws@"^0.9.0" from apollo-link-ws@1.0.20
> npm ERR!   node_modules/apollo-link-ws
> npm ERR!     apollo-link-ws@"^1.0.20" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR! See /home/stuart/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/stuart/.npm/_logs/2022-05-08T02_26_52_099Z-debug-0.log
> make: *** [Makefile:96: react] Error 1
> 

`sudo make install`

> bash: go: command not found
> expr: syntax error: unexpected argument ‘1016000’
> install -C ./boost /usr/local/bin/boost
> install: cannot stat './boost': No such file or directory
> make: *** [Makefile:109: install-boost] Error 1

### Logging Information

```text
See errors above
```

### Uninstall Boost

sudo rm -r boost
sudo apt-get remove nodejs
sudo npm uninstall npm -g

### Install Boost
sudo apt install nodejs
git clone https://github.com/filecoin-project/boost
cd boost
make build
sudo make install

**Comment by stuberman** [comment]
Update - the react dependency errors are causing the build script to fail prematurely. Please review these dependencies and test.

**Comment by stuberman** [comment]
Now on Boostd start I see this:

> 2022-05-08T04:41:54.780Z	INFO	boost-provider	storagemarket/provider.go:422	storage provider: started
> 2022-05-08T04:41:54.784Z	INFO	index-provider-wrapper.boost-migrator	indexprovider/wrapper.go:180	dagstore root is /market/.boost/dagstore
> 2022-05-08T04:41:54.784Z	INFO	index-provider-wrapper.boost-migrator	indexprovider/wrapper.go:189	no boost shard migration necessary; already marked complete
> 2022-05-08T04:41:54.784Z	INFO	gql	gql/server.go:40	graphql server: starting
> 2022-05-08T04:41:54.784Z	WARN	gql	gql/server.go:125	not serving react app: no files found in embedded react build directory - you may need to build the boost react app
> Graphql server listening on :8080
> 2022-05-08T04:41:54.796Z	DEBUG	boostd	boostd/run.go:101	Getting API endpoint of boost node
> 2022-05-08T04:41:54.796Z	INFO	boostd	boostd/run.go:114	Boost libp2p node listening	{"mad

**Comment by stuberman** [comment]
Additional update:
I suspect the two problems are these when following Build React Frontend instructions:
1. Older dependencies (I can run this to resolve: `npm install --legacy-peer-deps` or `npm install --legacy-peer-deps caniuse-lite`
2. OpenSSL incompatibility with Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-109-generic x86_64)
  Throws error: "Error: error:0308010C:digital envelope routines::unsupported"
  See: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by dirkmc** [comment]
I think I've seen that second error when running the newest version of nodejs.
Which version of nodejs are you running at the moment? Could you try with version 16?

**Comment by stuberman** [comment]
I will downgrade to v16

Right now
`node -v && npm -v`

> v18.1.0
> 8.9.0

**Comment by LexLuthr** [comment]
@dirkmc Done

**Comment by Trevor-K-Smith** [comment]
```
root@Markets-01:~/Git/boost# make build
Building using Node v16
npm install --prefix react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: apollo-link-ws@1.0.20
npm ERR! Found: subscriptions-transport-ws@0.11.0
npm ERR! node_modules/subscriptions-transport-ws
npm ERR!   subscriptions-transport-ws@"^0.11.0" from the root project
npm ERR!   peerOptional subscriptions-transport-ws@"^0.9.0 || ^0.11.0" from @apollo/client@3.5.5
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.4.16" from the root project
npm ERR!     @apollo/client@"latest" from @apollo/react-hooks@4.0.0
npm ERR!     node_modules/@apollo/react-hooks
npm ERR!       @apollo/react-hooks@"^4.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer subscriptions-transport-ws@"^0.9.0" from apollo-link-ws@1.0.20
npm ERR! node_modules/apollo-link-ws
npm ERR!   apollo-link-ws@"^1.0.20" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: subscriptions-transport-ws@0.9.19
npm ERR! node_modules/subscriptions-transport-ws
npm ERR!   peer subscriptions-transport-ws@"^0.9.0" from apollo-link-ws@1.0.20
npm ERR!   node_modules/apollo-link-ws
npm ERR!     apollo-link-ws@"^1.0.20" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-05T05_29_55_327Z-debug-0.log
make: *** [Makefile:104: react] Error 1
root@Markets-01:~/Git/boost# node -v && npm -v
v16.15.1
8.11.0

```

**Comment by Trevor-K-Smith** [comment]
```
cd react
npm install --legacy-peer-deps caniuse-lite
cd ..
vim Makefile
<remove the `npm install --prefix react` line>
:wq
make build
make install
```

**Comment by Trevor-K-Smith** [comment]
Yes, Confirm.
