### ISSUE TITLE
CLI command: `dagstore register-shard <piece cid>`

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#509]
Sometimes a deal will be correctly handed off to the sealer, but the deal will not be successfully registered with the DAG store. See https://github.com/filecoin-project/boost/issues/499

There are a couple of stages that a deal goes through with the DAG store:
1. When the deal has been handed off to the sealer, it is `Registered`
  This means the DAG store knows about the deal (knows its piece CID)
2. In the background, the deal is `Initialized`
  This means the DAG store gets the deal data from the sealer, and builds an index of its cids

The command `dagstore initialize-shard` will only work if the DAG store already knows about the deal: ie the deal's piece was `Registered`.

We need a command that will allow users to manually register a deal with the DAG store:
`dagstore register-shard <piece cid>`

**Comment by stuberman** [comment]
I upgraded boost to `boostd version 0.0.1+git.817f9eb` in the last hour.
In the last hour I saw dozens of these errors:

> 2022-05-10T23:28:51.587Z	ERROR	retrieval	impl/provider.go:343	Retrieval query: getPieceInfoFromCid: getting pieces for cid Qmbj9md2rexbV7hzyXRU4em3JWKDdYGMwZDrC1rVmsuRZp: getting pieces containing block Qmbj9md2rexbV7hzyXRU4em3JWKDdYGMwZDrC1rVmsuRZp: failed to lookup index for mh 1220c6eb91187530c184a5883c4437dd4c85f5c563c948d295baad4cf10adc9cab0f, err: datastore: key not found
> 2022-05-10T23:28:54.001Z	ERROR	retrieval	impl/provider.go:343	Retrieval query: getPieceInfoFromCid: getting pieces for cid QmVh8fe2Pg4vKY13vV2estzytsQbum9V48Dh4aNPRiouLp: getting pieces containing block QmVh8fe2Pg4vKY13vV2estzytsQbum9V48Dh4aNPRiouLp: failed to lookup index for mh 12206d41094893481f8483dd3905fe2d508b0cca72f7b6b38e650771dba97c8aa68d, err: datastore: key not found
> 2022-05-10T23:28:54.634Z	DEBUG	gql	gql/resolver_storage.go:45	storage values	{"tagged": 0, "transferred": 0, "staged": 0, "sealing": 2834898779421}
> 2022-05-10T23:28:56.870Z	ERROR	retrieval	impl/provider.go:343	Retrieval query: getPieceInfoFromCid: getting pieces for cid QmeYs8FLdGLACVsXKGMQ3zNEeF3pD91ZfbPA8iamMHbmSd: getting pieces containing block QmeYs8FLdGLACVsXKGMQ3zNEeF3pD91ZfbPA8iamMHbmSd: failed to lookup index for mh 1220f0dbffe6473f0e14ef9f979e9c3dafee9001600ab812dc3262d0dc3e2b3e434e, err: datastore: key not found
> 2022-05-10T23:28:57.054Z	ERROR	retrieval	impl/provider.go:343	Retrieval query: getPieceInfoFromCid: getting pieces for cid QmeE4UBz8ncUDJdfsasHFmat4qVc21m6HuKRVg5iAcCLzR: getting pieces containing block QmeE4UBz8ncUDJdfsasHFmat4qVc21m6HuKRVg5iAcCLzR: failed to lookup index for mh 1220ec0aca6e4af442abff7f40347825953feaacd2d82772dd1a943ab744a25dab76, err: datastore: key not found

**Comment by dirkmc** [comment]
@stuberman could you please update boost to the latest from the `main` branch and run the following commands with some of the payload cids that you pasted in the log output above:
```
# Get the piece cid from the payload cid
$ boostd pieces cid-info <payload cid>
Info for:  <payload cid>
PieceCid     Offset  Size
<piece cid>  0       0

# Check that the piece has been added to the piece store
$ boostd pieces piece-info <piece cid>
Piece:  <piece cid>
Deals:
DealID   SectorID  Length       Offset
123      456       34359738368  0

# Check that the piece has been added to the DAG store
$ boostd dagstore list-shards | grep <piece cid>
<piece cid>

# If you don't see the piece in the DAG store try this
$ boostd dagstore register <piece cid>

# Initialize the DAG store piece cid
$ boostd dagstore initialize-shard <piece cid>
```

**Comment by stuberman** [comment]
Also notice that the sector is almost a year old. It is common practice for SPs to delete old unsealed sectors if space is needed. For Slingshot we usually keep unsealed sectors for at least 90 days.

**Comment by RobQuistNL** [comment]
Those logs will be from us at Evergreen trying to retrieve & renew your 54.820 TB of deals before they expire :)

**Comment by stuberman** [comment]
I think the issue is that if an unsealed sector is missing, Lotus does not unseal the needed sector for retrievals and causes indexing issues.

**Comment by dirkmc** [comment]
Fixed by https://github.com/filecoin-project/boost/pull/517

**Comment by dirkmc** [comment]
>  I think the issue is that if an unsealed sector is missing, Lotus does not unseal the needed sector for retrievals and causes indexing issues.

That sounds right to me @stuberman
I'm going to close this issue as it's really about the register-shard CLI command, and it sounds like we've found the source of the errors you were seeing.
