### ISSUE TITLE
Add support for SPs to rate limit incoming deals (ASKv2 support)

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#53]
Currently there is no good backoff mechanism to allow Storage Providers to rate limit incoming storage deal requests. The key problem is around the associated data transfer, as accepting deals immediately triggers data transfer, and too many in progress deals can starve needed resources.

### ASKv2 Protocol
The [ARG team](https://github.com/application-research) has currently proposed an initial iteration of the [ASKv2 protocol](https://hackmd.io/xAk_QnXeQCiYtb4BaeOMwg?view) to enable Storage Providers to respond to ASK requests with a backoff timing, ie: "Hey, come back in 3 hours and let's do this". This should provide an immediate improvement to the existing deal negotiation that Estuary and other clients are making. 

Long term solutions may include order books or deal markets to enable easier discovery of SPs who have bandwidth to accept deals immediately.

**Dependencies**
* Requires a "finalized" design of the ASKv2 protocol. (We may wish to test early iterations of this with Estuary to find appropriate flows for backoff)

**Comment by LexLuthr** [comment]
Closing this as SPs can use offline deals if they wish to control in in flow of the deals themselves. Practical example of this would be "Spade" program.  We can reopen this if there is more demand for the feature.
