### ISSUE TITLE
GUI shows StorageDealError right after AP of deal into sector

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/boost#547]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [X] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd --version
boostd version 0.0.1+git.bc85712
```

### Describe the Bug

After two deals publish, Legacy Storage Deals page shows two deals (in two separate sectors) in state 'StorageDealError' despite these deals being on chain and being sealed by worker. I see this once in a while and assume this may be due to two deals being published in the same PublishStorageDeals message (see below). Once these deals in UI show 'StorageDealError' the UI does not update and recover from this misinformation.

See logs below and Filfox link for publish message. These are from Evergreen deals and have not expired.

21h | bafyreicwcqb… | 32 GiB | f1pkrmyg… | StorageDealError: error awaiting deal pre-commit: failed to set up called handler: called check error (h: 1848792): failed to look up deal on chain: deal 6567133 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed
-- | -- | -- | -- | --
21h | bafyreifz7gx… | 32 GiB | f1pkrmyg… | StorageDealError: error awaiting deal pre-commit: failed to set up called handler: called check error (h: 1848803): failed to look up deal on chain: deal 6567132 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed

`lotus-miner sectors status --on-chain-info --log 4446`

SectorID:	4446
Status:		Proving
CIDcommD:	baga6ea4seaqjnkhj7adimkczjnwcnz5iqex7z6enabgt674cau4ppt6s3r2jefi
CIDcommR:	bagboea4b5abcbbw27wlaw7vpgsppm3rmigichzwoizh5y2kt4pzmtf6zrw4puvzh
Ticket:		caef7b32fb45cbb34279779bc26caa1e9155a107ac7076a939a9dcea7a07a786
TicketH:	1847971
Seed:		70986f66115e6815681cf619ed37299efc6b61bed6c7ef52d1c3741da2018a76
SeedH:		1849387
Precommit:	bafy2bzacearrylarmcmla4vzbf5nlr3epifjaxhs5sdnnkdilyg2cke4hfgwy
Commit:		bafy2bzaced2sx7ruloe4n6hzl45l44tdhbfj7xghn3by2kktfltmdei4yaeoa
Deals:		[6567133]
Retries:	0

Sector On Chain Info
SealProof:		8
Activation:		1849454
Expiration:		3391788
DealWeight:		0
VerifiedDealWeight:		52739037298950144
InitialPledge:		1.681470351672090508 FIL

Expiration Info
OnTime:		3391968
Early:		0
--------
Event Log:
0.	2022-05-28 21:07:31 +0000 UTC:	[event;sealing.SectorStart]	{"User":{"ID":4446,"SectorType":8}}
1.	2022-05-28 21:07:31 +0000 UTC:	[event;sealing.SectorAddPiece]	{"User":{}}
2.	2022-05-28 21:15:45 +0000 UTC:	[event;sealing.SectorPieceAdded]	{"User":{"NewPieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqjnkhj7adimkczjnwcnz5iqex7z6enabgt674cau4ppt6s3r2jefi"}},"DealInfo":{"PublishCid":{"/":"bafy2bzacebfo5f36yqd3qlbuq46ub6v2hqtq4ctz7kw2ubmrufvnztukpyjhw"},"DealID":6567133,"DealProposal":{"PieceCID":{"/":"baga6ea4seaqjnkhj7adimkczjnwcnz5iqex7z6enabgt674cau4ppt6s3r2jefi"},"PieceSize":34359738368,"VerifiedDeal":true,"Client":"f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda","Provider":"f01278","Label":"QmfRRPDFMNnLsJvFYcNcUZUTwEBXwAcTjy4UaDV8kq9Bj6","StartEpoch":1856880,"EndEpoch":3391788,"StoragePricePerEpoch":"0","ProviderCollateral":"10289023394331808","ClientCollateral":"0"},"DealSchedule":{"StartEpoch":1856880,"EndEpoch":3391788},"KeepUnsealed":true}}]}}
3.	2022-05-28 21:15:45 +0000 UTC:	[event;sealing.SectorStartPacking]	{"User":{}}
4.	2022-05-28 21:15:45 +0000 UTC:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
5.	2022-05-28 21:15:45 +0000 UTC:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"yu97MvtFy7NCeXebwmyqHpFVoQescHapOanc6noHp4Y=","TicketEpoch":1847971}}
6.	2022-05-29 00:05:07 +0000 UTC:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJfbG90dXNfU2VhbFJhbmRvbW5lc3MiOiJ5dTk3TXZ0Rnk3TkNlWGVid215cUhwRlZvUWVzY0hhcE9hbmM2bm9IcDRZPSIsImNvbW1fZCI6WzE1MCwxNjgsMjMzLDI0OCw2LDEzNCw0MCw4OSw3NSwxMDgsMzgsMjMxLDE2OCwxMjksNDcsMjUyLDI0OCwxNDEsMCw3Nyw2MywxMjcsMTMwLDUsNTYsMjQ3LDIwNywyMTAsMjIwLDExNiwxNDYsMjFdLCJjb25maWciOnsiaWQiOiJ0cmVlLWQiLCJwYXRoIjoiL3NlYWwyL3dvcmtlci9jYWNoZS9zLXQwMTI3OC00NDQ2Iiwicm93c190b19kaXNjYXJkIjo3LCJzaXplIjoyMTQ3NDgzNjQ3fSwibGFiZWxzIjp7IlN0YWNrZWREcmczMkdpQlYxIjp7Il9oIjpudWxsLCJsYWJlbHMiOlt7ImlkIjoibGF5ZXItMSIsInBhdGgiOiIvc2VhbDIvd29ya2VyL2NhY2hlL3MtdDAxMjc4LTQ0NDYiLCJyb3dzX3RvX2Rpc2NhcmQiOjcsInNpemUiOjEwNzM3NDE4MjR9LHsiaWQiOiJsYXllci0yIiwicGF0aCI6Ii9zZWFsMi93b3JrZXIvY2FjaGUvcy10MDEyNzgtNDQ0NiIsInJvd3NfdG9fZGlzY2FyZCI6Nywic2l6ZSI6MTA3Mzc0MTgyNH0seyJpZCI6ImxheWVyLTMiLCJwYXRoIjoiL3NlYWwyL3dvcmtlci9jYWNoZS9zLXQwMTI3OC00NDQ2Iiwicm93c190b19kaXNjYXJkIjo3LCJzaXplIjoxMDczNzQxODI0fSx7ImlkIjoibGF5ZXItNCIsInBhdGgiOiIvc2VhbDIvd29ya2VyL2NhY2hlL3MtdDAxMjc4LTQ0NDYiLCJyb3dzX3RvX2Rpc2NhcmQiOjcsInNpemUiOjEwNzM3NDE4MjR9LHsiaWQiOiJsYXllci01IiwicGF0aCI6Ii9zZWFsMi93b3JrZXIvY2FjaGUvcy10MDEyNzgtNDQ0NiIsInJvd3NfdG9fZGlzY2FyZCI6Nywic2l6ZSI6MTA3Mzc0MTgyNH0seyJpZCI6ImxheWVyLTYiLCJwYXRoIjoiL3NlYWwyL3dvcmtlci9jYWNoZS9zLXQwMTI3OC00NDQ2Iiwicm93c190b19kaXNjYXJkIjo3LCJzaXplIjoxMDczNzQxODI0fSx7ImlkIjoibGF5ZXItNyIsInBhdGgiOiIvc2VhbDIvd29ya2VyL2NhY2hlL3MtdDAxMjc4LTQ0NDYiLCJyb3dzX3RvX2Rpc2NhcmQiOjcsInNpemUiOjEwNzM3NDE4MjR9LHsiaWQiOiJsYXllci04IiwicGF0aCI6Ii9zZWFsMi93b3JrZXIvY2FjaGUvcy10MDEyNzgtNDQ0NiIsInJvd3NfdG9fZGlzY2FyZCI6Nywic2l6ZSI6MTA3Mzc0MTgyNH0seyJpZCI6ImxheWVyLTkiLCJwYXRoIjoiL3NlYWwyL3dvcmtlci9jYWNoZS9zLXQwMTI3OC00NDQ2Iiwicm93c190b19kaXNjYXJkIjo3LCJzaXplIjoxMDczNzQxODI0fSx7ImlkIjoibGF5ZXItMTAiLCJwYXRoIjoiL3NlYWwyL3dvcmtlci9jYWNoZS9zLXQwMTI3OC00NDQ2Iiwicm93c190b19kaXNjYXJkIjo3LCJzaXplIjoxMDczNzQxODI0fSx7ImlkIjoibGF5ZXItMTEiLCJwYXRoIjoiL3NlYWwyL3dvcmtlci9jYWNoZS9zLXQwMTI3OC00NDQ2Iiwicm93c190b19kaXNjYXJkIjo3LCJzaXplIjoxMDczNzQxODI0fV19fSwicmVnaXN0ZXJlZF9wcm9vZiI6IlN0YWNrZWREcmczMkdpQlYxXzEifQ=="}}
7.	2022-05-29 00:18:23 +0000 UTC:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcbbw27wlaw7vpgsppm3rmigichzwoizh5y2kt4pzmtf6zrw4puvzh"},"Unsealed":{"/":"baga6ea4seaqjnkhj7adimkczjnwcnz5iqex7z6enabgt674cau4ppt6s3r2jefi"}}}
8.	2022-05-29 00:18:24 +0000 UTC:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzacearrylarmcmla4vzbf5nlr3epifjaxhs5sdnnkdilyg2cke4hfgwy"},"PreCommitDeposit":"115751268916518620","PreCommitInfo":{"SealProof":8,"SectorNumber":4446,"SealedCID":{"/":"bagboea4b5abcbbw27wlaw7vpgsppm3rmigichzwoizh5y2kt4pzmtf6zrw4puvzh"},"SealRandEpoch":1847971,"DealIDs":[6567133],"Expiration":3391788,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
9.	2022-05-29 00:21:30 +0000 UTC:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIgOVCOMemF0bNXxnsZ5SBH6Gw82ShseuzSWeYpvp3zHGoBcaDkAiA6gj04S4pxR3CBYfL7SAH5cT/6JaNFEuz5LO1+aiCJpAFxoOQCIBY7R0R8oIXbF9cn9OwFXyPxqt1tbz6C3KeJptnIcVSSAXGg5AIgK2rGExKxkCe7adizoS8yis+HZthiEZLFCA5ugVeXl1I="}}
10.	2022-05-29 01:36:30 +0000 UTC:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"cJhvZhFeaBVoHPYZ7TcpnvxrYb7Wx+9S0cN0HaIBinY=","SeedEpoch":1849387}}
11.	2022-05-29 01:55:27 +0000 UTC:	[event;sealing.SectorProofReady]	{"User":{"Proof":"hi55rvuwhsiVKy/HkdHGPrPwmC99OSmNmpYrQ2h/SZtSs1UwIQKe9/LJpAA0OKIthwcTXR2tcN2Q7yojloED5yJHP39rOd/fWw/do9OhG3bjyZufnntYrHX4tbRl+8+jASPs9c8BS2LF20C3Y0Uh/PsgoaPwzfADHTCj4/GZCxuiQNwsVCxt2e6Y/l5YvYx2hY5SqwFZt+sP0jhQk1Sune4luKMhWk45TdSUSmJAy+tmtc6KvOz5Bs+63x759ONcjZm47C38pRv14TWaxDDI8cOydwJoCh6U9rhZkmdWH7i32SADXO+N8DnfvHKnaVgpsGGj8FGCJvR+Khx7DD09XyHavOvzYF2YznA8Q+WQuTEgGFhEDWxFfINi/9S5UwCUEnwyyhMaDsluTjS0Mv87BTdwQcGoqnbB8hE4FRBj4OSohsbIxaIHy+eFf4fGxxKPrYznx8Bixe/t5KdDvVTNx6M8eC5V/eBBbiDoIysvoaSLs6aBw7qL9fUFkvVlJsStrsx2N5aXdbDpK4ItGaXMIpM/sei02rzKHWJNVitzvVWSwhilw3ygdanbWAzk9M9vhORv30ocVUTp+v1b8hlAXEGi6iEkZ2IJeO01lszicuNfXrLksJ45slmirGq8DFeyEHKf88h054DW5QeRQrRxPvq4NTVc+t1Ag8B2xJiFlfyXlK2iuP49GeTxxFesGxCShbH4gcg7VUzG1+qLDWm2W+OEGkSlXQvljovXcFu7GFyj9yjrOPZ+g3Ev50Ms0wxNt8G1Ru3tNK4KmITJfWrIzUxmDoQpX61rSTZebXwtQ7sPHYuTYBZ1aK6ls9u7zYOirR3G7m08PKN+r78SjG1qBBQ5r8xKaFMXVPnAovFcmgObA1NOQlK/R9dqnmFTBXzBEO0dMQCqpQGLp/XdEWChpeupoeBT5FBVkEq0sp46PxwhKk/BNXnqOlUncIwlDQoYttojXzd5UDJLGaXdMMLhhRQYe6pMsF59DlC7S8kgzpZ2+GgggOhIxaLO3mHpturYouTmSf5DrpGVJ9bIklzc63KdbtMNrCUbB1Zc7Vev9y2DliM/MX/EaaAj730O/9z2oRdm/eufO2Xh+E0sZ8NNzEQaeX6X0HhlDKPiyBZUvT0ZANDlm1RKUVTYNpbBamKLB5/KgPLKC/mn2NSLVvxgvs8DgF8OD/yMCimil5iCoKwd7jaSvQSoS2R7xjh02uFprl54hDBrSbeHfxi53Qu/rbssOoe6NB5UNvGoGVGpfJtslXxQifC+MHoGNLcuNyUzqM4huek2+ALzNA/Kdz4KYz/FF6EH2eQrwBbjUzSBDEk+aO+x735nzOjHl7zpxrHLgFdZuqRD1MiBohoPwFkKXwARy6qR+vGjWn1LykHZ8hbeHfod5HCwrMfG8PJptEm/FuHBYmHzsjOPYoChXTt36DN0CbjDV5f2WEe+UJpBCdr+PbnMg+sAHJAByINpdv0TklCBld/sOVxIo2S4bBeCCPTYA/j1mtyvvyaRSJn4M7OtTxir1rSjgEmK718h+BOlkhoFtrJYhJ1sCzRwxbCf6oyTvy7c9Ewg1kHIiLTECOqLK3zOJr4uBQp2eCHrjUq9om9QClUa8irZnSQhIgU8XhbXx5DgLsLX2X9zJBVexDRJ73mw/WKPFbTlNi/2YbeZGNYhm24knnmJ661KlafMmEM9aEAwDNkY6TvcFwJAq770G5sOaTkzZsbGItBNsRMPrqojRBf6CexvsspL4ExRJs6CHj+GX3qogv0vL6aELretslQx04DBd1WmslsgMVhAprWdz/mLJE+vCyS8RXal4tdTCpqTi50fDvnXp+XYN5mbfKu5ykPj3GTZPCRtjoKwiQAv/SGSC82jxKKg97+morQyuYGRchx99KJxMNKUG++y608N4NxNL23WOl/H6w5WC8FDaPNAT8rHeKHR6vA+v1oe+WQ8knVziy7avNZGh5fI3rnxhUS4uKCMxhPVPO5wuP79YsSMjuteuwYH8NAjlpY1rrAxU3rss/eiP9BsFrfG+IOh+a2+dJipjwoq61Zdkg9L+JVEh076rQ0O5XcfZ3u0gY+KTeWrI4nK2aU6TG11d6TVXL6qkLB64lxTFBHElH8ahv3TjgCKPH+PvQ4sFyqrDoe7eFvMKuTi9hgT1uAb66SxTrZR3HyYGc0pub6tClMhN1XDRghRs7j2C87F8lMTCD1fsiK3gXBRtIz6pc5ow9mg/D+cERmWOw46rcviittIfQqBgpYvypphzpjE0xJP8pdTfUr8ezpG8eg29W79QAlQXHCE4dE4DPPvjZ0ngoAFoX7Z2pAIaU1KGiRscO3ZX0cv8JhL8NxLGRxIk5bu4paEoYBAXC3MloI/wGbApv/foSxYoqm+/fvU5mLV5ut3M6paRYBCoCoKJgt48k8oQl6fywo0J3wSnH50ifA5D88Bx/n/14jS+cFV1t6WlMHSPycXuih/IjyDi7r0YDOYLlAyAFl/FWgRiuPim/DnkjTBz8mctLaO5oF+tlpCLIOqM34HAbni353SYAaQR8yOivDtwiKbCD+IQ9f4/Qim"}}
12.	2022-05-29 02:06:03 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}
13.	2022-05-29 02:06:50 +0000 UTC:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzaced2sx7ruloe4n6hzl45l44tdhbfj7xghn3by2kktfltmdei4yaeoa"}}}
14.	2022-05-29 02:10:00 +0000 UTC:	[event;sealing.SectorProving]	{"User":{}}
15.	2022-05-29 02:10:01 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}

### Logging Information

```text
https://filfox.info/en/message/bafy2bzacebfo5f36yqd3qlbuq46ub6v2hqtq4ctz7kw2ubmrufvnztukpyjhw

From Legacy Storage Deals page link to deal info:

Deal bafyreicwcqbghcterhu5ffaff5mdzvverrtli5keq7vgqbczbbwt4cvaxu
CreatedAt	2022-05-27 20:44:42.037 (21h ago)
Client Address	f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda
Client Peer ID	12D3KooWDWvRmzED7a1YjyKiinzmuQ5B9BGEXmMHk4VKNHC58bta
Deal Data Root CID	QmfRRPDFMNnLsJvFYcNcUZUTwEBXwAcTjy4UaDV8kq9Bj6
CAR File Path	
Piece CID	baga6ea4seaqjnkhj7adimkczjnwcnz5iqex7z6enabgt674cau4ppt6s3r2jefi
Piece Size	32 GiB (34,359,738,368 bytes)
Piece File Path	
Provider Collateral	0.01 FIL
Funds Reserved	0 atto
Current Epoch	1,848,908
Start Epoch	1,856,880 (in 3 days)
End Epoch	3,391,788 (in a year)
Transfer Type	manual
Transferred	0 B (0 bytes)
Transfer Size	
Available for Retrieval	Yes
Chain Deal ID	6567133
Publish Message CID	bafy2bzacebfo5f36yqd3qlbuq46ub6v2hqtq4ctz7kw2ubmrufvnztukpyjhw
Status	StorageDealError
Message	error awaiting deal pre-commit: failed to set up called handler: called check error (h: 1848792): failed to look up deal on chain: deal 6567133 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by stuberman** [comment]
BTW - Since I posted this, I saw the same issue with single deals being published as well. Could it be that the error is detected too soon and the task needs to either wait longer or allow for an update when the deal hits the chain?

**Comment by LexLuthr** [comment]
@stuberman Can you also paste the logs from boost UI for this deal? There should be a copy button when you open the deal page.

**Comment by stuberman** [comment]
@LexLuthr For legacy deals, I don't see a copy button, only newer deals. Here is me copying everything on the page

**DEAL bafyreicwcqbghcterhu5ffaff5mdzvverrtli5keq7vgqbczbbwt4cvaxu**

CreatedAt	2022-05-27 20:44:42.037 (3 days ago)
Client Address	f1pkrmygbvweykpjcut36lf7ewgqdfhjklbhvepda
Client Peer ID	12D3KooWDWvRmzED7a1YjyKiinzmuQ5B9BGEXmMHk4VKNHC58bta
Deal Data Root CID	QmfRRPDFMNnLsJvFYcNcUZUTwEBXwAcTjy4UaDV8kq9Bj6
CAR File Path	
Piece CID	baga6ea4seaqjnkhj7adimkczjnwcnz5iqex7z6enabgt674cau4ppt6s3r2jefi
Piece Size	32 GiB (34,359,738,368 bytes)
Piece File Path	
Provider Collateral	0.01 FIL
Funds Reserved	0 atto
Current Epoch	1,854,170
Start Epoch	1,856,880 (in a day)
End Epoch	3,391,788 (in a year)
Transfer Type	manual
Transferred	0 B (0 bytes)
Transfer Size	
Available for Retrieval	Yes
Chain Deal ID	6567133
Publish Message CID	bafy2bzacebfo5f36yqd3qlbuq46ub6v2hqtq4ctz7kw2ubmrufvnztukpyjhw
Status	StorageDealError
Message	error awaiting deal pre-commit: failed to set up called handler: called check error (h: 1848792): failed to look up deal on chain: deal 6567133 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed

**Comment by dirkmc** [comment]
This deal was made with v1.1.0 of the deal making protocol, so I don't believe it will help to change Boost version.

It looks like this error occurs because of a race in the legacy (v1.1.0) deal handler: it looks up the deal by ID before the deal has made it onto chain. This error might also occur when there's a chain re-org, although given that you're seeing the error quite often that seems less likely.
```
StorageDealError: error awaiting deal pre-commit: failed to set up called handler: called check error (h: 1848792): failed to look up deal on chain: deal 6567133 not found - deal may not have completed sealing before deal proposal start epoch, or deal may have been slashed
```

I'd recommend asking the client to switch to use the v1.2.0 protocol. With deals made over the v1.2.0 protocol (and the [latest RC of Boost](https://github.com/filecoin-project/boost/releases/tag/v1.0.0-rc2)) you can retry deals that fail at the add piece stage.

Note also that the v1.2.0 deal handler in Boost doesn't do this deal ID lookup so this problem won't occur for v1.2.0 deals.

**Comment by LexLuthr** [comment]
Closing this as Boost does not lookup deals on chain for status. The legacy deals are no loner supported by Boost.
