### ISSUE TITLE
Eliminate unavailable deals from piece store and DAG store

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#553]
When the data for a deal is no longer available, references to the deal should be deleted from the DAG store and from the Piece Store.

The Piece Store keeps a mapping of `piece CID => sector ID, offset in sector, length of piece`.
Note that the same piece can be in multiple sectors:
- `piece CID abcd => sector 5, offset 100, length 1000`.
- `piece CID abcd => sector 18, offset 500, length 1000`.

The DAG store keeps a mapping of
- `piece CID => all CIDs in the piece`
- `CID in the piece => offset in the CAR file`

The DAG store also keeps a separate mapping of
`CIDs in piece => piece CID`

For retrieval by payload CID:
1. Use DAG store `CIDs in piece => piece CID` to map from payload CID to piece CID
2. Use Piece Store to map from piece CID to sector
3. Get a reader over the sector from the sealer API
4. Starting from the payload CID, retrieve the DAG of the CAR file from the reader.
  Use the DAG store `CID in the piece => offset in the CAR file` to map from each CID in the CAR file to the offset of the corresponding block

**Comment by ribasushi** [comment]
@dirkmc this probably needs to be a flag. Many SPs would want to do the exact opposite.

**Comment by dirkmc** [comment]
@ribasushi could you expand on that a little? By the way I've added a bit of detail to the original description for clarity, as the internals of what these components do probably isn't clear to many people.

**Comment by ribasushi** [comment]
@dirkmc it's simple: some folks want to continue serving data from extended sectors ( which still have the data ). They are unable to renew deals in-place due to lack of protocol support, but they are able to keep the underlying sector alive for a *very* long time.
In case of Fil+ this is not that rational, albeit there can be reasons to do so. However for plain deals it is clearly superior: retrieval income can be maintained *and* the PublishDeal/PoRep/ReplicaUpdate cost is not incurred a second time.

**Comment by RobQuistNL** [comment]
That makes sense. There's tons of reasons not to delete the stuff automatically on deal expiration.

If it would be on sector removal - I could agree - but that doesn't happen automatically either.

If someone (or maybe the FVM) wants me to extend a sector that will expire in 3 hours - I'd prefer to keep it around and pulling the data from there, locally. Being able to store data "indefinitely" would also be a nice proposition as an SP.

**Comment by LexLuthr** [comment]
Closing this in favour of https://github.com/filecoin-project/boost/issues/981
This feature will be implemented in the new PieceDirectory replacing dagstore and pieceStore
