### ISSUE TITLE
Improve Fund Management UX

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#557]
At the moment fund management in Boost is quite confusing for SPs:
- It's not clear what Tagged, Available and Locked are
- We need to make clearer the purpose of each of the wallets clearer
- We should visually distinguish between things that happen on chain in the Storage Market Actor (adding funds to escrow & locking funds) vs things that Boost is doing (tagging funds)
- We should make clear that the Storage Market Actor is associated with a miner address, not with a particular wallet
- The config value for Deal Collateral is called Pledge Collateral (super confusing, this is something else entirely)

**Comment by jacobheun** [comment]
Closing this as replaced by https://github.com/filecoin-project/boost/issues/726
