### ISSUE TITLE
Fix index provider not starting up if db is corrupted

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#561]

**Comment by masih** [comment]
Original issue here: https://github.com/filecoin-project/index-provider/issues/231

**Comment by masih** [comment]
The latest release of index-provider now has the graceful recovery from corrupt ad entry chunk cache: https://github.com/filecoin-project/index-provider/releases/tag/v0.8.0

**Comment by dirkmc** [comment]
Amazing, thanks @masih 🙏
