### ISSUE TITLE
Unable to view data-transfers

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/boost#566]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 0.0.1+git.e3d45e3
```

### Describe the Bug

When running `boostd data-transfers list` I get error below.
Context: 

- Indexer disabled in config.toml
- Lotus-miner running v1.15.3
- Lotus node var set to LOTUS_RCMGR=0 (per James Bluett)

### Logging Information

```text
Error: fatal error calling 'Filecoin.MarketListDataTransfers': panic in rpc method 'Filecoin.MarketListDataTransfers': runtime error: invalid memory address or nil pointer dereference
```

### Repo Steps

1. Run 'boostd data-transfers list'
2. See error 'Error: fatal error calling 'Filecoin.MarketListDataTransfers': panic in rpc method 'Filecoin.MarketListDataTransfers': runtime error: invalid memory address or nil pointer dereference'
...

**Comment by dirkmc** [comment]
What happens if you set the BOOST_PATH env var?
```
BOOST_PATH=<boost path> boostd data-transfers list
```

**Comment by stuberman** [comment]
@dirkmc 

`BOOST_PATH=/market/.boost boostd data-transfers list`
Error: fatal error calling 'Filecoin.MarketListDataTransfers': panic in rpc method 'Filecoin.MarketListDataTransfers': runtime error: invalid memory address or nil pointer dereference

**Comment by LexLuthr** [comment]
@stuberman Can you set the LOTUS_MAKET_PATH to boost directory and then run the command?

**Comment by stuberman** [comment]
Current paths and vars for boost node
`PATH=/home/stuart/.nvm/versions/node/v16.15.0/bin:/home/stuart/.cargo/bin:/home/stuart/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/market:/market/.boost:/usr/local/go/bin:/usr/local/bin/lotus:/home/stuart/boost/cmd:/usr/local/bin/boost:/usr/local/bin/boostd:/usr/local/bin/boostx:/usr/local/bin/devnet`

TMPDIR=/market/tmpdir
BOOST_PATH=/market/.boost
LOTUS_BACKUP_BASE_PATH=/market/lotus-backups
LOTUS_MINER_PATH=/market/.boost
LOTUS_PATH=/.lotus

**Comment by dirkmc** [comment]
@stuberman is this working for you now?

**Comment by stuberman** [comment]
Yes, it has been working [since I upgraded June 7](https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1654612709169869?thread_ts=1654194474.086719&cid=C03CKDLEWG1).
Now running `boostd --version`

> boostd version 0.0.1+git.de88f8c
