### ISSUE TITLE
Add a boost doctor command to enable SP's to surface known issues

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#582]
In order to help SP's diagnose and fix issues with their system it would be helpful to include a `doctor` command within Boost to run a full diagnostic of subsystems for known issues. This could help alleviate issues that SP's can remedy manually.

## Systems to check (and include commands/docs to run to fix)
_⚠️ This list is not exhaustive, we should aggregate other known system checks to include_

* The number of sealed and unsealed sectors should match. Retrievals will fail if there is no unsealed sector.
* All shards for the dag store should be initialized. Missing shards can result in retrieval failures.
* ...

## Nice to have
* On Boost restart, surface the latest `doctor` diagnostic check in the UI.
* On Boost restart, run and log `doctor` results so SP's know of immediate issues they should resolve

**Comment by LexLuthr** [comment]
1. mh lookup failed error
2. Can we surface piece store overview - keys and state (like yes I can fetch data for it)
3. If a shard cannot initialize  - error why?
4. If there is anything in piece store that does not have corresponding shard

**Comment by brendalee** [comment]
@dirkmc is this the current work you're doing, or is the current boost doctor work just a portion of this?

**Comment by dirkmc** [comment]
I think we can close this one as code complete
