### ISSUE TITLE
Consolidate deal making config

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#586]
Currently we have 2 deal making sections

1. Lotus deal making for legacy
2. Boost deal making for mk 1.2 protocol

The difference between 2 is couple of extra variables. It would be ideal to consolidate these 2 and use extra params based on deal type.

**Comment by dirkmc** [comment]
We decided that because the user may want to have different config for legacy vs boost deals we should keep the separate sections for now
