### ISSUE TITLE
Boost v1.0.0 reports version 0.0.1

### ISSUE THREAD

**Issue by cameronfyfe** [filecoin-project/boost#596]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [X] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boost version 0.0.1+git.12ce769
boostd version 0.0.1+git.12ce769
```

### Describe the Bug

The release candidate commit got tagged as `v1.0.0` but the version reported by the cli apps is still `0.0.1`.

https://github.com/filecoin-project/boost/blob/v1.0.0/build/version.go#L5

### Logging Information

```text
NA
```

### Repo Steps

1. git clone https://github.com/filecoin-project/boost.git
2. cd boost
3. git checkout v1.0.0
4. make boost
5. boost --version

**Comment by dirkmc** [comment]
Thanks for the bug report @cameronfyfe - should be fixed on the `main` branch now
