### ISSUE TITLE
Deal acceptance filter

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#60]
- Integrate the deal acceptance filter
- Make sure that the deal acceptance filter can access these parameters:
  - Available storage space for incoming deals
    Check that there is enough space to store the deal as it is transferred across the wire
  - Available storage space for unsealed / sealed deal
    Check that there is enough space to store the deal in sealed format (and unsealed for fast-retrieval deals)
  - Data transfer url
    Check that provider supports this type of data transfer
  - Sealing pipeline capacity
    Check that pipeline has capacity to seal deal by requested start time
  - Control wallet amount
    Check that provider has enough funds for deal collateral
  - PublishStorageDeals wallet amount
    Check that provider has enough funds to call PublishStorageDeals
  - Data transfer volume
    Check the current data transfer rate and make sure we have bandwidth to accept more
  - Data transfer statistics
    eg Provider has 5 transfers in progress with Estuary, wants to limit max transfers
    eg Maximum number of in-progress deal transfers: global, per client, per specific client

**Comment by nonsense** [comment]
Depends on: https://github.com/filecoin-project/boost/issues/163
