### ISSUE TITLE
feat: enable sending forged deals using boost cli

### ISSUE THREAD

**Issue by nicobao** [filecoin-project/boost#601]
## Current situation

`boost deal` allows users to send  deal proposal to the selected storage provider address. The deal proposal is a JSON file than contains a cryptographic signature.

It is not possible to send an unvalidated JSON to a SP.

## Challenge

At CIDgravity, we want to be able to test the flow end to end from Client to CIDgravity through boost.

## Proposed changes

Create a forged-deal command. I suggest that it would be run as follows: `boost forged-deal --provider=t01000 --file=/path/to/proposal.json`:

- `provider` is the Filecoin storage provider address to send the message to
- `file` is a file path. It would locate the file to be sent on the local machine. Any format is accepted.

If proposal.json doesn't contain the signature, boost will generate it. Otherwise, it is sent as is.

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/

**Comment by nicobao** [comment]
Waiting for @s0nik42 's inputs
