### ISSUE TITLE
Cannot set a high value of storage ask price

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#605]
Anything more than 9 fils results in the below error. We need to allow SPs to be able to set high values when they don't want to make deals. 

mutation {
  storageAskUpdate(update:{
    Price: 90000000000000000000
  } )
}

{
  "errors": [
    {
      "message": "panic occurred: strconv.ParseInt: parsing \"90000000000000000000\": value out of range"
    }
  ]
}

**Comment by willscott** [comment]
it looks like with the newer ask V2 this won't be needed because there's an explicit field for not accepting, https://github.com/filecoin-project/FIPs/issues/225

**Comment by LexLuthr** [comment]
@willscott Unfortunately, that's not the only use case. SPs should be able to set a higher values. Current ceiling is <10fils which is very low.

**Comment by willscott** [comment]
Yep, but lets be clear that the reason shouldn't be to overload it to support a 'don't want to make deals' use case

**Comment by marshyonline** [comment]
When using lotus markets I was able to reject deals on the fly via the CLI, meaning no service restarts or the likes.
With boost this isnt possible - so the only way for me to stop deals is to either kill boost, or set the price high so no deal will ever be proposed at such a price. There are many reasons why someone may not want to accept deals at any time. 
Regardless of what is coming in V2, this is something that i think should be addressed in boost for now.

I see two solutions - A: Create something in the CLI or UI similar to `lotus-miner --call-on-markets storage-deals selection reject/reset` or fix the UI bug and allow SP's to set high prices.

**Comment by willscott** [comment]
@LexLuthr  i'm looking and don't see any successful deals having happened for >10fil. Do we have a use case for accepting individual deals at >10fil?

**Comment by dirkmc** [comment]
@marshyonline are you able to use the deal filter to reject deals? This should be possible with boost if you are using cid gravity or if you set up your own deal filter script:
https://lotus.filecoin.io/storage-providers/advanced-configurations/market/#using-filters-for-fine-grained-storage-and-retrieval-deal-acceptance

**Comment by marshyonline** [comment]
> @marshyonline are you able to use the deal filter to reject deals? This should be possible with boost if you are using cid gravity or if you set up your own deal filter script: https://lotus.filecoin.io/storage-providers/advanced-configurations/market/#using-filters-for-fine-grained-storage-and-retrieval-deal-acceptance

Yes, this would be one way of doing it.
I don't require CID gravity on this miner so I avoiding setting it up just for that feature. 
A filter would be a short term fix, but would make scripting enabling and disabling deals slight more complex than if it was as simple as one or two commands

**Comment by marshyonline** [comment]
The core of this issue really is that when you set the price to anything higher than 10FiL in the UI, it errors and no change is stored.
