### ISSUE TITLE
Add retrieve command to `boost` cli

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#619]
We need to ensure that context cancel is honoured and keep it stateless.
Do we want to do only car files retrieval or do we also want to allow extracting from car file?

**Comment by brendalee** [comment]
@nonsense is this the work that you had started to work on, or if there's another issue can we dedupe

**Comment by nonsense** [comment]
free retrievals over graphsync added at https://github.com/filecoin-project/boost/pull/1131
