### ISSUE TITLE
Add a deal subcommand   --fast-retrieval

### ISSUE THREAD

**Issue by haocai2868** [filecoin-project/boost#621]
boost deal --fast-retrieval
boost offline-deal --fast-retrieval

When there is no need to retrieve data recently, there is no need to store unseal files on the sp side, which can improve storage space utilization

**Comment by brendalee** [comment]
Hey @haocai2868 - thanks for sharing this! Wanting to better understand what your use case is. It would be great to hear more about it. 

Based on my understanding, there is a relatively trusted relationship with SPs and clients making storage deals on Filecoin (large clients/aggregators such as Estuary), and SPs will set the option to keep an unsealed copy on the Lotus side.

**Comment by brendalee** [comment]
we've recently added a flag to storage deal proposal so clients can specify whether or not they want the SPs to store an unsealed copy. fyi @haocai2868 I think that should address what you need!
