### ISSUE TITLE
FR: boost deal-status JSON Output

### ISSUE THREAD

**Issue by marshyonline** [filecoin-project/boost#660]
G'day guys - 

Would be super handy for automation if the command `boost deal-status` could be exported in JSON format

Thanks!

**Comment by LexLuthr** [comment]
This is already implemented in https://github.com/filecoin-project/boost/pull/542
Can you please check and confirm?

**Comment by nonsense** [comment]
As @LexLuthr says, this is already implemented.

```
$ boost --json deal-status --deal-uuid <DEAL-UUID> --provider <PROVIDER>
```
