### ISSUE TITLE
Should automatically recover from: GUI shows all new sectors stuck in Announcing status

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/boost#664]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [X] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.2.0-rc3+git.7665e14
```

### Describe the Bug

After a deal is published, GUI shows announcing status even after deal is sealed and proving.

`lotus-miner version`

> Daemon:  1.16.1+mainnet+git.a2fa07d35+api1.5.0
> Local: lotus-miner version 1.16.1+mainnet+git.a2fa07d35

Boost Storage Deals (new format not legacy display)
**Boost UI is using UTC +4 hours - Miner is using UTC for time**
<img width="847" alt="Boost storage deals" src="https://user-images.githubusercontent.com/49840642/180445334-3221991e-5239-43a9-9690-674cc35265a8.png">

`lotus-miner sectors status --on-chain-info --log 4830`

> SectorID:	4830
> Status:		Proving
> CIDcommD:	baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq
> CIDcommR:	bagboea4b5abcbxmhgyzkmrflbx6n6ghd2prb7bbxxzkca67w7jdocmz3zgcvvzr2
> Ticket:		5e9e9b06e463bd0763f337006da5eeb3d86341f7bd2e3d7d36f405a710ff5a3a
> TicketH:	2002702
> Seed:		cdf33dac37e87c310fbad03b23f235ab51c3ec663430f4219dce4b6fc60a2256
> SeedH:		2004186
> Precommit:	bafy2bzacednryo33j5o7aja7kcsiczu7k726c66vjeepylzbbhfd7nikhlahe
> Commit:		bafy2bzaceaw5hzpszkccgizyw2wkcvfgezhjrh6aokuk7y3kldgj54c33da3q
> Deals:		[8125041]
> Retries:	0
> 
> Sector On Chain Info
> SealProof:		8
> Activation:		2004248
> Expiration:		3475487
> DealWeight:		0
> VerifiedDealWeight:		50467583714918400
> InitialPledge:		1.729361701126415925 FIL
>  
> Expiration Info
> OnTime:		3475488
> Early:		0
> 
> Event Log:
> 0.	2022-07-21 14:15:35 +0000 UTC:	[event;sealing.SectorStart]	{"User":{"ID":4830,"SectorType":8}}
> 1.	2022-07-21 14:15:35 +0000 UTC:	[event;sealing.SectorAddPiece]	{"User":{}}
> 2.	2022-07-21 14:41:19 +0000 UTC:	[event;sealing.SectorPieceAdded]	{"User":{"NewPieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq"}},"DealInfo":{"PublishCid":{"/":"bafy2bzaceb46k5tejvppp2kzw6dxt532zcybf4zjo7yx22phxqm6xhgeazz7u"},"DealID":8125041,"DealProposal":{"PieceCID":{"/":"baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq"},"PieceSize":34359738368,"VerifiedDeal":true,"Client":"f144zep4gitj73rrujd3jw6iprljicx6vl4wbeavi","Provider":"f01278","Label":"mAXASINCFFSKpfCqKbRqCMBeAlYCHOY+57zCUMWsU1u7/RkpX","StartEpoch":2006687,"EndEpoch":3475487,"StoragePricePerEpoch":"0","ProviderCollateral":"7002435018545039","ClientCollateral":"0"},"DealSchedule":{"StartEpoch":2006687,"EndEpoch":3475487},"KeepUnsealed":true}}]}}
> 3.	2022-07-21 14:41:19 +0000 UTC:	[event;sealing.SectorStartPacking]	{"User":{}}
> 4.	2022-07-21 14:41:19 +0000 UTC:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
> 5.	2022-07-21 14:41:19 +0000 UTC:	[event;sealing.SectorTicket]	{"User":{"TicketValue":"Xp6bBuRjvQdj8zcAbaXus9hjQfe9Lj19NvQFpxD/Wjo=","TicketEpoch":2002702}}
> 6.	2022-07-21 17:59:07 +0000 UTC:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"ZZZ}}
> 7.	2022-07-21 18:17:26 +0000 UTC:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bagboea4b5abcbxmhgyzkmrflbx6n6ghd2prb7bbxxzkca67w7jdocmz3zgcvvzr2"},"Unsealed":{"/":"baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq"}}}
> 8.	2022-07-21 18:17:27 +0000 UTC:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzacednryo33j5o7aja7kcsiczu7k726c66vjeepylzbbhfd7nikhlahe"},"PreCommitDeposit":"106752792677538084","PreCommitInfo":{"SealProof":8,"SectorNumber":4830,"SealedCID":{"/":"bagboea4b5abcbxmhgyzkmrflbx6n6ghd2prb7bbxxzkca67w7jdocmz3zgcvvzr2"},"SealRandEpoch":2002702,"DealIDs":[8125041],"Expiration":3475487,"ReplaceCapacity":false,"ReplaceSectorDeadline":0,"ReplaceSectorPartition":0,"ReplaceSectorNumber":0}}}
> 9.	2022-07-21 18:21:00 +0000 UTC:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"ZZZ"}}
> 10.	2022-07-21 19:36:00 +0000 UTC:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"zfM9rDfofDEPutA7I/I1q1HD7GY0MPQhnc5Lb8YKIlY=","SeedEpoch":2004186}}
> 11.	2022-07-21 19:53:14 +0000 UTC:	[event;sealing.SectorProofReady]	{"User":{"Proof":"ZZZ"}}
> 12.	2022-07-21 20:03:20 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}
> 13.	2022-07-21 20:03:20 +0000 UTC:	[event;sealing.SectorCommitSubmitted]	{"User":{"Message":{"/":"bafy2bzaceaw5hzpszkccgizyw2wkcvfgezhjrh6aokuk7y3kldgj54c33da3q"}}}
> 14.	2022-07-21 20:07:00 +0000 UTC:	[event;sealing.SectorProving]	{"User":{}}
> 15.	2022-07-21 20:07:00 +0000 UTC:	[event;sealing.SectorFinalized]	{"User":{}}

### Logging Information
**Boost UI is using UTC +4 hours - Miner is using UTC for time**

```text
Deal b6b617b6-3749-41d7-87f3-4ded218ec0c5
CreatedAt	2022-07-21 08:54:26.832 (a day ago)
Client Address	f144zep4gitj73rrujd3jw6iprljicx6vl4wbeavi
Client Peer ID	QmbtapmGKVN9HQw9yTVjrUfzsVA18DycBUyA5FF66qtRJe
Signed Proposal CID	bafyreiegiw5klcwmfy3ntwxezp5su26rpybphm2g2tj3zlo3u5hdb5q52m
Deal Data Root CID	bafybeigqquksfkl4fkfg2gucgalybfmaq44y7oppgckdc2yu23xp6rskk4
Verified	Yes
Piece CID	baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq
Piece Size	32 GiB (34,359,738,368 bytes)
Client Collateral	0 atto
Provider Collateral	0.007 FIL
Storage Price / epoch / GiB	0 atto
Current Epoch	2,006,296
Start Epoch	2,006,687 (in 3h)
End Epoch	3,475,487 (in a year)
Duration	1,468,800 (509 days)
Storage Fee	0 atto (Price per epoch x Piece Size x Duration)
Transfer Mode	Online
Transfer Type	http
Transfer Size	23.4 GiB (25,104,827,999 bytes)
Transfer Params	
URL: https://app-cargo.fil.riba.cloud/deal-cars/de21dae84efc65410f5d3111c674fded_baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq.car
Transferred	23.4 GiB (25,104,827,999 bytes)
Inbound File Path	/market/.boost/incoming/b6b617b6-3749-41d7-87f3-4ded218ec0c5.download
Sector ID	4830
Sector Data Offset	0
Sector Data Length	34,359,738,368
Publish Message CID	bafy2bzaceb46k5tejvppp2kzw6dxt532zcybf4zjo7yx22phxqm6xhgeazz7u
Chain Deal ID	8,125,041
Checkpoint	AddedPiece (a day ago)
Status	Announcing
Deal Logs
2022-07-21 08:54:26.021		
executing deal proposal received from network
peer: QmbtapmGKVN9HQw9yTVjrUfzsVA18DycBUyA5FF66qtRJe
2022-07-21 08:54:26.030	9ms	
processing deal acceptance request
2022-07-21 08:54:26.823	793ms	
tagged funds for deal
tagged for deal collateral: 7,002,435,018,545,039
tagged for deal publish: 150,000,000,000,000,000
total available for collateral: 28,075,134,077,772,133,470
total available for publish: 24,334,770,447,640,689,245
total tagged for collateral: 7,002,435,018,545,039
total tagged for publish: 150,000,000,000,000,000
2022-07-21 08:54:26.830	7ms	
created deal download staging file
path: /market/.boost/incoming/b6b617b6-3749-41d7-87f3-4ded218ec0c5.download
2022-07-21 08:54:26.835	5ms	
inserted deal into deals DB
2022-07-21 08:54:26.837	2ms	
deal accepted and scheduled for execution
2022-07-21 08:54:26.838	1ms	
deal execution initiated
deal state: 
2022-07-21 08:54:26.848	10ms	
size of downloaded file
filepath: /market/.boost/incoming/b6b617b6-3749-41d7-87f3-4ded218ec0c5.download
size: 0
2022-07-21 08:54:26.851	3ms	
deal execution in progress
2022-07-21 08:54:26.854	3ms	
transferring deal data
transfer client id: 
2022-07-21 08:54:26.857	3ms	
http-transport: execute transfer
deal size: 25,104,827,999
output file: /market/.boost/incoming/b6b617b6-3749-41d7-87f3-4ded218ec0c5.download
time before context deadline: 23h59m59.999958461s
2022-07-21 08:54:26.859	2ms	
http-transport: existing file size
deal size: 25,104,827,999
file size: 0
2022-07-21 08:54:26.861	2ms	
http-transport: http url
url: https://app-cargo.fil.riba.cloud/deal-cars/de21dae84efc65410f5d3111c674fded_baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq.car
2022-07-21 08:54:26.864	3ms	
http-transport: started async http transfer
2022-07-21 08:54:26.864	0ms	
http-transport: sending http request
range-rq: bytes=0-
received: 0
remaining: 25,104,827,999
2022-07-21 08:55:39.963	1m	
transfer progress
bytes received: 2,510,489,309
deal size: 25,104,827,999
percent complete: 10
2022-07-21 08:56:57.277	1m	
transfer progress
bytes received: 5,020,994,865
deal size: 25,104,827,999
percent complete: 20
2022-07-21 08:58:12.936	1m	
transfer progress
bytes received: 7,531,459,609
deal size: 25,104,827,999
percent complete: 30
2022-07-21 08:59:26.600	1m	
transfer progress
bytes received: 10,041,936,593
deal size: 25,104,827,999
percent complete: 40
2022-07-21 09:00:38.569	1m	
transfer progress
bytes received: 12,552,423,857
deal size: 25,104,827,999
percent complete: 50
2022-07-21 09:02:41.161	2m	
transfer progress
bytes received: 15,062,913,045
deal size: 25,104,827,999
percent complete: 60
2022-07-21 09:04:59.295	2m	
transfer progress
bytes received: 17,573,383,285
deal size: 25,104,827,999
percent complete: 70
2022-07-21 09:07:04.280	2m	
transfer progress
bytes received: 20,083,903,605
deal size: 25,104,827,999
percent complete: 80
2022-07-21 09:09:06.273	2m	
transfer progress
bytes received: 22,594,358,389
deal size: 25,104,827,999
percent complete: 90
2022-07-21 09:11:07.990	2m	
http-transport: http server sent EOF
deal-size: 25,104,827,999
received: 25,104,827,999
2022-07-21 09:11:07.990	0ms	
transfer progress
bytes received: 25,104,827,999
deal size: 25,104,827,999
percent complete: 100
2022-07-21 09:11:08.080	90ms	
http-transport: http transfer completed successfully
2022-07-21 09:11:08.150	70ms	
http-transport: http request finished successfully
file size: 25,104,827,999
nBytesReceived: 25,104,827,999
2022-07-21 09:11:08.359	209ms	
deal data-transfer completed successfully
bytes received: 25,104,827,999
time taken: 16m41.502203869s
2022-07-21 09:11:08.396	37ms	
checking commP
2022-07-21 09:25:03.561	14m	
commP matched successfully: deal-data verified
2022-07-21 09:25:03.665	104ms	
updated deal checkpoint in DB
new checkpoint: Transferred
old checkpoint: Accepted
2022-07-21 09:25:04.445	780ms	
deal data transfer finished successfully
2022-07-21 09:25:04.574	129ms	
deal data-transfer can no longer be cancelled
2022-07-21 09:25:04.602	28ms	
sending deal to deal publisher
2022-07-21 10:09:17.936	44m	
updated deal checkpoint in DB
new checkpoint: Published
old checkpoint: Transferred
2022-07-21 10:09:18.061	125ms	
deal published successfully, will await deal publish confirmation
2022-07-21 10:09:18.081	20ms	
awaiting deal publish confirmation
2022-07-21 10:15:35.213	6m	
deal publish confirmed
2022-07-21 10:15:35.257	44ms	
updated deal checkpoint in DB
new checkpoint: PublishConfirmed
old checkpoint: Published
2022-07-21 10:15:35.277	20ms	
deal successfully published and confirmed-publish
2022-07-21 10:15:35.338	61ms	
funds successfully untagged for deal after publish
2022-07-21 10:15:35.359	21ms	
add piece called
2022-07-21 10:41:19.214	26m	
added new deal to sector
sector: 4,830
2022-07-21 10:41:19.243	29ms	
deal successfully handed to the sealing subsystem
length: 34,359,738,368
offset: 0
sectorNum: 4,830
2022-07-21 10:41:19.265	22ms	
updated deal checkpoint in DB
new checkpoint: AddedPiece
old checkpoint: PublishConfirmed
2022-07-21 10:41:19.715	450ms	
deal successfully handed over to the sealing subsystem
2022-07-21 10:41:20.569	854ms	
removed inbound file as deal handed to sealer
path: /market/.boost/incoming/b6b617b6-3749-41d7-87f3-4ded218ec0c5.download
2022-07-21 10:41:20.608	39ms	
untagged storage space
2022-07-21 10:41:20.619	11ms	
storage space successfully untagged for deal after it was handed to sealer
2022-07-21 10:41:20.645	26ms	
deal successfully added to piecestore
```

### Repo Steps

Checking these deals, I see that the shard status is 'new' and Boost does not allow the piece to be initialized:

`boostd dagstore list-shards | grep baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq`
baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq  New

`boostd dagstore initialize-shard baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctk`
**[No result after 12 hours - and I cancel - control C the command]**
^CError: context canceled

`boostd dagstore list-shards | grep baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq`
baga6ea4seaqesqa32ou6uqbdnrgazzw4yqx4jrs5piz3aqxezxpnnu67acctklq  New

**Comment by stuberman** [comment]
Reboot resolved the dagstore problems. Oddly nothing special had happened when the dagstore stopped working and no errors were logged. Once boost node was restarted the shards then started to initialize and now all of  them are displaying properly in the UI without additional effort. Just realize each shard takes about 5  minutes to initialize.

**Comment by jacobheun** [comment]
I'm going to reopen this and track for auto recovery. It's great the idempotent restarts are working well, but it sounds like we're hitting a recoverable error here that we should auto retry and not require a restart to do so.

**Comment by LexLuthr** [comment]
@jacobheun Auto recovery is what actually helped here. When Boost was restarted, auto recovery triggered shard initialization as expected and everything was resolved without intervention. I have opened https://github.com/filecoin-project/boost/issues/669 to track the underlying issue.

**Comment by jacobheun** [comment]
I'm saying we shouldn't need the restart. We only initiate recovery on restart iirc, we shouldnt need to wait for that.

**Comment by LexLuthr** [comment]
Deal recovery can be done manually as well but that only happens when there is a failure. In this case there was no failure.
My observation was that dagstore was not responding properly and deal was stuck in limbo but not failed.  Thus auto recovery never came into picture till the restart happened and boost saw that deals the not indexed and it triggered a recovery.

**Comment by LexLuthr** [comment]
@stuberman Have you faced this issue again? Can you run your boostd with flag --pprof. This will allows us to dump goroutines in case we run into this situation again.

**Comment by LexLuthr** [comment]
Whenever, you restart boost next, please run it with --pprof. Let's monitor for few more days. If we see nothing then we can make a decision.

**Comment by stuberman** [comment]
I just restarted using `nohup boostd run --pprof >> /market/logs/boost.log 2>&1 &`
running boostd version 1.3.0-rc1+git.b85d1b9

**Comment by stuberman** [comment]
Seeing same issue with `boostd version 1.4.0-rc2+git.a425103`

**Comment by LexLuthr** [comment]
@stuberman Did you get a goroutine dump? Can you upload it here?

**Comment by stuberman** [comment]
[dump.log](https://github.com/filecoin-project/boost/files/9478229/dump.log)

**Comment by LexLuthr** [comment]
@nonsense Can you take a look at the dump?
