### ISSUE TITLE
Config Option To Record Support For HTTP

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/boost#667]
# Goals

Providers need to have a way to indicate they are running booster-http for the QueryAsk v2 protocol

# How

1. Add a "HTTPRetrievalURL" string to https://github.com/filecoin-project/boost/blob/fe1b0139be4c769a1348abd9bb0a6e4e55973435/node/config/types.go#L123

2. When the URL is not a blank string, QueryAskV2 will return HTTP options. When it's blank, from QueryAsk v2's point of view, HTTP retrieval is disabled.

This config is the PUBLIC url for HTTP retrieval. Currently, booster HTTP only allows configuring the port, and doesn't support HTTPS. The assumption is if you want your server to run over HTTPS, on a different port externally, or with a filter, it's configured through an Nginx/Apache reverse proxy. 

# For Discussion

The current proposal is this URL is set manually in the config file, independently of booster-http being started/stopped. That means that there's no guarantee it's correct, or that while set, booster-http is actually running. Should we try to do something to disable returning the URL when booster-http is stopped?

**Comment by jacobheun** [comment]
> Should we try to do something to disable returning the URL when booster-http is stopped?

I think we could do this later. It should be fairly trivial to have booster-http tell boost to enable/disable on startup/shutdown via the boost api. This might get annoying to track if we go beyond 1:1 scaling. If we ended up doing public endpoint configuration through a boost-http flag on startup, then we'll probably want to enable this.
