### ISSUE TITLE
Boost goroutine dump

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#669]
We need a way to safely dump all the goroutine from boost, dagstore, piece store and other related processes.
Today, we came across a [situation](https://github.com/filecoin-project/boost/issues/664) where dagstore was not initalizing the shards after deal completed sealing. I think we were stuck at https://github.com/filecoin-project/boost/blob/7de8020c418e7e6d546c4bdb98b35182d8bcd33a/storagemarket/deal_execution.go#L653 but no logs were being generated from dagstore at all. 
Dagstore was responding to queries with "mh" not found but nothing else was working(manual commands too failed). This was resolved with boost restart.
With the plan to make boost multi-node this would be helpful when something is stuck.

**Comment by stuberman** [comment]
FYI - this morning experienced the same issue with all new deals stuck in announce state in UI.  Restarting boostd resolved issue.

**Comment by dirkmc** [comment]
`boostd` can be run with the `--pprof` flag
