### ISSUE TITLE
Depend on standard go-car release

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/boost#670]
Currently Boost is dependenging on a custom branch of go-car:

https://github.com/filecoin-project/boost/blob/main/go.mod#L65
```
github.com/ipld/go-car v0.4.1-0.20220707083113-89de8134e58e
github.com/ipld/go-car/v2 v2.4.2-0.20220707083113-89de8134e58e
```

I believe this is for the extra functionality in https://github.com/ipld/go-car/pull/290.

I'd like to get this resolved given the complications it caused when resolving [GHSA-9x4h-8wgm-8xfg](https://github.com/ipld/go-car/security/advisories/GHSA-9x4h-8wgm-8xfg).  The reason to prioritize this is so we maintain good operational posture for a future go-car event by reducing moving pieces.

**Comment by jacobheun** [comment]
Looking at resolving this by landing https://github.com/ipld/go-car/pull/291.
