### ISSUE TITLE
Limit parallel HTTP downloads for storage deals

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#705]
Currently boost has a config option to limit parallel Graphsync downloads.

We should add a config option to
- limit parallel HTTP downloads per peer (eg max 20 concurrent downloads to peer A)
- limit parallel HTTP downloads overall (eg max 100 concurrent downloads to all peers)

Note that the limit is on boost downloading data for storage deals.

**Comment by willscott** [comment]
i wonder if this is the right policy knob to give providers:
* at the highest level, it could be reasonable to allow for limitation of overall bandwidth "use 100mbit". that seems preferable over a number of streams, where if they get connected to by slow peers they'd have 100 downloads but wouldn't use any bandwidth.
* Why do we want to limit 1 peer? in the case next 6 months this seems like the primary effect is to encourage degraded service in our common use case of the HTTP gateways pulling a bulk of content from SPs?

**Comment by nonsense** [comment]
> Why do we want to limit 1 peer?

If we are downloading 100 deal each 512MiB, ideally we want to have some concurrency factor, and not download them all at the same time, because then the sealing pipeline would be idle. We want to continuously stage data for the sealing pipeline and not get it downloaded at the same time and passed-through in a huge chunk.

**Comment by willscott** [comment]
is this for downloading by the SP from data providing client, or retrieval downloads _from_ the SP

**Comment by dirkmc** [comment]
I added a note to the description to clarify that the limit is on boost downloading data for storage deals (not retrieval)

**Comment by nonsense** [comment]
the former - downloading by the SP (i.e. storage deal)

**Comment by dirkmc** [comment]
For http retrieval there are existing tools that SPs can use to rate limit (eg nginx has rate limiting features)

**Comment by hannahhoward** [comment]
@willscott for existing SPs, this is similar to the knobs they have for graphsync. I don't know if "keep it familiar" is the design goal, but my recollection is we tried to collect feedback before on what was ideal and this is what they wanted.

**Comment by hannahhoward** [comment]
Is it a cross protocol knob? Like are we applying it to Legacy SPs as well?
