### ISSUE TITLE
SimultaneousTransfersForStorage not workiing for Boost deals

### ISSUE THREAD

**Issue by cerblue** [filecoin-project/boost#708]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.3.0+git.4334f92
```

### Describe the Bug

Boost would accept ~20 deals at once and start transfers with all of them, despite SimultaneousTransfersForStorage set to 5.

### Logging Information

```text
-
```

### Repo Steps

1. Run Boost daemon
2. Wait for Boost deals to come in
3. See data transfers of all deals start right away

**Comment by LexLuthr** [comment]
Closing this in favor of https://github.com/filecoin-project/boost/issues/705 
We are already working on fixing this.
