### ISSUE TITLE
Announce Bitswap service multiaddrs to the Network Indexers

### ISSUE THREAD

**Issue by jacobheun** [filecoin-project/boost#711]
Currently only Graphsync records are announced to the network Indexers. When Bitswap is enabled we need to announce the multiaddrs of the service to the network as well.

**Considerations**
As Bitswap runs as a separate service we need a way to pass its multiaddrs to the index provider for announcing records.

**Comment by jacobheun** [comment]
With the current state of index announcements we need graphsync and bitswap records to all point back to the same node. We'll need to be able to route bitswap requests through the index announcement libp2p node (which is the Boost node today). It's currently not possible to point different protocol indexing records to different multiaddrs (even if the libp2p keypair was shared).

**Comment by ribasushi** [comment]
@jacobheun @willscott this is potentially a blocker, can we dig into the source of this limitation? My understanding is that elasticprovider does exactly this: they announce a peerid which is different from the announcer...

**Comment by willscott** [comment]
It's the addition and removal of identities that's expensive for the indexer. elastic provider has a single provider identity that all the cids map to.

the ask here was to take all the cids sp's have already announced, and now say "this new provider also announces all of that same content"

in the current indexer model, that's a whole new chain of a new provider, and as expensive as re-ingesting the whole chain. (each cid gets a new value entry put in to it's entry)

having those flap isn't something we'll really be able to tolerate right now, but we're working on it.

**Comment by LaurenSpiegel** [comment]
As an interim solution, there has been discussion of the SP's running a load balancer like https://github.com/mcamou/go-libp2p-kitsune.  By using a load balancer we will be able to retrieve old and new CID's via bitswap even before work is done on https://github.com/filecoin-project/storetheindex/issues/678.

Putting diagrams from @willscott here for future reference --

Current state--
<img width="791" alt="image" src="https://user-images.githubusercontent.com/7368115/185509288-4e6ab30e-cb1d-40b3-9416-2d9ca80f7e8d.png">


<img width="807" alt="image (1)" src="https://user-images.githubusercontent.com/7368115/185509338-6f5b966e-4b77-42cb-bb2a-f39e559d98dd.png">

<img width="839" alt="image (2)" src="https://user-images.githubusercontent.com/7368115/185509347-88fa018a-9f2d-47bf-9d8f-0f2b6aafd566.png">

<img width="832" alt="image (3)" src="https://user-images.githubusercontent.com/7368115/185509356-30be138b-ea4b-45f6-b35e-9d6074a20052.png">

**Comment by LaurenSpiegel** [comment]
Since the indexer will be accepting different transport protocols after work in q4, is there still a strict need for a load balancer?

**Comment by LaurenSpiegel** [comment]
Sounds like we can work on the load balancer as a separate effort.

**Comment by hannahhoward** [comment]
@willscott looking forward on this ticket for Q4 Bitswap + Evergreen, what work is needed from the indexer side? Is it tracked somewhere?

**Comment by willscott** [comment]
we can track under https://github.com/filecoin-project/storetheindex/issues/678

**Comment by jacobheun** [comment]
This is complete. https://github.com/filecoin-project/boost/pull/967 is a new version to update to index families, so tracking that separately.
