### ISSUE TITLE
booster-bitswap add option to limit the number of simultaneous peer connections

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/boost#716]
# What

On top of https://github.com/filecoin-project/boost/pull/707, add a CLI option to limit the number of simultaneous peer connections in the booster-bitswap libp2p node. The most straightforward way to do this is almost surely with the libp2p resource manager, which allows setting a maximum number of simultaneous connections -- https://github.com/libp2p/go-libp2p/tree/master/p2p/host/resource-manager

**Comment by dirkmc** [comment]
It might make more sense to have a bandwidth limit on peers, rather than a connection limit.
For example a peer can send many "do you have this block" messages, which don't transfer much data, or it can send many "give me block xyz" messages that can be around 1mb in size.

**Comment by LaurenSpiegel** [comment]
@ribasushi, any reason to do number of peers rather than bandwidth per peer?

**Comment by ribasushi** [comment]
@LaurenSpiegel I strongly prefer and originally requested BW-based metrics and limits, but we do not have the technology within libp2p. So it was relegated to "have an SP set OS-level traffic controls".

**Comment by LaurenSpiegel** [comment]
@dirkmc , is there a way to make @ribasushi 's dream come true?

**Comment by hannahhoward** [comment]
@LaurenSpiegel jumping in, to add bandwidth based metrics and limits, we'd need some upstream changes in go-bitswap and dependent libraries, assuming we're not trying to do this completely at the libp2p level. I think we're more likely to get changes at the level of go-bitswap and dependent libraries, and I have ideas on how to make that happen. However, we would at minimum need to work with @jorropo and @guseggert on that.

**Comment by hannahhoward** [comment]
I also believe bandwidth limits per peer and other associated controls is something several have asked for in go-bitswap, so maybe we can get traction on that. I know go-bitswap code fairly well and could personally make a PR, but I don't think other members of Tornado have that background.

**Comment by hannahhoward** [comment]
There are ultimately two concerns:

- bandwidth limiting of bitswap overalll
    - docs around traffic shapping for a booster-bitswap process
    *or*
    - a technical code feature to limit bandwidth in bitswap server or Libp2p (if possible)

- fairness among peers
   - one peer should be not be able to DDOS a connection and tie up everything
   - probably already done within Bitswap

- CIDGravity
   - need to make sure docs clarify retrieval controls only apply to GraphSync
   - cc: @s0nik42

**Comment by hannahhoward** [comment]
closing in favor of #954 

This describes how this requirement is actually being implemented, and is already implemented with #1020
