### ISSUE TITLE
Check tests in `test-all` for correctness

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#720]
Over the time, some tests in `test-all` in the CI fail for no good reason. As per my observation, these failures are around resumption tests. We should maybe revisit the tests and make sure they are not flaky. 
There have been multiple instances of failure where rerunning the job passes the test.

https://app.circleci.com/pipelines/github/filecoin-project/boost/2000/workflows/86bfb3e3-7200-4707-956f-69a2dfad6219/jobs/15762

https://app.circleci.com/pipelines/github/filecoin-project/boost/2000/workflows/583e9761-98f0-4414-9d2c-fcd214970bed/jobs/15753

**Comment by jacobheun** [comment]
@LexLuthr does this still occur? Do we still need to audit these?

**Comment by LexLuthr** [comment]
I think we can close it
