### ISSUE TITLE
Merge Piece Meta store codebase and boostd-data service behind a feature flag

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/boost#727]
Given that the changeset at https://github.com/filecoin-project/boost/pull/573 is becoming increasingly larger and complex, we should release the Piece Meta store / boostd-data service feature behind a feature flag, so that we manage complexity of upcoming PRs and can continuously test the feature before marking it experimental and stable / GA.

Ultimately this is a step on the path to:
- refactor the data model and schema for deals on Boost and allow for data to be stored in an external database
- migrate all data from the DAGStore into the Piece Meta store
- refactor Boost into a stateless service, so that we can scale it horizontally

**Comment by jacobheun** [comment]
@nonsense this can be closed correct?
