### ISSUE TITLE
Update `config.toml` with the right env vars - Unable to set custom path for dagstore!

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/boost#746]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [X] Other

### Boost Version

```text
boostd version 1.4.0-rc1+git.e5b59d2
```

### Describe the Bug

**Hi Boost team!** 👋

Im unable to set a custom path for my dagstore. The node wont start - _it worked on legacy._ 

`Error: creating node: applying node options failed: Detected custom DAG store path /markets/boost/dagstore. The DAG store must be at $BOOST_PATH/dagstore`

Also, if possible at this stage remove Lotus Markets Path/explanation and envvar in Boost config file. 

```
[DAGStore]
  # Path to the dagstore root directory. This directory contains three
  # subdirectories, which can be symlinked to alternative locations if
  # need be:
  # - ./transients: caches unsealed deals that have been fetched from the
  # storage subsystem for serving retrievals.
  # - ./indices: stores shard indices.
  # - ./datastore: holds the KV store tracking the state of every shard
  # known to the DAG store.
  # Default value: <LOTUS_MARKETS_PATH>/dagstore (split deployment) or
  # <LOTUS_MINER_PATH>/dagstore (monolith deployment)
  #
  # type: string
  # env var: LOTUS_DAGSTORE_ROOTDIR
   RootDir = ""
```

### Logging Information

```text
Shown above.
```

### Repo Steps

1. Set custom path for dagstore in your `config.toml`
2. Boost node wont start.

**Comment by LexLuthr** [comment]
This is by design. We have removed the custom path for dagstore. If you wish to use a custom path, create a symlink to the path in the `.boost` directory to an external dagstore location. It should work.

**Comment by Reiers** [comment]
...

**Comment by Reiers** [comment]
Remove functionally from the Markets and rely on symlink instead.. 
Remember a lot of people are going to jump over to Boost with this setting, and having issues with your Boost on your first run its not fun...

Anyway, the whole config should be removed from config file - since its no longer a option and doesn't block people.

**Comment by LexLuthr** [comment]
Unfortunately, we could not phase it out because of migration(copying over the config values). As soon as everyone has switches to boost, we will be removing that variable.
