### ISSUE TITLE
Inspect tool does not show result for indexed CID

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#748]
I was debugging a retrieval issue with one of the payload with Stuart from PikNik and we came across a situation that payload CID "QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6" was retrievable over the http (failed over graphsync).
Dagstore has this payload CID indexed in correct pieceCID and if we search for the pieceCID in Inspect we get back all the details about that piece.

We need to review how we are querying in Inspect tool works and why a indexed payload CID did not return the correct details.

**Comment by stuberman** [comment]
Issue noticed when @hannahhoward attempted to retrieve a deal from f01278:

`boostd data-transfers list -v`

> Sending Channels
> 
> ID          Status      Sending To                      Root Cid                    Initiated? Transferred Voucher                                                                                                                             
> 1661494380561613205 ResponderPaused 12D3KooWPmm3iECH2vjdezfxwKeEbHJ5RmcyT3Bz2zsPZmNZURiS QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6 N      0B      {"PayloadCID":{"/":"QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6"},"ID":533166,"Selector":{"Raw":"oWFSomFsoWRub25loGI6PqFhYaFhPqFhQKA="},"PieceCID":null,"PricePerByte":"0","PaymentInterval":10485760,"PaymentIntervalIncrease":10485760,"UnsealPrice":"0"}  
>  Message: stream reset

Using Boost Inspector for `QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6` yielded no results.
After retrieving over HTTP, Inspector still yielded no results although we saw this

`curl http://localhost:7777/payload/QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6 > /market/download.piece`

 | % Total | % Received | % Xferd | Average Speed | Time | Time | Time | Current | Dload | Upload | Total Spent | Left  Speed  | 
 | -  | -  | -  | -  | -  | -  | -  | -  | - | -  | -  | - |
 | 100 | 31.7G | 100 | 31.7G | 0 | 0 | 110M | 0 | 0:04:54 | 0:04:54 | --:--:-- | 110M | 

`boostx commp /market/download.piece`

> CommP CID:  baga6ea4seaqbkguoaif4qvdzma6syixru56wb3b72uwiohgq3uebemwwnlwocla
> Piece size:  34359738368
> Car file size:  34091302912

`boostd pieces piece-info baga6ea4seaqbkguoaif4qvdzma6syixru56wb3b72uwiohgq3uebemwwnlwocla`

> Piece:  baga6ea4seaqbkguoaif4qvdzma6syixru56wb3b72uwiohgq3uebemwwnlwocla
> Deals:

| DealID | SectorID |  Length | Offset | 
| - | - | - | - | 
| 2757338 | 2579 | 34359738368 | 0  | 

`boostd dagstore register-shard baga6ea4seaqbkguoaif4qvdzma6syixru56wb3b72uwiohgq3uebemwwnlwocla`

> Registered shard baga6ea4seaqbkguoaif4qvdzma6syixru56wb3b72uwiohgq3uebemwwnlwocla

`boostd dagstore list-shards | grep baga6ea4seaqbkguoaif4qvdzma6syixru56wb3b72uwiohgq3uebemwwnlwocla`

> baga6ea4seaqbkguoaif4qvdzma6syixru56wb3b72uwiohgq3uebemwwnlwocla  Available

**Comment by stuberman** [comment]
**Inspector result** 
<div class="page-title" style="color: rgb(166, 30, 77); font-size: 1.5em; margin: 1em auto; text-align: center; font-family: &quot;Cerebri Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Inspect Piece metadata</div><div class="inspect" style="color: rgb(18, 38, 63); font-family: &quot;Cerebri Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="search" style="position: absolute; right: 8em; top: 2em;"><input placeholder="piece or payload CID" type="text" value="QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6" style="margin: 0.5em; padding: 0.5em 2em; border: 1px solid rgb(153, 153, 153); border-radius: 0.5em; font-size: 1em; background-image: url(&quot;/static/media/search.b1f781b99ceaafb9c831.svg&quot;); background-position: left 0.5em center; background-repeat: no-repeat;"></div><div class="piece-detail" id="QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6" style="padding: 1em 0px 5em;"><div class="content">

Piece CID | QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6
-- | --
NotFound

<h3 style="color: rgb(166, 30, 77); font-size: 1.25em; font-weight: 400; margin: 2em 0.85em 1em; text-align: left;">Piece Store</h3><p style="padding: 0.5em 1em;">No data found in piece store for piece CID<span> </span>QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6</p><h3 style="color: rgb(166, 30, 77); font-size: 1.25em; font-weight: 400; margin: 2em 0.85em 1em; text-align: left;">Deals</h3><p style="padding: 0.5em 1em;">No deals found with piece CID<span> </span>QmWao9t1wBkQ54T2q4TiiAZfcNNfgwAAxfQK1NsVz9zEL6</p></div></div></div>

**Comment by jacobheun** [comment]
fixed by https://github.com/filecoin-project/boost/pull/998 and available in https://github.com/filecoin-project/boost/releases/tag/v1.5.1-rc2
