### ISSUE TITLE
Piece store clean up after deal expiration or sector loss

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#756]
Currently, the old piece CIDs of expired deal are still kept in the piece store. We can also find the piece CID for the deals where sectors were lost and SP has already been slashed. 
If we end up adding these incorrect piece CIDs to the dagstore as part of fixing the retrievals via `dagstore register-shard` command then this ends up triggering `UNS` jobs on sealer side for non existent sectors.
We should device a strategy to clean up piece store once a deal expires or get slashed. Otherwise, fixing retrievals for older deal would be a much harder challenge where SPs have to trace each piece CID to sector and verify everything is good before adding it to dagstore.

**Comment by stuberman** [comment]
Just to chime in here and relate how painful this is and some suggestions:

I have just a single machine running for more than two years with more than a thousand expired sectors (removed) and a number of sectors that had to be terminated or removed in the course of accepting deals and problems that arose. The current state has resulted in many deals not getting indexed properly (dagstore or piece store) resulting in deals not being retrievable. Also for sectors that lack an unsealed sector the system attempts to unseal the sealed copy and this does not work today. I have been able to manually query both the dagstore and piece store and manually fix some of these issues but this does not scale to SPs that have hundreds of miners/boost nodes. 

**My suggestions:**
Sometimes a deal gets published but does not get sealed, the piece store assumes the deal can be found by unsealing a sector which is already unsealed. Errors include "returning StatusRequestedRangeNotSatisfiable: worker does NOT have unsealed file with unsealed piece, sector:{Miner:1278 Number:2882}, offset:0, size:17045651456"
`Storing in the piece store should occur after a deal and sector are finalized - or use a mechanism to poll sectors and update the db`

There are [duplicate](https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1663090814879769?thread_ts=1662638160.737989&cid=C03CKDLEWG1) pieces in the piece store which throws the counts off.
`Validate whether the piece already exists in the piece store`

Unsealing does not work and creates problems for SPs that have a retrieval or initialization command triggering an unseal. Having an unseal occur on a lotus-miner will often result in PoST faults. Unsealing on sealing workers does not work. There are cases where mass unsealing is triggered and results in a [huge backlog](https://filecoinproject.slack.com/archives/CEHTVSEG6/p1663362567953769?thread_ts=1663362476.129009&cid=CEHTVSEG6) of unseal tasks.
`Make unseal a configurable option for dagstore commands.`

After a sector is terminated or removed, the dagstore and piece stores need to be updated.
`Create an automated process to keep the dagstore and piece store up to date and accurate. Also create a tool/command to manually remove problem entries.`

The [health](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1663360065577799) of the dagstore and piece store is very difficult to discern on local SP machines.
`Create some simple tools/commands to monitor dagstore and piece store health.`

Additional troubleshooting for other errors is warranted such as "Error: failed to register shard: failed to register shard: failed to read/generate CAR Index: invalid header: EOF"
`Identify other dagstore issues and seek remedies`

I has spent in excess of 40 hours trying to reduce the number of errors that are obvious to me and seem to have a manual fix that can be attempted. In some cases, restarting Boost resulted in much of the work being lost and seeing a return of the shards that were not in the "Available State".

### Initial shard counts in August
`boostd dagstore list-shards | wc -l`
5165
`boostd dagstore list-shards | grep Available | wc -l`
4537
`boostd dagstore list-shards | grep New | wc -l` (These have been "stuck" for months)
580
`boostd dagstore list-shards | grep Errored | wc -l`
46
`boostd dagstore list-shards | grep Serving | wc -l`
1
`boostd dagstore list-shards | grep Initializing |wc -l`
0
`boostd dagstore list-shards | grep Recovering |wc -l`
1


### Data before and after manual clean up of DagStore
**BEFORE**
`boostd pieces list-pieces |wc -l`
9801
`boostd dagstore list-shards | awk '{print $1}' | sed 1d | wc -l`
5274
`Identify the missing shards`
4527
`Create a list of shards to be registered with the dagstore. (This would result in days of failures from failed unsealing attempts)`
834
`cat pieces_without_sectors.txt |wc -l`
4597

### Manually checking list of shards (834) and determining which shards could be manually registered
**AFTER** 
`boostd pieces list-pieces |wc -l`
9807
`boostd dagstore list-shards | awk '{print $1}' | sed 1d | wc -l`
5388
`Identify the missing shards`
4419
`Create a list of shards to be registered with the dagstore. (This would result in days of failures from failed unsealing attempts)`
726
`cat pieces_without_sectors.txt |wc -l`
4603

**I was able to manually register 107 shards**

### Current shard counts
`boostd dagstore list-shards | wc -l`
5389
`boostd dagstore list-shards | grep Available | wc -l`
5380
`boostd dagstore list-shards | grep New | wc -l` (These have been "stuck" for months)
0
`boostd dagstore list-shards | grep Errored | wc -l`
8
`boostd dagstore list-shards | grep Serving | wc -l`
0
`boostd dagstore list-shards | grep Initializing |wc -l`
0
`boostd dagstore list-shards | grep Recovering |wc -l`
1

**Detail of errored pieces**

> baga6ea4seaqbckf244y672h6rtjs3a6ax4it6usikq22zz53uxmxf7rrr522egq  Errored    failed to acquire reader of mount on initialization: failed to unseal deal 2858272: failed to unseal piece from sector 2882: unsealing piece: worker UnsealPiece call: context canceled     
       
> baga6ea4seaqbuhhznjpnpmfskl6ehzt6tefnwuanbuhtkykhbyc4kmkkes7bmoa  Errored    failed to acquire reader of mount on initialization: failed to unseal deal 2643110: failed to unseal piece from sector 2255: unsealing piece: worker UnsealPiece call: scheduling request removed  

> baga6ea4seaqepmudbhsxwzipk2jiva5ejtqqtwu4katchvfyaod3kly7meg32ni  Errored    failed to acquire reader of mount on initialization: failed to unseal deal 6238857: failed to unseal piece from sector 4322: unsealing piece: worker UnsealPiece call: scheduling request removed  

> baga6ea4seaqi7wnidwpi5bnx24tivsuzthycmocbhxcud5nyitnpjh27al66ema  Errored    failed to acquire reader of mount on initialization: failed to unseal deal 2863362: failed to unseal piece from sector 2888: unsealing piece: worker UnsealPiece call: scheduling request removed  

> baga6ea4seaqiak7lczyx6dvc7nojgbrk7iybvhsjzrccn3yee3ysb7obw4bk6lq  Errored    failed to acquire reader of mount on initialization: failed to unseal deal 2857374: failed to unseal piece from sector 2882: unsealing piece: worker UnsealPiece call: scheduling request removed  

> baga6ea4seaqmnpfv4l57njhoodnloc3szj7kh7dwh4unal2k2l7szhpow3vjkay  Errored    failed to acquire reader of mount on initialization: failed to unseal deal 2562232: failed to unseal piece from sector 2121: unsealing piece: worker UnsealPiece call: scheduling request removed  

> baga6ea4seaqokkktggdjngfs5h5q3u6wcxvs6c3tn7qyj346corr4qpizay4qha  Errored    failed to read/generate CAR Index: invalid header: EOF          
                                                                                                                                   
> baga6ea4seaqotgmqqawfa76ndz6orzm2si7utkacmq3rh6kiujcpta5hpkr2ehi  Errored    failed to acquire reader of mount on initialization: failed to unseal deal 6401118: failed to unseal piece from sector 4361: unsealing piece: worker UnsealPiece call: scheduling request removed

**Comment by LexLuthr** [comment]
Closing this in favour of https://github.com/filecoin-project/boost/issues/981
This feature will be implemented in the new PieceDirectory replacing dagstore and pieceStore
