### ISSUE TITLE
Error: couldnt import v1.1.0 deal, or find boost deal: handler: websocket connection closed

### ISSUE THREAD

**Issue by donkabat** [filecoin-project/boost#765]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.4.0-rc2+git.52eda3d.dirty
```

### Describe the Bug

Remote commP - No
When I try to use parallel: `boostd import-data` I got very often errors:
`Error: couldnt import v1.1.0 deal, or find boost deal: handler: websocket connection closed`
The error appears only if you run many `import-data` in the same time. For example I'm able to run 3 `import-data` parallel but with delay and I achieve few imports done correctly before the error appears. 

### Logging Information

```text
I see nothing more in logs...
```

### Repo Steps

```
boostd import-data
boostd import-data
```

**Comment by donkabat** [comment]
If boostd is able to handle only one connection than maybe it could try to wait a hile and reconnect instead of halt?

**Comment by LexLuthr** [comment]
@donkabat Can you attach full boost logs and confir(removing any sensitive parameters)

**Comment by LexLuthr** [comment]
I am closing this issue as there have been no new updated from the author. Please feel free to reopen and add the requested logs if you encounter this again.
