### ISSUE TITLE
Remove [LotusDealmaking] MaxStagingDealsBytes

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#818]
Remove the config parameter `[LotusDealmaking] MaxStagingDealsBytes` as it is no longer used (it has been superseded by `[Dealmaking] MaxStagingDealsBytes`).
This change should include a migration that cleans up the parameter from the config file.

**Comment by LexLuthr** [comment]
@dirkmc AFAIK, the `MaxStagingDealsBytes` in lotus config should be in use. It is used to control the size of `.boost/incoming` for the legacy deals. Can you confirm that `MaxStagingDealsBytes` is not used anywhere in go-fil-market?

**Comment by dirkmc** [comment]
Ah yes you're right 👍 
Closing this ticket
