### ISSUE TITLE
Legacy verified deal appears as "not verified" in deals details

### ISSUE THREAD

**Issue by SBudo** [filecoin-project/boost#820]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [X] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.4.0-rc2+git.a425103
```

### Describe the Bug

After receiving a verified legacy deal in boost, if we click on the deal to see the details, the "Verified" variable is set to "No" in the UI

### Logging Information

```text
Not sure what logs to provide
```

### Repo Steps

Accept a legacy verified deal and check the deals details through the UI

**Comment by brendalee** [comment]
@SBudo are you still seeing this issue?

**Comment by stuberman** [comment]
Many people are still seeing this.

https://filecoinproject.slack.com/archives/C03CKDLEWG1/p1679576945954329

**Comment by LexLuthr** [comment]
I am digging into this
