### ISSUE TITLE
Calibration network wallet addresses appears as "f3xxxxx"

### ISSUE THREAD

**Issue by SBudo** [filecoin-project/boost#833]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [X] boost client
- [X] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boost version
```

### Describe the Bug

When boost is installed on the calibration network, all the associated wallets appears as "f3xxxxx" instead of "t3xxxx"
For example, the command `boost wallet list` returns an f3xxxx address

In the boost UI, under the "funds" tab, the wallets appears as "f3xxxx"

### Logging Information

```text
Not sure what log to provide
```

### Repo Steps

Deploy a boost node on the calibration network

**Comment by LexLuthr** [comment]
@SBudo Can you give me quick steps you used to build Boost? This used to be a problem earlier but with `make calibnet`, it should have gone away and it builds underlying `lotus` for calibnet. All actor addresses come from there.

**Comment by SBudo** [comment]
I built lotus with `make clean calibnet` and built boost with `make build`
Was there anything I should have done at the boost built?

**Comment by LexLuthr** [comment]
Try building boost with `make calibnet` instead of `make build`. It will build specifically for calibnet and you should start seeing "txxxxx" instead of "fxxxxx"

**Comment by SBudo** [comment]
Yes, that was the issue, building boost with `make calibne`t instead of `make build calibnet` fixed it.
Thank you! :-)

**Comment by LexLuthr** [comment]
I will update the docs about calibnet. Closing this issue.
