### ISSUE TITLE
Retrievals stopped working (stuck on DealProposed (WaitForAcceptance))

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/boost#846]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [X] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
1.4.0
```

### Describe the Bug

Tried to retrieve data from my node, but was stuck;

```
Recv 0 B, Paid 0 FIL, Open (New), 0s
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 1ms
```

Noted a vague error too;
```
$ boostd data-transfers list
Sending Channels

ID                   Status   Sending To   Root Cid     Initiated?  Transferred  Voucher                                   
1664340793264965768  Ongoing  ...92NHXnvC  ...yqkg5YzX  N           17.61GiB     ...lIncrease":1048576,"UnsealPrice":"0"}  
  Message: queue shutdown
1664340793264965771  Ongoing  ...92NHXnvC  ...nKWMsn81  N           3.27GiB      ...lIncrease":1048576,"UnsealPrice":"0"}  

Receiving Channels

```

Cancelled both, still not working

Restarted boostd, and the retrievals were working again.

**Comment by RobQuistNL** [comment]
It is stuck again

**Comment by RobQuistNL** [comment]
And its stuck again (after increasing `SimultaneousTransfersForRetrieval` to 100 and `SimultaneousTransfersForStoragePerClient` to 20)

**Comment by RobQuistNL** [comment]
Looks like this happens more often while importing deals, and less often when not importing deals.

**Comment by RobQuistNL** [comment]
All was going smoooooth for 2 days (retrieving deals) - until someone started making deals at mass - now the retrievals are hanging at this again;

```
Recv 0 B, Paid 0 FIL, Open (New), 3ms
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 6ms
```

So it seems to have something to do with Boost being busy ?

**Comment by dirkmc** [comment]
It seems likely it's due to the limit on concurrent retrievals.

**Comment by RobQuistNL** [comment]
And how would I verify / fix that? Because there seem to be 2 retrievals open in boost.

**Comment by dirkmc** [comment]
@hannahhoward would you mind taking a look into this one?
