### ISSUE TITLE
booster-http sends complete payload instead of requested CID

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/boost#855]
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [X] boost data-transfer
- [ ] boost index-provider
- [X] Other

### Boost Version

```text
1.4.0
```

### Describe the Bug

```
lotus client retrieve --miner=xxx --maxPrice=0 bafkreib3tgbpfgrvvrpwmji4di4e254dwejdfg7ujq2pkcblxdmhovelcy /tmp/test2.jpg
```
I end up with a 440kb file that is an image. Exactly as expected.

```
lotus client cat --miner=xxx --maxPrice=0 bafkreib3tgbpfgrvvrpwmji4di4e254dwejdfg7ujq2pkcblxdmhovelcy /tmp/test2.jpg
```
I end up with that same data, but in my CLI.

```
curl http://xxxx/payload/bafkreib3tgbpfgrvvrpwmji4di4e254dwejdfg7ujq2pkcblxdmhovelcy
```
I end up with a 1.1GB file

**Comment by RobQuistNL** [comment]
It looks like its always sending the root CID / payload of the CID i send, instead of just the piece I've requested;

```
$ md5sum bafkreie3qzvb7nvdn5dzsmorbrnpwugjjg3duy5ia7ust7cb3ru5p3qx2e 
47444f2a69aeca7db362808a05ee763d  bafkreie3qzvb7nvdn5dzsmorbrnpwugjjg3duy5ia7ust7cb3ru5p3qx2e
$ md5sum bafkreib3tgbpfgrvvrpwmji4di4e254dwejdfg7ujq2pkcblxdmhovelcy
47444f2a69aeca7db362808a05ee763d  bafkreib3tgbpfgrvvrpwmji4di4e254dwejdfg7ujq2pkcblxdmhovelcy
```

These 2 files are next to each other and share the same parent CID / root CID.

**Comment by dirkmc** [comment]
At the the moment the http retrieval endpoints send the entire piece, or the entire car file if the filename ends with `.car`

Could you please describe your use case - do you want to retrieve individual blocks by cid, or all blocks in the DAG under a 
particular cid?

**Comment by RobQuistNL** [comment]
I think it would be best to support both, right? The most important in my opinion would be to be able to fetch all blocks in a particular CID - this way, if we have some deeply nested CID somewhere (which would be a single file) - we can retrieve that directly through HTTP

**Comment by LaurenSpiegel** [comment]
Thanks for opeining @RobQuistNL. We are tracking to prioritize it. Any specifics on the anticipated workload/use case for http retrieval by payload CID would help.

**Comment by RobQuistNL** [comment]
It would allow people to actually access their data from machines in an easy way

**Comment by jacobheun** [comment]
Closing this as the http endpoints have been consolidated as of [v1.5.1-rc1](https://github.com/filecoin-project/boost/releases/tag/v1.5.1-rc1) to only allow full piece retrieval.  

#960 discusses additional endpoints that would support the use case of retrieving individual files over http.
