### ISSUE TITLE
booster-bitswap testing

### ISSUE THREAD

**Issue by LaurenSpiegel** [filecoin-project/boost#861]
Test:
1) on sofia miner
2) SPX
3) a few evergreen participants (could be same as SPX participants)

Testing should confirm:
1) functionality
2) minimal interruptions to other processes (data onboarding and sealing)
3) what maximum load can be sustained

based on requirements here - https://www.notion.so/pl-strflt/Bitswap-Retrieval-Requirements-WIP-ed17a22b006e4ba79c9ca9ec85fcf93e

**Comment by brendalee** [comment]
test discussion : https://github.com/filecoin-project/boost/discussions/1036
