### ISSUE TITLE
[PLACEHOLDER] Ability to enable/disable advertising to the indexer

### ISSUE THREAD

**Issue by LaurenSpiegel** [filecoin-project/boost#862]
Needs to be discussed. This is included as a requirement to include booster-bitswap as a condition to participate in Evergreen.

Need to determine how this will work.

@honghaoq

https://www.notion.so/pl-strflt/Bitswap-Retrieval-Requirements-WIP-ed17a22b006e4ba79c9ca9ec85fcf93e

**Comment by willscott** [comment]
I'm confused about how this can be a requirement - there is no legitimate reason that any content available over booster-bitswap should not be advertised to the indexer.

**Comment by LaurenSpiegel** [comment]
@ribasushi, can you please provide some background on the requirement here?

**Comment by ribasushi** [comment]
Apologies, the line as-written was overloaded with implicit context. The requirement here is for the bitswap codepath to share the same "exclusion list" that SPs use to not advertise their graphsync deals. I.e. whatever SPs use today to say "these CIDs are not something we send to the indexer", needs to be in effect for the (*standalone*) bitswap thing as well.

**Comment by LaurenSpiegel** [comment]
Right now the "don't index" is all or nothing for a whole node (not deal or cid). So it will work the same for bitswap but it is not fine-grained at all. Is this what you had in mind?

We want fine-grained later but seems out of scope for this.

**Comment by LaurenSpiegel** [comment]
Noted. We are working on a more general "do not index" by deal solution.  cc @honghao

I will close this issue since no additional work needed right now directly related to booster-bitswap.

**Comment by hannahhoward** [comment]
@LaurenSpiegel I'm gonna actually close -- cause it doesn't look like this issue was closed. But I think we will need a per-deal general do-not-index (not per protocol ala bitswap)
