### ISSUE TITLE
[Placeholder][Epic] Prepare Boost for lotus markets deprecation

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#874]
# Summary
As Boost matures, it will be default market implementation for Lotus users. Part of this would deprecating the existing lotus markets module and remove the code base from the lotus repo. This change will require moving all market related code from lotus to boost repo and further uncoupling Boost and Lotus.

# Milestones
## 1. Disable lotus markets
- Disabling the APIs and CLIs can be a starting point along with removing market components from `lotus-miner` definition
- Milestone 1 can be done in parallel with any other milestone depending upon the readiness of both teams

## 4. Enable graphsync retrievals in Boost client
- We need to make a decision on payment channels integration here

- [ ] https://github.com/filecoin-project/boost/issues/883

## 5. Remove all market code base from Lotus
- We will keep the go-fil-markets as a lotus dependency to facilitate client side market features in lotus client
- All code base related to lotus market should be removed from lotus as this point

 ## 6. Identify other lotus packages which are used by Boost but are not necessarily related to markets like `cliutils`, `repo` etc
- We need to make a decision if we want to copy over these packages to Boost for further uncoupling Boost and Lotus

**Comment by jacobheun** [comment]
Closing this out in favor of more concrete, boost specific milestones such as the next focus - https://github.com/filecoin-project/boost/milestone/22.
