### ISSUE TITLE
Retrievals load testing

### ISSUE THREAD

**Issue by brendalee** [filecoin-project/boost#877]
We need to have manually triggered tests for retrievals load testing, for each of the data transfer protocols: 
- [x] #892 
- [ ] http
- [x] #891 

Placeholder for work items: 
- testing setup for sofia miner
- consistently measuring response times
- test for low load, average number of requests, max load (can start with autoretrieve metrics history)
- simulate traffic patterns (from autoretrieve first, potentially dotstorage, evergreen)

**Comment by davidd8** [comment]
cc @kylehuntsman @rvagg to consider plugging into this to test the Lassie <> Boost e2e retrieval integration.
