### ISSUE TITLE
Determine a strategy for Bitswap and 3rd party configuration agents like CIDGravity, revisit custom retrieval filter architecture

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/boost#886]
# What

Currently, 3rd party agents like CID Gravity offer robust tools for controlling retrieval through the ability to configure a custom retrieval filter for GraphSync retrievals. Often these custom filters make a per-request HTTP call to an external server. This fundamentally is not performant in a Bitswap context. Currently we don't run the custom retrieval filters at all for Bitswap

We need a way to support agents like CIDGravity in a Bitswap context but we also need to make sure we can insure a satisfactory turn around time on filtering requests.

# How

This is non-urgent as our initial booster-bitswap releases won't support custom filters, but this is something we should consider. Personally I think it's a good opportunity to rethink the whole custom retrieval filter architecture. Perhaps we could provide some kind of sandboxed execution environment for the filter -- a WASM machine with fixed gas limit (though honestly, I hope there is something simpler!)

We can discuss further with @s0nik42 when we meet.

This issue is primarily setup to track the issue.

**Comment by jacobheun** [comment]
Closing as I believe this has been replaced by https://github.com/filecoin-project/boost/issues/954. Feel free to reopen if that's not correct.
