### ISSUE TITLE
Rename HTTP URL from "payload" to something else

### ISSUE THREAD

**Issue by LexLuthr** [filecoin-project/boost#888]
Current setup:

http://URL/pieceCID   returns a unpadded car file of the data

http://URL/pieceCID.car   returns a padded car file of the data (whole piece)

http://URL/payloadCID   returns a unpadded car file of the data

http://URL/payloadCID.car   returns a padded car file of the data (whole piece)

The distinction between the URLs is to allow users to download either by specifying the pieceCID or payloadCID whatever is available to them.

But this gets confusing because payload makes you think that we are talking about the unixfs data here.

Perhaps, we can do it like:

http://URL/pieceCID   returns a unpadded car file of the data

http://URL/pieceCID.car   returns a padded car file of the data (whole piece)

http://URL/payloadCID   returns a unixfs data

http://URL/payloadCID.car   returns a unpadded car file of the data

or rename "payload" to something else to confusion between data and car file. "Payload" also gives you incorrect idea that you can retrieve partial DAGs from within the uploaded car files

**Comment by LexLuthr** [comment]
CC: @hannahhoward @jacobheun @LaurenSpiegel @dirkmc @nonsense 
Please comment your thoughts here and possible alternatives.

**Comment by LaurenSpiegel** [comment]
I liked @jacobheun 's suggestion of using query params.  So, for now there would be one path: `http://foo.com/piece`

With query params--
To get car by piece:
`http://foo.com/piece?piececid=bagaSomePieceCID&format=car`
To get piece by piece:
`http://foo.com/piece?piececid=bagaSomePieceCID&format=piece`
To get car by payload cid:
`http://foo.com/piece?payloadcid=bafySomePayloadCid&format=car`
To get piece by payload cid:
`http://foo.com/piece?payloadcid=bafySomePayloadCid&format=piece`

I might have messed up some of the details there so appreciate 👁️ s and other viewpoints.

**Comment by nonsense** [comment]
I like the suggestion with query params, but I suggest we don't use `piece` as part of the URL, as it has a specific meaning in Filecoin... I'd rather we use `http://foo.com/data` as path.

**Comment by LexLuthr** [comment]
As Anton said, piece has a very specific meaning within Fil. This would also be confusing to Fil people. Perhaps description needs to be updated.

My suggestion:

To get padded car (piece) by pieceCID:  
http://foo.com/piece?piececid=bagaSomePieceCID&format=car
To get unpadded car by pieceCID: 
http://foo.com/piece?piececid=bagaSomePieceCID&format=piece
To get padded car (piece) by payload cid: 
http://foo.com/piece?payloadcid=bafySomePayloadCid&format=car
To get unpadded car by by payload cid: 
http://foo.com/piece?payloadcid=bafySomePayloadCid&format=piece

**Comment by dirkmc** [comment]
In this case the endpoint returns the data for the entire piece, so I think it does make sense to call it piece

**Comment by jacobheun** [comment]
@LexLuthr can you make sure the docs are up to date with these changes - https://boost.filecoin.io/experimental-features/http-retrieval

**Comment by LexLuthr** [comment]
@jacobheun I will be making this change in docs as soon as we cut a new RC or a full release. This PR is not part of the latest RC.
