### ISSUE TITLE
Add tracing to piece directory implementations

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/boost#889]
In order to load testing we should add tracing to the piece directory implementations:
- leveldb
- couchbase

The fuzz test TestServiceFuzz at https://github.com/filecoin-project/boost/pull/573/files#diff-868ff5b51b358e503fe3cd19937cb3a7a3bccf98081d36d0244ceca4297608dbR118 could be used as the basis for a test to make sure that the tracing is working as expected, and to do some load testing on the implementations.

**Comment by kylehuntsman** [comment]
Closed via #894
