### ISSUE TITLE
API replacement for retrieval filter

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/boost#954]
# Goals

Currently, we allow SPs to run a custom retrieval script to enable arbitrary custom retrieval filtering. This isn't scalable for protocols like Bitswap that receive potentially millions of requests for single blocks, especially since many retrieval scripts make calls to external providers to run filtering.

This ticket is to define a data structure to describe filtering rules. Rather than running a custom script, we allow SPs or external providers to provide a set of rules for filtering deals, and then we apply these rules ourselves in process during a retrieval, avoiding an external service call.

In my mind, the most important task is to define the structure of the rules we want to apply. How we fetch and update them is something of a secondary concern. My initial preference is to simply periodically fetch them (every 5 mins) over a REST API. A REST API is extremely simple to implement for external providers. We can consider more complicated tools like Websockets, Libp2p, etc, as time goes on.

# Proposed data structure

We're designing our initial support around the most common provider of custom retrieval filtering capability -- CID Gravity. I'd direct feedback from @s0nik42. What specific parameters from CIDGravity do you want to apply? In my mind I have:
- PeerID white or black list
- Simultaneous retrievals (per hour, per day, at any given time concurrently? I can't remember what your number is)
- CID white or black list

# Filter Scripts Going Forward

Running a pure terminal script for retrieval filter is an ongoing security as well as performance risk on many levels and I'd like to eventually move away from it. At the same time, this will be a very big lift and disruption initially, so to be clear the initial use of this new approach would only apply to Bitswap, where the custom scripts aren't running.

**Comment by willscott** [comment]
> so to be clear the initial use of this new approach would only apply to Bitswap

is this the right place for this?
we also would want it on https://github.com/filecoin-project/boost/pull/946 - so should this be in the piece meta store for caching / aggregation purposes?

**Comment by hannahhoward** [comment]
@willscott yea, we should put it somewhere common. I guess piece metastore is now our common source of truth for data across processes

That all said, I'd like to defer that question and focus on the API design, and what controls we're supporting, and implement an MVP directly in bitswap first, since that's where this is make or break.

**Comment by willscott** [comment]
once we have a proposed API here, we can see if we can convince saturn to use a compatible API - they're currently doing some one-off stuff like https://filecoinproject.slack.com/archives/C03DH0BL02E/p1668779553073199

**Comment by hannahhoward** [comment]
marking done based on final merge of boost branch
